# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Ignore generated code from coverage metrics
ignore:
  # typegen: Generated xDS types from go-control-plane
  - "pkg/xds/types/cds/*_generated.go"
  - "pkg/xds/types/lds/*_generated.go"
  - "pkg/xds/types/rds/*_generated.go"
  - "pkg/xds/types/eds/*_generated.go"
  # controller-gen: Generated DeepCopy methods
  - "apis/v1alpha1/zz_generated*.go"
  # mockgen: Generated test mocks
  - "pkg/xds/mock/*.go"
  # typegen tools themselves (not runtime code)
  - "tools/typegen/**/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

