// Code generated by tools/typegen/lds. DO NOT EDIT.
// Source: github.com/envoyproxy/go-control-plane/envoy/config/listener/v3
// Envoy version: v1.36.0
// To regenerate: make generate-lds

package lds

import (
	"strings"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

var _ = strings.ToUpper // suppress unused import

// AccessLogType is an enum type.
type AccessLogType string

var (
	AccessLogType_name  = map[int32]string{}
	AccessLogType_value = map[string]int32{}
)

func (x AccessLogType) ToInt() int32 {
	return AccessLogType_value[strings.ToUpper(string(x))]
}

// ApiConfigSource_ApiType is an enum type.
type ApiConfigSource_ApiType string

const (
	ApiConfigSource_ApiType_DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE ApiConfigSource_ApiType = "DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE"
	ApiConfigSource_ApiType_REST                                  ApiConfigSource_ApiType = "REST"
	ApiConfigSource_ApiType_GRPC                                  ApiConfigSource_ApiType = "GRPC"
	ApiConfigSource_ApiType_DELTA_GRPC                            ApiConfigSource_ApiType = "DELTA_GRPC"
	ApiConfigSource_ApiType_AGGREGATED_GRPC                       ApiConfigSource_ApiType = "AGGREGATED_GRPC"
	ApiConfigSource_ApiType_AGGREGATED_DELTA_GRPC                 ApiConfigSource_ApiType = "AGGREGATED_DELTA_GRPC"
)

var (
	ApiConfigSource_ApiType_name = map[int32]string{
		0: "DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE",
		1: "REST",
		2: "GRPC",
		3: "DELTA_GRPC",
		5: "AGGREGATED_GRPC",
		6: "AGGREGATED_DELTA_GRPC",
	}
	ApiConfigSource_ApiType_value = map[string]int32{
		"DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE": 0,
		"REST":                                  1,
		"GRPC":                                  2,
		"DELTA_GRPC":                            3,
		"AGGREGATED_GRPC":                       5,
		"AGGREGATED_DELTA_GRPC":                 6,
	}
)

func (x ApiConfigSource_ApiType) ToInt() int32 {
	return ApiConfigSource_ApiType_value[strings.ToUpper(string(x))]
}

// ApiVersion is an enum type.
type ApiVersion string

const (
	ApiVersion_AUTO ApiVersion = "AUTO"
	ApiVersion_V2   ApiVersion = "V2"
	ApiVersion_V3   ApiVersion = "V3"
)

var (
	ApiVersion_name = map[int32]string{
		0: "AUTO",
		1: "V2",
		2: "V3",
	}
	ApiVersion_value = map[string]int32{
		"AUTO": 0,
		"V2":   1,
		"V3":   2,
	}
)

func (x ApiVersion) ToInt() int32 {
	return ApiVersion_value[strings.ToUpper(string(x))]
}

// ComparisonFilter_Op is an enum type.
type ComparisonFilter_Op string

const (
	ComparisonFilter_Op_EQ ComparisonFilter_Op = "EQ"
	ComparisonFilter_Op_GE ComparisonFilter_Op = "GE"
	ComparisonFilter_Op_LE ComparisonFilter_Op = "LE"
)

var (
	ComparisonFilter_Op_name = map[int32]string{
		0: "EQ",
		1: "GE",
		2: "LE",
	}
	ComparisonFilter_Op_value = map[string]int32{
		"EQ": 0,
		"GE": 1,
		"LE": 2,
	}
)

func (x ComparisonFilter_Op) ToInt() int32 {
	return ComparisonFilter_Op_value[strings.ToUpper(string(x))]
}

// FilterChainMatch_ConnectionSourceType is an enum type.
type FilterChainMatch_ConnectionSourceType string

const (
	FilterChainMatch_ConnectionSourceType_ANY                 FilterChainMatch_ConnectionSourceType = "ANY"
	FilterChainMatch_ConnectionSourceType_SAME_IP_OR_LOOPBACK FilterChainMatch_ConnectionSourceType = "SAME_IP_OR_LOOPBACK"
	FilterChainMatch_ConnectionSourceType_EXTERNAL            FilterChainMatch_ConnectionSourceType = "EXTERNAL"
)

var (
	FilterChainMatch_ConnectionSourceType_name = map[int32]string{
		0: "ANY",
		1: "SAME_IP_OR_LOOPBACK",
		2: "EXTERNAL",
	}
	FilterChainMatch_ConnectionSourceType_value = map[string]int32{
		"ANY":                 0,
		"SAME_IP_OR_LOOPBACK": 1,
		"EXTERNAL":            2,
	}
)

func (x FilterChainMatch_ConnectionSourceType) ToInt() int32 {
	return FilterChainMatch_ConnectionSourceType_value[strings.ToUpper(string(x))]
}

// FractionalPercent_DenominatorType is an enum type.
type FractionalPercent_DenominatorType string

const (
	FractionalPercent_DenominatorType_HUNDRED      FractionalPercent_DenominatorType = "HUNDRED"
	FractionalPercent_DenominatorType_TEN_THOUSAND FractionalPercent_DenominatorType = "TEN_THOUSAND"
	FractionalPercent_DenominatorType_MILLION      FractionalPercent_DenominatorType = "MILLION"
)

var (
	FractionalPercent_DenominatorType_name = map[int32]string{
		0: "HUNDRED",
		1: "TEN_THOUSAND",
		2: "MILLION",
	}
	FractionalPercent_DenominatorType_value = map[string]int32{
		"HUNDRED":      0,
		"TEN_THOUSAND": 1,
		"MILLION":      2,
	}
)

func (x FractionalPercent_DenominatorType) ToInt() int32 {
	return FractionalPercent_DenominatorType_value[strings.ToUpper(string(x))]
}

// GrpcStatusFilter_Status is an enum type.
type GrpcStatusFilter_Status string

const (
	GrpcStatusFilter_Status_OK                  GrpcStatusFilter_Status = "OK"
	GrpcStatusFilter_Status_CANCELED            GrpcStatusFilter_Status = "CANCELED"
	GrpcStatusFilter_Status_UNKNOWN             GrpcStatusFilter_Status = "UNKNOWN"
	GrpcStatusFilter_Status_INVALID_ARGUMENT    GrpcStatusFilter_Status = "INVALID_ARGUMENT"
	GrpcStatusFilter_Status_DEADLINE_EXCEEDED   GrpcStatusFilter_Status = "DEADLINE_EXCEEDED"
	GrpcStatusFilter_Status_NOT_FOUND           GrpcStatusFilter_Status = "NOT_FOUND"
	GrpcStatusFilter_Status_ALREADY_EXISTS      GrpcStatusFilter_Status = "ALREADY_EXISTS"
	GrpcStatusFilter_Status_PERMISSION_DENIED   GrpcStatusFilter_Status = "PERMISSION_DENIED"
	GrpcStatusFilter_Status_RESOURCE_EXHAUSTED  GrpcStatusFilter_Status = "RESOURCE_EXHAUSTED"
	GrpcStatusFilter_Status_FAILED_PRECONDITION GrpcStatusFilter_Status = "FAILED_PRECONDITION"
	GrpcStatusFilter_Status_ABORTED             GrpcStatusFilter_Status = "ABORTED"
	GrpcStatusFilter_Status_OUT_OF_RANGE        GrpcStatusFilter_Status = "OUT_OF_RANGE"
	GrpcStatusFilter_Status_UNIMPLEMENTED       GrpcStatusFilter_Status = "UNIMPLEMENTED"
	GrpcStatusFilter_Status_INTERNAL            GrpcStatusFilter_Status = "INTERNAL"
	GrpcStatusFilter_Status_UNAVAILABLE         GrpcStatusFilter_Status = "UNAVAILABLE"
	GrpcStatusFilter_Status_DATA_LOSS           GrpcStatusFilter_Status = "DATA_LOSS"
	GrpcStatusFilter_Status_UNAUTHENTICATED     GrpcStatusFilter_Status = "UNAUTHENTICATED"
)

var (
	GrpcStatusFilter_Status_name = map[int32]string{
		0:  "OK",
		1:  "CANCELED",
		2:  "UNKNOWN",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		5:  "NOT_FOUND",
		6:  "ALREADY_EXISTS",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "FAILED_PRECONDITION",
		10: "ABORTED",
		11: "OUT_OF_RANGE",
		12: "UNIMPLEMENTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		15: "DATA_LOSS",
		16: "UNAUTHENTICATED",
	}
	GrpcStatusFilter_Status_value = map[string]int32{
		"OK":                  0,
		"CANCELED":            1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"UNAUTHENTICATED":     16,
	}
)

func (x GrpcStatusFilter_Status) ToInt() int32 {
	return GrpcStatusFilter_Status_value[strings.ToUpper(string(x))]
}

// HeaderValueOption_HeaderAppendAction is an enum type.
type HeaderValueOption_HeaderAppendAction string

const (
	HeaderValueOption_HeaderAppendAction_APPEND_IF_EXISTS_OR_ADD    HeaderValueOption_HeaderAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_ADD_IF_ABSENT              HeaderValueOption_HeaderAppendAction = "ADD_IF_ABSENT"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS_OR_ADD HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS        HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	HeaderValueOption_HeaderAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	HeaderValueOption_HeaderAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x HeaderValueOption_HeaderAppendAction) ToInt() int32 {
	return HeaderValueOption_HeaderAppendAction_value[strings.ToUpper(string(x))]
}

// KeyValueAppend_KeyValueAppendAction is an enum type.
type KeyValueAppend_KeyValueAppendAction string

const (
	KeyValueAppend_KeyValueAppendAction_APPEND_IF_EXISTS_OR_ADD    KeyValueAppend_KeyValueAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_ADD_IF_ABSENT              KeyValueAppend_KeyValueAppendAction = "ADD_IF_ABSENT"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS_OR_ADD KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS        KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	KeyValueAppend_KeyValueAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	KeyValueAppend_KeyValueAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x KeyValueAppend_KeyValueAppendAction) ToInt() int32 {
	return KeyValueAppend_KeyValueAppendAction_value[strings.ToUpper(string(x))]
}

// Listener_DrainType is an enum type.
type Listener_DrainType string

const (
	Listener_DrainType_DEFAULT     Listener_DrainType = "DEFAULT"
	Listener_DrainType_MODIFY_ONLY Listener_DrainType = "MODIFY_ONLY"
)

var (
	Listener_DrainType_name = map[int32]string{
		0: "DEFAULT",
		1: "MODIFY_ONLY",
	}
	Listener_DrainType_value = map[string]int32{
		"DEFAULT":     0,
		"MODIFY_ONLY": 1,
	}
)

func (x Listener_DrainType) ToInt() int32 {
	return Listener_DrainType_value[strings.ToUpper(string(x))]
}

// RequestMethod is an enum type.
type RequestMethod string

const (
	RequestMethod_METHOD_UNSPECIFIED RequestMethod = "METHOD_UNSPECIFIED"
	RequestMethod_GET                RequestMethod = "GET"
	RequestMethod_HEAD               RequestMethod = "HEAD"
	RequestMethod_POST               RequestMethod = "POST"
	RequestMethod_PUT                RequestMethod = "PUT"
	RequestMethod_DELETE             RequestMethod = "DELETE"
	RequestMethod_CONNECT            RequestMethod = "CONNECT"
	RequestMethod_OPTIONS            RequestMethod = "OPTIONS"
	RequestMethod_TRACE              RequestMethod = "TRACE"
	RequestMethod_PATCH              RequestMethod = "PATCH"
)

var (
	RequestMethod_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "GET",
		2: "HEAD",
		3: "POST",
		4: "PUT",
		5: "DELETE",
		6: "CONNECT",
		7: "OPTIONS",
		8: "TRACE",
		9: "PATCH",
	}
	RequestMethod_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"GET":                1,
		"HEAD":               2,
		"POST":               3,
		"PUT":                4,
		"DELETE":             5,
		"CONNECT":            6,
		"OPTIONS":            7,
		"TRACE":              8,
		"PATCH":              9,
	}
)

func (x RequestMethod) ToInt() int32 {
	return RequestMethod_value[strings.ToUpper(string(x))]
}

// RoutingPriority is an enum type.
type RoutingPriority string

const (
	RoutingPriority_DEFAULT RoutingPriority = "DEFAULT"
	RoutingPriority_HIGH    RoutingPriority = "HIGH"
)

var (
	RoutingPriority_name = map[int32]string{
		0: "DEFAULT",
		1: "HIGH",
	}
	RoutingPriority_value = map[string]int32{
		"DEFAULT": 0,
		"HIGH":    1,
	}
)

func (x RoutingPriority) ToInt() int32 {
	return RoutingPriority_value[strings.ToUpper(string(x))]
}

// SocketAddress_Protocol is an enum type.
type SocketAddress_Protocol string

const (
	SocketAddress_Protocol_TCP SocketAddress_Protocol = "TCP"
	SocketAddress_Protocol_UDP SocketAddress_Protocol = "UDP"
)

var (
	SocketAddress_Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	SocketAddress_Protocol_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x SocketAddress_Protocol) ToInt() int32 {
	return SocketAddress_Protocol_value[strings.ToUpper(string(x))]
}

// SocketOption_SocketState is an enum type.
type SocketOption_SocketState string

const (
	SocketOption_SocketState_STATE_PREBIND   SocketOption_SocketState = "STATE_PREBIND"
	SocketOption_SocketState_STATE_BOUND     SocketOption_SocketState = "STATE_BOUND"
	SocketOption_SocketState_STATE_LISTENING SocketOption_SocketState = "STATE_LISTENING"
)

var (
	SocketOption_SocketState_name = map[int32]string{
		0: "STATE_PREBIND",
		1: "STATE_BOUND",
		2: "STATE_LISTENING",
	}
	SocketOption_SocketState_value = map[string]int32{
		"STATE_PREBIND":   0,
		"STATE_BOUND":     1,
		"STATE_LISTENING": 2,
	}
)

func (x SocketOption_SocketState) ToInt() int32 {
	return SocketOption_SocketState_value[strings.ToUpper(string(x))]
}

// TrafficDirection is an enum type.
type TrafficDirection string

const (
	TrafficDirection_UNSPECIFIED TrafficDirection = "UNSPECIFIED"
	TrafficDirection_INBOUND     TrafficDirection = "INBOUND"
	TrafficDirection_OUTBOUND    TrafficDirection = "OUTBOUND"
)

var (
	TrafficDirection_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INBOUND",
		2: "OUTBOUND",
	}
	TrafficDirection_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INBOUND":     1,
		"OUTBOUND":    2,
	}
)

func (x TrafficDirection) ToInt() int32 {
	return TrafficDirection_value[strings.ToUpper(string(x))]
}

// LDS represents the Envoy LDS configuration.
type LDS struct {
	Name                             string                 `json:"name,omitempty"`
	Address                          *Address               `json:"address,omitempty"`
	AdditionalAddresses              []*AdditionalAddress   `json:"additional_addresses,omitempty"`
	StatPrefix                       string                 `json:"stat_prefix,omitempty"`
	FilterChains                     []*FilterChain         `json:"filter_chains,omitempty"`
	FcdsConfig                       *Listener_FcdsConfig   `json:"fcds_config,omitempty"`
	UseOriginalDst                   *bool                  `json:"use_original_dst,omitempty"`
	DefaultFilterChain               *FilterChain           `json:"default_filter_chain,omitempty"`
	PerConnectionBufferLimitBytes    *uint32                `json:"per_connection_buffer_limit_bytes,omitempty"`
	Metadata                         *Metadata              `json:"metadata,omitempty"`
	DeprecatedV1                     *Listener_DeprecatedV1 `json:"deprecated_v1,omitempty"`
	DrainType                        Listener_DrainType     `json:"drain_type,omitempty"`
	ListenerFilters                  []*ListenerFilter      `json:"listener_filters,omitempty"`
	ListenerFiltersTimeout           *string                `json:"listener_filters_timeout,omitempty"`
	ContinueOnListenerFiltersTimeout bool                   `json:"continue_on_listener_filters_timeout,omitempty"`
	Transparent                      *bool                  `json:"transparent,omitempty"`
	Freebind                         *bool                  `json:"freebind,omitempty"`
	SocketOptions                    []*SocketOption        `json:"socket_options,omitempty"`
	TcpFastOpenQueueLength           *uint32                `json:"tcp_fast_open_queue_length,omitempty"`
	TrafficDirection                 TrafficDirection       `json:"traffic_direction,omitempty"`
	UdpListenerConfig                *UdpListenerConfig     `json:"udp_listener_config,omitempty"`
	ApiListener                      *ApiListener           `json:"api_listener,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ConnectionBalanceConfig              *runtime.RawExtension `json:"connection_balance_config,omitempty"`
	ReusePort                            bool                  `json:"reuse_port,omitempty"`
	EnableReusePort                      *bool                 `json:"enable_reuse_port,omitempty"`
	AccessLog                            []*AccessLog          `json:"access_log,omitempty"`
	TcpBacklogSize                       *uint32               `json:"tcp_backlog_size,omitempty"`
	MaxConnectionsToAcceptPerSocketEvent *uint32               `json:"max_connections_to_accept_per_socket_event,omitempty"`
	BindToPort                           *bool                 `json:"bind_to_port,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	InternalListener *runtime.RawExtension `json:"internal_listener,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ExactBalance          *runtime.RawExtension `json:"exact_balance,omitempty"`
	ExtendBalance         *TypedExtensionConfig `json:"extend_balance,omitempty"`
	EnableMptcp           bool                  `json:"enable_mptcp,omitempty"`
	IgnoreGlobalConnLimit bool                  `json:"ignore_global_conn_limit,omitempty"`
	BypassOverloadManager bool                  `json:"bypass_overload_manager,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LDS) DeepCopyInto(out *LDS) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalAddresses != nil {
		in, out := &in.AdditionalAddresses, &out.AdditionalAddresses
		*out = make([]*AdditionalAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(AdditionalAddress)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.FilterChains != nil {
		in, out := &in.FilterChains, &out.FilterChains
		*out = make([]*FilterChain, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(FilterChain)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.FcdsConfig != nil {
		in, out := &in.FcdsConfig, &out.FcdsConfig
		*out = new(Listener_FcdsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UseOriginalDst != nil {
		in, out := &in.UseOriginalDst, &out.UseOriginalDst
		*out = new(bool)
		**out = **in
	}
	if in.DefaultFilterChain != nil {
		in, out := &in.DefaultFilterChain, &out.DefaultFilterChain
		*out = new(FilterChain)
		(*in).DeepCopyInto(*out)
	}
	if in.PerConnectionBufferLimitBytes != nil {
		in, out := &in.PerConnectionBufferLimitBytes, &out.PerConnectionBufferLimitBytes
		*out = new(uint32)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.DeprecatedV1 != nil {
		in, out := &in.DeprecatedV1, &out.DeprecatedV1
		*out = new(Listener_DeprecatedV1)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerFilters != nil {
		in, out := &in.ListenerFilters, &out.ListenerFilters
		*out = make([]*ListenerFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(ListenerFilter)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ListenerFiltersTimeout != nil {
		in, out := &in.ListenerFiltersTimeout, &out.ListenerFiltersTimeout
		*out = new(string)
		**out = **in
	}
	if in.Transparent != nil {
		in, out := &in.Transparent, &out.Transparent
		*out = new(bool)
		**out = **in
	}
	if in.Freebind != nil {
		in, out := &in.Freebind, &out.Freebind
		*out = new(bool)
		**out = **in
	}
	if in.SocketOptions != nil {
		in, out := &in.SocketOptions, &out.SocketOptions
		*out = make([]*SocketOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(SocketOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.TcpFastOpenQueueLength != nil {
		in, out := &in.TcpFastOpenQueueLength, &out.TcpFastOpenQueueLength
		*out = new(uint32)
		**out = **in
	}
	if in.UdpListenerConfig != nil {
		in, out := &in.UdpListenerConfig, &out.UdpListenerConfig
		*out = new(UdpListenerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ApiListener != nil {
		in, out := &in.ApiListener, &out.ApiListener
		*out = new(ApiListener)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionBalanceConfig != nil {
		in, out := &in.ConnectionBalanceConfig, &out.ConnectionBalanceConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.EnableReusePort != nil {
		in, out := &in.EnableReusePort, &out.EnableReusePort
		*out = new(bool)
		**out = **in
	}
	if in.AccessLog != nil {
		in, out := &in.AccessLog, &out.AccessLog
		*out = make([]*AccessLog, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(AccessLog)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.TcpBacklogSize != nil {
		in, out := &in.TcpBacklogSize, &out.TcpBacklogSize
		*out = new(uint32)
		**out = **in
	}
	if in.MaxConnectionsToAcceptPerSocketEvent != nil {
		in, out := &in.MaxConnectionsToAcceptPerSocketEvent, &out.MaxConnectionsToAcceptPerSocketEvent
		*out = new(uint32)
		**out = **in
	}
	if in.BindToPort != nil {
		in, out := &in.BindToPort, &out.BindToPort
		*out = new(bool)
		**out = **in
	}
	if in.InternalListener != nil {
		in, out := &in.InternalListener, &out.InternalListener
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.ExactBalance != nil {
		in, out := &in.ExactBalance, &out.ExactBalance
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.ExtendBalance != nil {
		in, out := &in.ExtendBalance, &out.ExtendBalance
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// AccessLog represents the Envoy AccessLog configuration.
type AccessLog struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
	Name        string                `json:"name,omitempty"`
	Filter      *AccessLogFilter      `json:"filter,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *AccessLog) DeepCopyInto(out *AccessLog) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(AccessLogFilter)
		(*in).DeepCopyInto(*out)
	}
}

// AccessLogFilter represents the Envoy AccessLogFilter configuration.
type AccessLogFilter struct {
	StatusCodeFilter *StatusCodeFilter `json:"status_code_filter,omitempty"`
	DurationFilter   *DurationFilter   `json:"duration_filter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	NotHealthCheckFilter *runtime.RawExtension `json:"not_health_check_filter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TraceableFilter *runtime.RawExtension `json:"traceable_filter,omitempty"`
	RuntimeFilter   *RuntimeFilter        `json:"runtime_filter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	AndFilter *runtime.RawExtension `json:"and_filter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	OrFilter           *runtime.RawExtension `json:"or_filter,omitempty"`
	HeaderFilter       *HeaderFilter         `json:"header_filter,omitempty"`
	ResponseFlagFilter *ResponseFlagFilter   `json:"response_flag_filter,omitempty"`
	GrpcStatusFilter   *GrpcStatusFilter     `json:"grpc_status_filter,omitempty"`
	ExtensionFilter    *ExtensionFilter      `json:"extension_filter,omitempty"`
	MetadataFilter     *MetadataFilter       `json:"metadata_filter,omitempty"`
	LogTypeFilter      *LogTypeFilter        `json:"log_type_filter,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *AccessLogFilter) DeepCopyInto(out *AccessLogFilter) {
	*out = *in
	if in.StatusCodeFilter != nil {
		in, out := &in.StatusCodeFilter, &out.StatusCodeFilter
		*out = new(StatusCodeFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.DurationFilter != nil {
		in, out := &in.DurationFilter, &out.DurationFilter
		*out = new(DurationFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.NotHealthCheckFilter != nil {
		in, out := &in.NotHealthCheckFilter, &out.NotHealthCheckFilter
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.TraceableFilter != nil {
		in, out := &in.TraceableFilter, &out.TraceableFilter
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.RuntimeFilter != nil {
		in, out := &in.RuntimeFilter, &out.RuntimeFilter
		*out = new(RuntimeFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.AndFilter != nil {
		in, out := &in.AndFilter, &out.AndFilter
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.OrFilter != nil {
		in, out := &in.OrFilter, &out.OrFilter
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.HeaderFilter != nil {
		in, out := &in.HeaderFilter, &out.HeaderFilter
		*out = new(HeaderFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.ResponseFlagFilter != nil {
		in, out := &in.ResponseFlagFilter, &out.ResponseFlagFilter
		*out = new(ResponseFlagFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.GrpcStatusFilter != nil {
		in, out := &in.GrpcStatusFilter, &out.GrpcStatusFilter
		*out = new(GrpcStatusFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtensionFilter != nil {
		in, out := &in.ExtensionFilter, &out.ExtensionFilter
		*out = new(ExtensionFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.MetadataFilter != nil {
		in, out := &in.MetadataFilter, &out.MetadataFilter
		*out = new(MetadataFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.LogTypeFilter != nil {
		in, out := &in.LogTypeFilter, &out.LogTypeFilter
		*out = new(LogTypeFilter)
		(*in).DeepCopyInto(*out)
	}
}

// AdditionalAddress represents the Envoy AdditionalAddress configuration.
type AdditionalAddress struct {
	Address       *Address               `json:"address,omitempty"`
	SocketOptions *SocketOptionsOverride `json:"socket_options,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *AdditionalAddress) DeepCopyInto(out *AdditionalAddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		(*in).DeepCopyInto(*out)
	}
	if in.SocketOptions != nil {
		in, out := &in.SocketOptions, &out.SocketOptions
		*out = new(SocketOptionsOverride)
		(*in).DeepCopyInto(*out)
	}
}

// Address represents the Envoy Address configuration.
type Address struct {
	SocketAddress        *SocketAddress        `json:"socket_address,omitempty"`
	Pipe                 *Pipe                 `json:"pipe,omitempty"`
	EnvoyInternalAddress *EnvoyInternalAddress `json:"envoy_internal_address,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
	if in.SocketAddress != nil {
		in, out := &in.SocketAddress, &out.SocketAddress
		*out = new(SocketAddress)
		(*in).DeepCopyInto(*out)
	}
	if in.Pipe != nil {
		in, out := &in.Pipe, &out.Pipe
		*out = new(Pipe)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyInternalAddress != nil {
		in, out := &in.EnvoyInternalAddress, &out.EnvoyInternalAddress
		*out = new(EnvoyInternalAddress)
		(*in).DeepCopyInto(*out)
	}
}

// AndFilter represents the Envoy AndFilter configuration.
type AndFilter struct {
	Filters []*AccessLogFilter `json:"filters,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *AndFilter) DeepCopyInto(out *AndFilter) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]*AccessLogFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(AccessLogFilter)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// ApiConfigSource represents the Envoy ApiConfigSource configuration.
type ApiConfigSource struct {
	ApiType                   ApiConfigSource_ApiType `json:"api_type,omitempty"`
	TransportApiVersion       ApiVersion              `json:"transport_api_version,omitempty"`
	ClusterNames              []string                `json:"cluster_names,omitempty"`
	GrpcServices              []*GrpcService          `json:"grpc_services,omitempty"`
	RefreshDelay              *string                 `json:"refresh_delay,omitempty"`
	RequestTimeout            *string                 `json:"request_timeout,omitempty"`
	RateLimitSettings         *RateLimitSettings      `json:"rate_limit_settings,omitempty"`
	SetNodeOnFirstMessageOnly bool                    `json:"set_node_on_first_message_only,omitempty"`
	ConfigValidators          []*TypedExtensionConfig `json:"config_validators,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ApiConfigSource) DeepCopyInto(out *ApiConfigSource) {
	*out = *in
	if in.ClusterNames != nil {
		in, out := &in.ClusterNames, &out.ClusterNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GrpcServices != nil {
		in, out := &in.GrpcServices, &out.GrpcServices
		*out = make([]*GrpcService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(GrpcService)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RefreshDelay != nil {
		in, out := &in.RefreshDelay, &out.RefreshDelay
		*out = new(string)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(string)
		**out = **in
	}
	if in.RateLimitSettings != nil {
		in, out := &in.RateLimitSettings, &out.RateLimitSettings
		*out = new(RateLimitSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigValidators != nil {
		in, out := &in.ConfigValidators, &out.ConfigValidators
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// ApiListener represents the Envoy ApiListener configuration.
type ApiListener struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	ApiListener *runtime.RawExtension `json:"api_listener,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ApiListener) DeepCopyInto(out *ApiListener) {
	*out = *in
	if in.ApiListener != nil {
		in, out := &in.ApiListener, &out.ApiListener
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// BackoffStrategy represents the Envoy BackoffStrategy configuration.
type BackoffStrategy struct {
	BaseInterval *string `json:"base_interval,omitempty"`
	MaxInterval  *string `json:"max_interval,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *BackoffStrategy) DeepCopyInto(out *BackoffStrategy) {
	*out = *in
	if in.BaseInterval != nil {
		in, out := &in.BaseInterval, &out.BaseInterval
		*out = new(string)
		**out = **in
	}
	if in.MaxInterval != nil {
		in, out := &in.MaxInterval, &out.MaxInterval
		*out = new(string)
		**out = **in
	}
}

// CidrRange represents the Envoy CidrRange configuration.
type CidrRange struct {
	AddressPrefix string  `json:"address_prefix,omitempty"`
	PrefixLen     *uint32 `json:"prefix_len,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *CidrRange) DeepCopyInto(out *CidrRange) {
	*out = *in
	if in.PrefixLen != nil {
		in, out := &in.PrefixLen, &out.PrefixLen
		*out = new(uint32)
		**out = **in
	}
}

// ComparisonFilter represents the Envoy ComparisonFilter configuration.
type ComparisonFilter struct {
	Op    ComparisonFilter_Op `json:"op,omitempty"`
	Value *RuntimeUInt32      `json:"value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ComparisonFilter) DeepCopyInto(out *ComparisonFilter) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(RuntimeUInt32)
		(*in).DeepCopyInto(*out)
	}
}

// ConfigSource represents the Envoy ConfigSource configuration.
type ConfigSource struct {
	Path             string            `json:"path,omitempty"`
	PathConfigSource *PathConfigSource `json:"path_config_source,omitempty"`
	ApiConfigSource  *ApiConfigSource  `json:"api_config_source,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Ads                 *runtime.RawExtension `json:"ads,omitempty"`
	Self                *SelfConfigSource     `json:"self,omitempty"`
	InitialFetchTimeout *string               `json:"initial_fetch_timeout,omitempty"`
	ResourceApiVersion  ApiVersion            `json:"resource_api_version,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.PathConfigSource != nil {
		in, out := &in.PathConfigSource, &out.PathConfigSource
		*out = new(PathConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ApiConfigSource != nil {
		in, out := &in.ApiConfigSource, &out.ApiConfigSource
		*out = new(ApiConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Ads != nil {
		in, out := &in.Ads, &out.Ads
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Self != nil {
		in, out := &in.Self, &out.Self
		*out = new(SelfConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialFetchTimeout != nil {
		in, out := &in.InitialFetchTimeout, &out.InitialFetchTimeout
		*out = new(string)
		**out = **in
	}
}

// DataSource represents the Envoy DataSource configuration.
type DataSource struct {
	Filename            string            `json:"filename,omitempty"`
	InlineBytes         []byte            `json:"inline_bytes,omitempty"`
	InlineString        string            `json:"inline_string,omitempty"`
	EnvironmentVariable string            `json:"environment_variable,omitempty"`
	WatchedDirectory    *WatchedDirectory `json:"watched_directory,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	if in.InlineBytes != nil {
		in, out := &in.InlineBytes, &out.InlineBytes
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.WatchedDirectory != nil {
		in, out := &in.WatchedDirectory, &out.WatchedDirectory
		*out = new(WatchedDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// DurationFilter represents the Envoy DurationFilter configuration.
type DurationFilter struct {
	Comparison *ComparisonFilter `json:"comparison,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DurationFilter) DeepCopyInto(out *DurationFilter) {
	*out = *in
	if in.Comparison != nil {
		in, out := &in.Comparison, &out.Comparison
		*out = new(ComparisonFilter)
		(*in).DeepCopyInto(*out)
	}
}

// EnvoyInternalAddress represents the Envoy EnvoyInternalAddress configuration.
type EnvoyInternalAddress struct {
	ServerListenerName string `json:"server_listener_name,omitempty"`
	EndpointId         string `json:"endpoint_id,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *EnvoyInternalAddress) DeepCopyInto(out *EnvoyInternalAddress) {
	*out = *in
}

// ExtensionConfigSource represents the Envoy ExtensionConfigSource configuration.
type ExtensionConfigSource struct {
	ConfigSource *ConfigSource `json:"config_source,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	DefaultConfig                    *runtime.RawExtension `json:"default_config,omitempty"`
	ApplyDefaultConfigWithoutWarming bool                  `json:"apply_default_config_without_warming,omitempty"`
	TypeUrls                         []string              `json:"type_urls,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ExtensionConfigSource) DeepCopyInto(out *ExtensionConfigSource) {
	*out = *in
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultConfig != nil {
		in, out := &in.DefaultConfig, &out.DefaultConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.TypeUrls != nil {
		in, out := &in.TypeUrls, &out.TypeUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// ExtensionFilter represents the Envoy ExtensionFilter configuration.
type ExtensionFilter struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
	Name        string                `json:"name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ExtensionFilter) DeepCopyInto(out *ExtensionFilter) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// Filter represents the Envoy Filter configuration.
type Filter struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig     *runtime.RawExtension  `json:"typed_config,omitempty"`
	Name            string                 `json:"name,omitempty"`
	ConfigDiscovery *ExtensionConfigSource `json:"config_discovery,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.ConfigDiscovery != nil {
		in, out := &in.ConfigDiscovery, &out.ConfigDiscovery
		*out = new(ExtensionConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// FilterChain represents the Envoy FilterChain configuration.
type FilterChain struct {
	FilterChainMatch              *FilterChainMatch `json:"filter_chain_match,omitempty"`
	Filters                       []*Filter         `json:"filters,omitempty"`
	UseProxyProto                 *bool             `json:"use_proxy_proto,omitempty"`
	Metadata                      *Metadata         `json:"metadata,omitempty"`
	TransportSocket               *TransportSocket  `json:"transport_socket,omitempty"`
	TransportSocketConnectTimeout *string           `json:"transport_socket_connect_timeout,omitempty"`
	Name                          string            `json:"name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FilterChain) DeepCopyInto(out *FilterChain) {
	*out = *in
	if in.FilterChainMatch != nil {
		in, out := &in.FilterChainMatch, &out.FilterChainMatch
		*out = new(FilterChainMatch)
		(*in).DeepCopyInto(*out)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]*Filter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(Filter)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.UseProxyProto != nil {
		in, out := &in.UseProxyProto, &out.UseProxyProto
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.TransportSocket != nil {
		in, out := &in.TransportSocket, &out.TransportSocket
		*out = new(TransportSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.TransportSocketConnectTimeout != nil {
		in, out := &in.TransportSocketConnectTimeout, &out.TransportSocketConnectTimeout
		*out = new(string)
		**out = **in
	}
}

// FilterChainMatch represents the Envoy FilterChainMatch configuration.
type FilterChainMatch struct {
	DestinationPort          *uint32                               `json:"destination_port,omitempty"`
	PrefixRanges             []*CidrRange                          `json:"prefix_ranges,omitempty"`
	AddressSuffix            string                                `json:"address_suffix,omitempty"`
	SuffixLen                *uint32                               `json:"suffix_len,omitempty"`
	DirectSourcePrefixRanges []*CidrRange                          `json:"direct_source_prefix_ranges,omitempty"`
	SourceType               FilterChainMatch_ConnectionSourceType `json:"source_type,omitempty"`
	SourcePrefixRanges       []*CidrRange                          `json:"source_prefix_ranges,omitempty"`
	SourcePorts              []uint32                              `json:"source_ports,omitempty"`
	ServerNames              []string                              `json:"server_names,omitempty"`
	TransportProtocol        string                                `json:"transport_protocol,omitempty"`
	ApplicationProtocols     []string                              `json:"application_protocols,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FilterChainMatch) DeepCopyInto(out *FilterChainMatch) {
	*out = *in
	if in.DestinationPort != nil {
		in, out := &in.DestinationPort, &out.DestinationPort
		*out = new(uint32)
		**out = **in
	}
	if in.PrefixRanges != nil {
		in, out := &in.PrefixRanges, &out.PrefixRanges
		*out = make([]*CidrRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(CidrRange)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.SuffixLen != nil {
		in, out := &in.SuffixLen, &out.SuffixLen
		*out = new(uint32)
		**out = **in
	}
	if in.DirectSourcePrefixRanges != nil {
		in, out := &in.DirectSourcePrefixRanges, &out.DirectSourcePrefixRanges
		*out = make([]*CidrRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(CidrRange)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.SourcePrefixRanges != nil {
		in, out := &in.SourcePrefixRanges, &out.SourcePrefixRanges
		*out = make([]*CidrRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(CidrRange)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.SourcePorts != nil {
		in, out := &in.SourcePorts, &out.SourcePorts
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	if in.ServerNames != nil {
		in, out := &in.ServerNames, &out.ServerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationProtocols != nil {
		in, out := &in.ApplicationProtocols, &out.ApplicationProtocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// FractionalPercent represents the Envoy FractionalPercent configuration.
type FractionalPercent struct {
	Numerator   uint32                            `json:"numerator,omitempty"`
	Denominator FractionalPercent_DenominatorType `json:"denominator,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FractionalPercent) DeepCopyInto(out *FractionalPercent) {
	*out = *in
}

// GrpcService represents the Envoy GrpcService configuration.
type GrpcService struct {
	Timeout         *string        `json:"timeout,omitempty"`
	InitialMetadata []*HeaderValue `json:"initial_metadata,omitempty"`
	RetryPolicy     *RetryPolicy   `json:"retry_policy,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService) DeepCopyInto(out *GrpcService) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.InitialMetadata != nil {
		in, out := &in.InitialMetadata, &out.InitialMetadata
		*out = make([]*HeaderValue, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValue)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// GrpcStatusFilter represents the Envoy GrpcStatusFilter configuration.
type GrpcStatusFilter struct {
	Statuses []GrpcStatusFilter_Status `json:"statuses,omitempty"`
	Exclude  bool                      `json:"exclude,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcStatusFilter) DeepCopyInto(out *GrpcStatusFilter) {
	*out = *in
	if in.Statuses != nil {
		in, out := &in.Statuses, &out.Statuses
		*out = make([]GrpcStatusFilter_Status, len(*in))
		copy(*out, *in)
	}
}

// HeaderFilter represents the Envoy HeaderFilter configuration.
type HeaderFilter struct {
	Header *HeaderMatcher `json:"header,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderFilter) DeepCopyInto(out *HeaderFilter) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(HeaderMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// HeaderMatcher represents the Envoy HeaderMatcher configuration.
type HeaderMatcher struct {
	Name                      string `json:"name,omitempty"`
	InvertMatch               bool   `json:"invert_match,omitempty"`
	TreatMissingHeaderAsEmpty bool   `json:"treat_missing_header_as_empty,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderMatcher) DeepCopyInto(out *HeaderMatcher) {
	*out = *in
}

// HeaderValue represents the Envoy HeaderValue configuration.
type HeaderValue struct {
	Key      string `json:"key,omitempty"`
	Value    string `json:"value,omitempty"`
	RawValue []byte `json:"raw_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderValue) DeepCopyInto(out *HeaderValue) {
	*out = *in
	if in.RawValue != nil {
		in, out := &in.RawValue, &out.RawValue
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// Int32Range represents the Envoy Int32Range configuration.
type Int32Range struct {
	Start int32 `json:"start,omitempty"`
	End   int32 `json:"end,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Int32Range) DeepCopyInto(out *Int32Range) {
	*out = *in
}

// ListenerFilter represents the Envoy ListenerFilter configuration.
type ListenerFilter struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig     *runtime.RawExtension              `json:"typed_config,omitempty"`
	Name            string                             `json:"name,omitempty"`
	ConfigDiscovery *ExtensionConfigSource             `json:"config_discovery,omitempty"`
	FilterDisabled  *ListenerFilterChainMatchPredicate `json:"filter_disabled,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ListenerFilter) DeepCopyInto(out *ListenerFilter) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.ConfigDiscovery != nil {
		in, out := &in.ConfigDiscovery, &out.ConfigDiscovery
		*out = new(ExtensionConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.FilterDisabled != nil {
		in, out := &in.FilterDisabled, &out.FilterDisabled
		*out = new(ListenerFilterChainMatchPredicate)
		(*in).DeepCopyInto(*out)
	}
}

// ListenerFilterChainMatchPredicate represents the Envoy ListenerFilterChainMatchPredicate configuration.
type ListenerFilterChainMatchPredicate struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	OrMatch *runtime.RawExtension `json:"or_match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	AndMatch *runtime.RawExtension `json:"and_match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	NotMatch             *runtime.RawExtension `json:"not_match,omitempty"`
	AnyMatch             bool                  `json:"any_match,omitempty"`
	DestinationPortRange *Int32Range           `json:"destination_port_range,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ListenerFilterChainMatchPredicate) DeepCopyInto(out *ListenerFilterChainMatchPredicate) {
	*out = *in
	if in.OrMatch != nil {
		in, out := &in.OrMatch, &out.OrMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.AndMatch != nil {
		in, out := &in.AndMatch, &out.AndMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.NotMatch != nil {
		in, out := &in.NotMatch, &out.NotMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.DestinationPortRange != nil {
		in, out := &in.DestinationPortRange, &out.DestinationPortRange
		*out = new(Int32Range)
		(*in).DeepCopyInto(*out)
	}
}

// ListenerFilterChainMatchPredicate_MatchSet represents the Envoy ListenerFilterChainMatchPredicate_MatchSet configuration.
type ListenerFilterChainMatchPredicate_MatchSet struct {
	Rules []*ListenerFilterChainMatchPredicate `json:"rules,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ListenerFilterChainMatchPredicate_MatchSet) DeepCopyInto(out *ListenerFilterChainMatchPredicate_MatchSet) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]*ListenerFilterChainMatchPredicate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(ListenerFilterChainMatchPredicate)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// Listener_DeprecatedV1 represents the Envoy Listener_DeprecatedV1 configuration.
type Listener_DeprecatedV1 struct {
	BindToPort *bool `json:"bind_to_port,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Listener_DeprecatedV1) DeepCopyInto(out *Listener_DeprecatedV1) {
	*out = *in
	if in.BindToPort != nil {
		in, out := &in.BindToPort, &out.BindToPort
		*out = new(bool)
		**out = **in
	}
}

// Listener_FcdsConfig represents the Envoy Listener_FcdsConfig configuration.
type Listener_FcdsConfig struct {
	Name         string        `json:"name,omitempty"`
	ConfigSource *ConfigSource `json:"config_source,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Listener_FcdsConfig) DeepCopyInto(out *Listener_FcdsConfig) {
	*out = *in
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// LogTypeFilter represents the Envoy LogTypeFilter configuration.
type LogTypeFilter struct {
	Types   []AccessLogType `json:"types,omitempty"`
	Exclude bool            `json:"exclude,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LogTypeFilter) DeepCopyInto(out *LogTypeFilter) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]AccessLogType, len(*in))
		copy(*out, *in)
	}
}

// Metadata represents the Envoy Metadata configuration.
type Metadata struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	FilterMetadata map[string]*runtime.RawExtension `json:"filter_metadata,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedFilterMetadata map[string]*runtime.RawExtension `json:"typed_filter_metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
	if in.FilterMetadata != nil {
		in, out := &in.FilterMetadata, &out.FilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TypedFilterMetadata != nil {
		in, out := &in.TypedFilterMetadata, &out.TypedFilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// MetadataFilter represents the Envoy MetadataFilter configuration.
type MetadataFilter struct {
	Matcher            *MetadataMatcher `json:"matcher,omitempty"`
	MatchIfKeyNotFound *bool            `json:"match_if_key_not_found,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *MetadataFilter) DeepCopyInto(out *MetadataFilter) {
	*out = *in
	if in.Matcher != nil {
		in, out := &in.Matcher, &out.Matcher
		*out = new(MetadataMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchIfKeyNotFound != nil {
		in, out := &in.MatchIfKeyNotFound, &out.MatchIfKeyNotFound
		*out = new(bool)
		**out = **in
	}
}

// MetadataMatcher represents the Envoy MetadataMatcher configuration.
type MetadataMatcher struct {
	Filter string `json:"filter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Path []*runtime.RawExtension `json:"path,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Value  *runtime.RawExtension `json:"value,omitempty"`
	Invert bool                  `json:"invert,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *MetadataMatcher) DeepCopyInto(out *MetadataMatcher) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(runtime.RawExtension)
				*(*out)[i] = *(*in)[i]
			}
		}
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// OrFilter represents the Envoy OrFilter configuration.
type OrFilter struct {
	Filters []*AccessLogFilter `json:"filters,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *OrFilter) DeepCopyInto(out *OrFilter) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]*AccessLogFilter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(AccessLogFilter)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// PathConfigSource represents the Envoy PathConfigSource configuration.
type PathConfigSource struct {
	Path             string            `json:"path,omitempty"`
	WatchedDirectory *WatchedDirectory `json:"watched_directory,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *PathConfigSource) DeepCopyInto(out *PathConfigSource) {
	*out = *in
	if in.WatchedDirectory != nil {
		in, out := &in.WatchedDirectory, &out.WatchedDirectory
		*out = new(WatchedDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// Pipe represents the Envoy Pipe configuration.
type Pipe struct {
	Path string `json:"path,omitempty"`
	Mode uint32 `json:"mode,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Pipe) DeepCopyInto(out *Pipe) {
	*out = *in
}

// QuicProtocolOptions represents the Envoy QuicProtocolOptions configuration.
type QuicProtocolOptions struct {
	IdleTimeout                         *string               `json:"idle_timeout,omitempty"`
	CryptoHandshakeTimeout              *string               `json:"crypto_handshake_timeout,omitempty"`
	Enabled                             *RuntimeFeatureFlag   `json:"enabled,omitempty"`
	PacketsToReadToConnectionCountRatio *uint32               `json:"packets_to_read_to_connection_count_ratio,omitempty"`
	CryptoStreamConfig                  *TypedExtensionConfig `json:"crypto_stream_config,omitempty"`
	ProofSourceConfig                   *TypedExtensionConfig `json:"proof_source_config,omitempty"`
	ConnectionIdGeneratorConfig         *TypedExtensionConfig `json:"connection_id_generator_config,omitempty"`
	ServerPreferredAddressConfig        *TypedExtensionConfig `json:"server_preferred_address_config,omitempty"`
	SendDisableActiveMigration          *bool                 `json:"send_disable_active_migration,omitempty"`
	ConnectionDebugVisitorConfig        *TypedExtensionConfig `json:"connection_debug_visitor_config,omitempty"`
	SaveCmsgConfig                      []*SocketCmsgHeaders  `json:"save_cmsg_config,omitempty"`
	RejectNewConnections                bool                  `json:"reject_new_connections,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *QuicProtocolOptions) DeepCopyInto(out *QuicProtocolOptions) {
	*out = *in
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.CryptoHandshakeTimeout != nil {
		in, out := &in.CryptoHandshakeTimeout, &out.CryptoHandshakeTimeout
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(RuntimeFeatureFlag)
		(*in).DeepCopyInto(*out)
	}
	if in.PacketsToReadToConnectionCountRatio != nil {
		in, out := &in.PacketsToReadToConnectionCountRatio, &out.PacketsToReadToConnectionCountRatio
		*out = new(uint32)
		**out = **in
	}
	if in.CryptoStreamConfig != nil {
		in, out := &in.CryptoStreamConfig, &out.CryptoStreamConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProofSourceConfig != nil {
		in, out := &in.ProofSourceConfig, &out.ProofSourceConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionIdGeneratorConfig != nil {
		in, out := &in.ConnectionIdGeneratorConfig, &out.ConnectionIdGeneratorConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerPreferredAddressConfig != nil {
		in, out := &in.ServerPreferredAddressConfig, &out.ServerPreferredAddressConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SendDisableActiveMigration != nil {
		in, out := &in.SendDisableActiveMigration, &out.SendDisableActiveMigration
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionDebugVisitorConfig != nil {
		in, out := &in.ConnectionDebugVisitorConfig, &out.ConnectionDebugVisitorConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SaveCmsgConfig != nil {
		in, out := &in.SaveCmsgConfig, &out.SaveCmsgConfig
		*out = make([]*SocketCmsgHeaders, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(SocketCmsgHeaders)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RateLimitSettings represents the Envoy RateLimitSettings configuration.
type RateLimitSettings struct {
	MaxTokens *uint32  `json:"max_tokens,omitempty"`
	FillRate  *float64 `json:"fill_rate,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimitSettings) DeepCopyInto(out *RateLimitSettings) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(uint32)
		**out = **in
	}
	if in.FillRate != nil {
		in, out := &in.FillRate, &out.FillRate
		*out = new(float64)
		**out = **in
	}
}

// ResponseFlagFilter represents the Envoy ResponseFlagFilter configuration.
type ResponseFlagFilter struct {
	Flags []string `json:"flags,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ResponseFlagFilter) DeepCopyInto(out *ResponseFlagFilter) {
	*out = *in
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// RetryPolicy represents the Envoy RetryPolicy configuration.
type RetryPolicy struct {
	RetryBackOff                  *BackoffStrategy                  `json:"retry_back_off,omitempty"`
	NumRetries                    *uint32                           `json:"num_retries,omitempty"`
	RetryOn                       string                            `json:"retry_on,omitempty"`
	RetryPriority                 *RetryPolicy_RetryPriority        `json:"retry_priority,omitempty"`
	RetryHostPredicate            []*RetryPolicy_RetryHostPredicate `json:"retry_host_predicate,omitempty"`
	HostSelectionRetryMaxAttempts int64                             `json:"host_selection_retry_max_attempts,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.RetryBackOff != nil {
		in, out := &in.RetryBackOff, &out.RetryBackOff
		*out = new(BackoffStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.NumRetries != nil {
		in, out := &in.NumRetries, &out.NumRetries
		*out = new(uint32)
		**out = **in
	}
	if in.RetryPriority != nil {
		in, out := &in.RetryPriority, &out.RetryPriority
		*out = new(RetryPolicy_RetryPriority)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryHostPredicate != nil {
		in, out := &in.RetryHostPredicate, &out.RetryHostPredicate
		*out = make([]*RetryPolicy_RetryHostPredicate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RetryPolicy_RetryHostPredicate)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RetryPolicy_RetryHostPredicate represents the Envoy RetryPolicy_RetryHostPredicate configuration.
type RetryPolicy_RetryHostPredicate struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryHostPredicate) DeepCopyInto(out *RetryPolicy_RetryHostPredicate) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RetryPolicy_RetryPriority represents the Envoy RetryPolicy_RetryPriority configuration.
type RetryPolicy_RetryPriority struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryPriority) DeepCopyInto(out *RetryPolicy_RetryPriority) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RuntimeFeatureFlag represents the Envoy RuntimeFeatureFlag configuration.
type RuntimeFeatureFlag struct {
	DefaultValue *bool  `json:"default_value,omitempty"`
	RuntimeKey   string `json:"runtime_key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RuntimeFeatureFlag) DeepCopyInto(out *RuntimeFeatureFlag) {
	*out = *in
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(bool)
		**out = **in
	}
}

// RuntimeFilter represents the Envoy RuntimeFilter configuration.
type RuntimeFilter struct {
	RuntimeKey               string             `json:"runtime_key,omitempty"`
	PercentSampled           *FractionalPercent `json:"percent_sampled,omitempty"`
	UseIndependentRandomness bool               `json:"use_independent_randomness,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RuntimeFilter) DeepCopyInto(out *RuntimeFilter) {
	*out = *in
	if in.PercentSampled != nil {
		in, out := &in.PercentSampled, &out.PercentSampled
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
}

// RuntimeUInt32 represents the Envoy RuntimeUInt32 configuration.
type RuntimeUInt32 struct {
	DefaultValue uint32 `json:"default_value,omitempty"`
	RuntimeKey   string `json:"runtime_key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RuntimeUInt32) DeepCopyInto(out *RuntimeUInt32) {
	*out = *in
}

// SelfConfigSource represents the Envoy SelfConfigSource configuration.
type SelfConfigSource struct {
	TransportApiVersion ApiVersion `json:"transport_api_version,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SelfConfigSource) DeepCopyInto(out *SelfConfigSource) {
	*out = *in
}

// SocketAddress represents the Envoy SocketAddress configuration.
type SocketAddress struct {
	Protocol                 SocketAddress_Protocol `json:"protocol,omitempty"`
	Address                  string                 `json:"address,omitempty"`
	PortValue                uint32                 `json:"port_value,omitempty"`
	NamedPort                string                 `json:"named_port,omitempty"`
	ResolverName             string                 `json:"resolver_name,omitempty"`
	Ipv4Compat               bool                   `json:"ipv4_compat,omitempty"`
	NetworkNamespaceFilepath string                 `json:"network_namespace_filepath,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketAddress) DeepCopyInto(out *SocketAddress) {
	*out = *in
}

// SocketCmsgHeaders represents the Envoy SocketCmsgHeaders configuration.
type SocketCmsgHeaders struct {
	Level        *uint32 `json:"level,omitempty"`
	Type         *uint32 `json:"type,omitempty"`
	ExpectedSize uint32  `json:"expected_size,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketCmsgHeaders) DeepCopyInto(out *SocketCmsgHeaders) {
	*out = *in
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(uint32)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(uint32)
		**out = **in
	}
}

// SocketOption represents the Envoy SocketOption configuration.
type SocketOption struct {
	Description string                   `json:"description,omitempty"`
	Level       int64                    `json:"level,omitempty"`
	Name        int64                    `json:"name,omitempty"`
	IntValue    int64                    `json:"int_value,omitempty"`
	BufValue    []byte                   `json:"buf_value,omitempty"`
	State       SocketOption_SocketState `json:"state,omitempty"`
	Type        *SocketOption_SocketType `json:"type,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketOption) DeepCopyInto(out *SocketOption) {
	*out = *in
	if in.BufValue != nil {
		in, out := &in.BufValue, &out.BufValue
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(SocketOption_SocketType)
		(*in).DeepCopyInto(*out)
	}
}

// SocketOption_SocketType represents the Envoy SocketOption_SocketType configuration.
type SocketOption_SocketType struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	Stream *runtime.RawExtension `json:"stream,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Datagram *runtime.RawExtension `json:"datagram,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketOption_SocketType) DeepCopyInto(out *SocketOption_SocketType) {
	*out = *in
	if in.Stream != nil {
		in, out := &in.Stream, &out.Stream
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Datagram != nil {
		in, out := &in.Datagram, &out.Datagram
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// SocketOptionsOverride represents the Envoy SocketOptionsOverride configuration.
type SocketOptionsOverride struct {
	SocketOptions []*SocketOption `json:"socket_options,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketOptionsOverride) DeepCopyInto(out *SocketOptionsOverride) {
	*out = *in
	if in.SocketOptions != nil {
		in, out := &in.SocketOptions, &out.SocketOptions
		*out = make([]*SocketOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(SocketOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// StatusCodeFilter represents the Envoy StatusCodeFilter configuration.
type StatusCodeFilter struct {
	Comparison *ComparisonFilter `json:"comparison,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *StatusCodeFilter) DeepCopyInto(out *StatusCodeFilter) {
	*out = *in
	if in.Comparison != nil {
		in, out := &in.Comparison, &out.Comparison
		*out = new(ComparisonFilter)
		(*in).DeepCopyInto(*out)
	}
}

// TransportSocket represents the Envoy TransportSocket configuration.
type TransportSocket struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
	Name        string                `json:"name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TransportSocket) DeepCopyInto(out *TransportSocket) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// TypedExtensionConfig represents the Envoy TypedExtensionConfig configuration.
type TypedExtensionConfig struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TypedExtensionConfig) DeepCopyInto(out *TypedExtensionConfig) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// UdpListenerConfig represents the Envoy UdpListenerConfig configuration.
type UdpListenerConfig struct {
	DownstreamSocketConfig      *UdpSocketConfig      `json:"downstream_socket_config,omitempty"`
	QuicOptions                 *QuicProtocolOptions  `json:"quic_options,omitempty"`
	UdpPacketPacketWriterConfig *TypedExtensionConfig `json:"udp_packet_packet_writer_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *UdpListenerConfig) DeepCopyInto(out *UdpListenerConfig) {
	*out = *in
	if in.DownstreamSocketConfig != nil {
		in, out := &in.DownstreamSocketConfig, &out.DownstreamSocketConfig
		*out = new(UdpSocketConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.QuicOptions != nil {
		in, out := &in.QuicOptions, &out.QuicOptions
		*out = new(QuicProtocolOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.UdpPacketPacketWriterConfig != nil {
		in, out := &in.UdpPacketPacketWriterConfig, &out.UdpPacketPacketWriterConfig
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// UdpSocketConfig represents the Envoy UdpSocketConfig configuration.
type UdpSocketConfig struct {
	MaxRxDatagramSize *uint64 `json:"max_rx_datagram_size,omitempty"`
	PreferGro         *bool   `json:"prefer_gro,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *UdpSocketConfig) DeepCopyInto(out *UdpSocketConfig) {
	*out = *in
	if in.MaxRxDatagramSize != nil {
		in, out := &in.MaxRxDatagramSize, &out.MaxRxDatagramSize
		*out = new(uint64)
		**out = **in
	}
	if in.PreferGro != nil {
		in, out := &in.PreferGro, &out.PreferGro
		*out = new(bool)
		**out = **in
	}
}

// WatchedDirectory represents the Envoy WatchedDirectory configuration.
type WatchedDirectory struct {
	Path string `json:"path,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *WatchedDirectory) DeepCopyInto(out *WatchedDirectory) {
	*out = *in
}
