// Code generated by tools/typegen/rds. DO NOT EDIT.
// Source: github.com/envoyproxy/go-control-plane/envoy/config/route/v3
// Envoy version: v1.36.0
// To regenerate: make generate-rds

package rds

import (
	"strings"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

var _ = strings.ToUpper // suppress unused import

// ApiVersion is an enum type.
type ApiVersion string

var (
	ApiVersion_name  = map[int32]string{}
	ApiVersion_value = map[string]int32{}
)

func (x ApiVersion) ToInt() int32 {
	return ApiVersion_value[strings.ToUpper(string(x))]
}

// FractionalPercent_DenominatorType is an enum type.
type FractionalPercent_DenominatorType string

const (
	FractionalPercent_DenominatorType_HUNDRED      FractionalPercent_DenominatorType = "HUNDRED"
	FractionalPercent_DenominatorType_TEN_THOUSAND FractionalPercent_DenominatorType = "TEN_THOUSAND"
	FractionalPercent_DenominatorType_MILLION      FractionalPercent_DenominatorType = "MILLION"
)

var (
	FractionalPercent_DenominatorType_name = map[int32]string{
		0: "HUNDRED",
		1: "TEN_THOUSAND",
		2: "MILLION",
	}
	FractionalPercent_DenominatorType_value = map[string]int32{
		"HUNDRED":      0,
		"TEN_THOUSAND": 1,
		"MILLION":      2,
	}
)

func (x FractionalPercent_DenominatorType) ToInt() int32 {
	return FractionalPercent_DenominatorType_value[strings.ToUpper(string(x))]
}

// HeaderValueOption_HeaderAppendAction is an enum type.
type HeaderValueOption_HeaderAppendAction string

const (
	HeaderValueOption_HeaderAppendAction_APPEND_IF_EXISTS_OR_ADD    HeaderValueOption_HeaderAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_ADD_IF_ABSENT              HeaderValueOption_HeaderAppendAction = "ADD_IF_ABSENT"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS_OR_ADD HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS        HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	HeaderValueOption_HeaderAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	HeaderValueOption_HeaderAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x HeaderValueOption_HeaderAppendAction) ToInt() int32 {
	return HeaderValueOption_HeaderAppendAction_value[strings.ToUpper(string(x))]
}

// KeyValueAppend_KeyValueAppendAction is an enum type.
type KeyValueAppend_KeyValueAppendAction string

const (
	KeyValueAppend_KeyValueAppendAction_APPEND_IF_EXISTS_OR_ADD    KeyValueAppend_KeyValueAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_ADD_IF_ABSENT              KeyValueAppend_KeyValueAppendAction = "ADD_IF_ABSENT"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS_OR_ADD KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS        KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	KeyValueAppend_KeyValueAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	KeyValueAppend_KeyValueAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x KeyValueAppend_KeyValueAppendAction) ToInt() int32 {
	return KeyValueAppend_KeyValueAppendAction_value[strings.ToUpper(string(x))]
}

// ProxyProtocolConfig_Version is an enum type.
type ProxyProtocolConfig_Version string

var (
	ProxyProtocolConfig_Version_name  = map[int32]string{}
	ProxyProtocolConfig_Version_value = map[string]int32{}
)

func (x ProxyProtocolConfig_Version) ToInt() int32 {
	return ProxyProtocolConfig_Version_value[strings.ToUpper(string(x))]
}

// ProxyProtocolPassThroughTLVs_PassTLVsMatchType is an enum type.
type ProxyProtocolPassThroughTLVs_PassTLVsMatchType string

var (
	ProxyProtocolPassThroughTLVs_PassTLVsMatchType_name  = map[int32]string{}
	ProxyProtocolPassThroughTLVs_PassTLVsMatchType_value = map[string]int32{}
)

func (x ProxyProtocolPassThroughTLVs_PassTLVsMatchType) ToInt() int32 {
	return ProxyProtocolPassThroughTLVs_PassTLVsMatchType_value[strings.ToUpper(string(x))]
}

// RateLimit_Action_MetaData_Source is an enum type.
type RateLimit_Action_MetaData_Source string

const (
	RateLimit_Action_MetaData_Source_DYNAMIC     RateLimit_Action_MetaData_Source = "DYNAMIC"
	RateLimit_Action_MetaData_Source_ROUTE_ENTRY RateLimit_Action_MetaData_Source = "ROUTE_ENTRY"
)

var (
	RateLimit_Action_MetaData_Source_name = map[int32]string{
		0: "DYNAMIC",
		1: "ROUTE_ENTRY",
	}
	RateLimit_Action_MetaData_Source_value = map[string]int32{
		"DYNAMIC":     0,
		"ROUTE_ENTRY": 1,
	}
)

func (x RateLimit_Action_MetaData_Source) ToInt() int32 {
	return RateLimit_Action_MetaData_Source_value[strings.ToUpper(string(x))]
}

// RedirectAction_RedirectResponseCode is an enum type.
type RedirectAction_RedirectResponseCode string

const (
	RedirectAction_RedirectResponseCode_MOVED_PERMANENTLY  RedirectAction_RedirectResponseCode = "MOVED_PERMANENTLY"
	RedirectAction_RedirectResponseCode_FOUND              RedirectAction_RedirectResponseCode = "FOUND"
	RedirectAction_RedirectResponseCode_SEE_OTHER          RedirectAction_RedirectResponseCode = "SEE_OTHER"
	RedirectAction_RedirectResponseCode_TEMPORARY_REDIRECT RedirectAction_RedirectResponseCode = "TEMPORARY_REDIRECT"
	RedirectAction_RedirectResponseCode_PERMANENT_REDIRECT RedirectAction_RedirectResponseCode = "PERMANENT_REDIRECT"
)

var (
	RedirectAction_RedirectResponseCode_name = map[int32]string{
		0: "MOVED_PERMANENTLY",
		1: "FOUND",
		2: "SEE_OTHER",
		3: "TEMPORARY_REDIRECT",
		4: "PERMANENT_REDIRECT",
	}
	RedirectAction_RedirectResponseCode_value = map[string]int32{
		"MOVED_PERMANENTLY":  0,
		"FOUND":              1,
		"SEE_OTHER":          2,
		"TEMPORARY_REDIRECT": 3,
		"PERMANENT_REDIRECT": 4,
	}
)

func (x RedirectAction_RedirectResponseCode) ToInt() int32 {
	return RedirectAction_RedirectResponseCode_value[strings.ToUpper(string(x))]
}

// RequestMethod is an enum type.
type RequestMethod string

const (
	RequestMethod_METHOD_UNSPECIFIED RequestMethod = "METHOD_UNSPECIFIED"
	RequestMethod_GET                RequestMethod = "GET"
	RequestMethod_HEAD               RequestMethod = "HEAD"
	RequestMethod_POST               RequestMethod = "POST"
	RequestMethod_PUT                RequestMethod = "PUT"
	RequestMethod_DELETE             RequestMethod = "DELETE"
	RequestMethod_CONNECT            RequestMethod = "CONNECT"
	RequestMethod_OPTIONS            RequestMethod = "OPTIONS"
	RequestMethod_TRACE              RequestMethod = "TRACE"
	RequestMethod_PATCH              RequestMethod = "PATCH"
)

var (
	RequestMethod_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "GET",
		2: "HEAD",
		3: "POST",
		4: "PUT",
		5: "DELETE",
		6: "CONNECT",
		7: "OPTIONS",
		8: "TRACE",
		9: "PATCH",
	}
	RequestMethod_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"GET":                1,
		"HEAD":               2,
		"POST":               3,
		"PUT":                4,
		"DELETE":             5,
		"CONNECT":            6,
		"OPTIONS":            7,
		"TRACE":              8,
		"PATCH":              9,
	}
)

func (x RequestMethod) ToInt() int32 {
	return RequestMethod_value[strings.ToUpper(string(x))]
}

// RetryPolicy_ResetHeaderFormat is an enum type.
type RetryPolicy_ResetHeaderFormat string

const (
	RetryPolicy_ResetHeaderFormat_SECONDS        RetryPolicy_ResetHeaderFormat = "SECONDS"
	RetryPolicy_ResetHeaderFormat_UNIX_TIMESTAMP RetryPolicy_ResetHeaderFormat = "UNIX_TIMESTAMP"
)

var (
	RetryPolicy_ResetHeaderFormat_name = map[int32]string{
		0: "SECONDS",
		1: "UNIX_TIMESTAMP",
	}
	RetryPolicy_ResetHeaderFormat_value = map[string]int32{
		"SECONDS":        0,
		"UNIX_TIMESTAMP": 1,
	}
)

func (x RetryPolicy_ResetHeaderFormat) ToInt() int32 {
	return RetryPolicy_ResetHeaderFormat_value[strings.ToUpper(string(x))]
}

// RouteAction_ClusterNotFoundResponseCode is an enum type.
type RouteAction_ClusterNotFoundResponseCode string

const (
	RouteAction_ClusterNotFoundResponseCode_SERVICE_UNAVAILABLE   RouteAction_ClusterNotFoundResponseCode = "SERVICE_UNAVAILABLE"
	RouteAction_ClusterNotFoundResponseCode_NOT_FOUND             RouteAction_ClusterNotFoundResponseCode = "NOT_FOUND"
	RouteAction_ClusterNotFoundResponseCode_INTERNAL_SERVER_ERROR RouteAction_ClusterNotFoundResponseCode = "INTERNAL_SERVER_ERROR"
)

var (
	RouteAction_ClusterNotFoundResponseCode_name = map[int32]string{
		0: "SERVICE_UNAVAILABLE",
		1: "NOT_FOUND",
		2: "INTERNAL_SERVER_ERROR",
	}
	RouteAction_ClusterNotFoundResponseCode_value = map[string]int32{
		"SERVICE_UNAVAILABLE":   0,
		"NOT_FOUND":             1,
		"INTERNAL_SERVER_ERROR": 2,
	}
)

func (x RouteAction_ClusterNotFoundResponseCode) ToInt() int32 {
	return RouteAction_ClusterNotFoundResponseCode_value[strings.ToUpper(string(x))]
}

// RouteAction_InternalRedirectAction is an enum type.
type RouteAction_InternalRedirectAction string

const (
	RouteAction_InternalRedirectAction_PASS_THROUGH_INTERNAL_REDIRECT RouteAction_InternalRedirectAction = "PASS_THROUGH_INTERNAL_REDIRECT"
	RouteAction_InternalRedirectAction_HANDLE_INTERNAL_REDIRECT       RouteAction_InternalRedirectAction = "HANDLE_INTERNAL_REDIRECT"
)

var (
	RouteAction_InternalRedirectAction_name = map[int32]string{
		0: "PASS_THROUGH_INTERNAL_REDIRECT",
		1: "HANDLE_INTERNAL_REDIRECT",
	}
	RouteAction_InternalRedirectAction_value = map[string]int32{
		"PASS_THROUGH_INTERNAL_REDIRECT": 0,
		"HANDLE_INTERNAL_REDIRECT":       1,
	}
)

func (x RouteAction_InternalRedirectAction) ToInt() int32 {
	return RouteAction_InternalRedirectAction_value[strings.ToUpper(string(x))]
}

// RoutingPriority is an enum type.
type RoutingPriority string

const (
	RoutingPriority_DEFAULT RoutingPriority = "DEFAULT"
	RoutingPriority_HIGH    RoutingPriority = "HIGH"
)

var (
	RoutingPriority_name = map[int32]string{
		0: "DEFAULT",
		1: "HIGH",
	}
	RoutingPriority_value = map[string]int32{
		"DEFAULT": 0,
		"HIGH":    1,
	}
)

func (x RoutingPriority) ToInt() int32 {
	return RoutingPriority_value[strings.ToUpper(string(x))]
}

// TrafficDirection is an enum type.
type TrafficDirection string

const (
	TrafficDirection_UNSPECIFIED TrafficDirection = "UNSPECIFIED"
	TrafficDirection_INBOUND     TrafficDirection = "INBOUND"
	TrafficDirection_OUTBOUND    TrafficDirection = "OUTBOUND"
)

var (
	TrafficDirection_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INBOUND",
		2: "OUTBOUND",
	}
	TrafficDirection_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INBOUND":     1,
		"OUTBOUND":    2,
	}
)

func (x TrafficDirection) ToInt() int32 {
	return TrafficDirection_value[strings.ToUpper(string(x))]
}

// VirtualHost_TlsRequirementType is an enum type.
type VirtualHost_TlsRequirementType string

const (
	VirtualHost_TlsRequirementType_NONE          VirtualHost_TlsRequirementType = "NONE"
	VirtualHost_TlsRequirementType_EXTERNAL_ONLY VirtualHost_TlsRequirementType = "EXTERNAL_ONLY"
	VirtualHost_TlsRequirementType_ALL           VirtualHost_TlsRequirementType = "ALL"
)

var (
	VirtualHost_TlsRequirementType_name = map[int32]string{
		0: "NONE",
		1: "EXTERNAL_ONLY",
		2: "ALL",
	}
	VirtualHost_TlsRequirementType_value = map[string]int32{
		"NONE":          0,
		"EXTERNAL_ONLY": 1,
		"ALL":           2,
	}
)

func (x VirtualHost_TlsRequirementType) ToInt() int32 {
	return VirtualHost_TlsRequirementType_value[strings.ToUpper(string(x))]
}

// RDS represents the Envoy RDS configuration.
type RDS struct {
	Name                               string                             `json:"name,omitempty"`
	VirtualHosts                       []*VirtualHost                     `json:"virtual_hosts,omitempty"`
	Vhds                               *Vhds                              `json:"vhds,omitempty"`
	InternalOnlyHeaders                []string                           `json:"internal_only_headers,omitempty"`
	ResponseHeadersToAdd               []*HeaderValueOption               `json:"response_headers_to_add,omitempty"`
	ResponseHeadersToRemove            []string                           `json:"response_headers_to_remove,omitempty"`
	RequestHeadersToAdd                []*HeaderValueOption               `json:"request_headers_to_add,omitempty"`
	RequestHeadersToRemove             []string                           `json:"request_headers_to_remove,omitempty"`
	MostSpecificHeaderMutationsWins    bool                               `json:"most_specific_header_mutations_wins,omitempty"`
	ValidateClusters                   *bool                              `json:"validate_clusters,omitempty"`
	MaxDirectResponseBodySizeBytes     *uint32                            `json:"max_direct_response_body_size_bytes,omitempty"`
	ClusterSpecifierPlugins            []*ClusterSpecifierPlugin          `json:"cluster_specifier_plugins,omitempty"`
	RequestMirrorPolicies              []*RouteAction_RequestMirrorPolicy `json:"request_mirror_policies,omitempty"`
	IgnorePortInHostMatching           bool                               `json:"ignore_port_in_host_matching,omitempty"`
	IgnorePathParametersInPathMatching bool                               `json:"ignore_path_parameters_in_path_matching,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedPerFilterConfig map[string]*runtime.RawExtension `json:"typed_per_filter_config,omitempty"`
	Metadata             *Metadata                        `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RDS) DeepCopyInto(out *RDS) {
	*out = *in
	if in.VirtualHosts != nil {
		in, out := &in.VirtualHosts, &out.VirtualHosts
		*out = make([]*VirtualHost, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(VirtualHost)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Vhds != nil {
		in, out := &in.Vhds, &out.Vhds
		*out = new(Vhds)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalOnlyHeaders != nil {
		in, out := &in.InternalOnlyHeaders, &out.InternalOnlyHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseHeadersToAdd != nil {
		in, out := &in.ResponseHeadersToAdd, &out.ResponseHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseHeadersToRemove != nil {
		in, out := &in.ResponseHeadersToRemove, &out.ResponseHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequestHeadersToAdd != nil {
		in, out := &in.RequestHeadersToAdd, &out.RequestHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToRemove != nil {
		in, out := &in.RequestHeadersToRemove, &out.RequestHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidateClusters != nil {
		in, out := &in.ValidateClusters, &out.ValidateClusters
		*out = new(bool)
		**out = **in
	}
	if in.MaxDirectResponseBodySizeBytes != nil {
		in, out := &in.MaxDirectResponseBodySizeBytes, &out.MaxDirectResponseBodySizeBytes
		*out = new(uint32)
		**out = **in
	}
	if in.ClusterSpecifierPlugins != nil {
		in, out := &in.ClusterSpecifierPlugins, &out.ClusterSpecifierPlugins
		*out = make([]*ClusterSpecifierPlugin, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(ClusterSpecifierPlugin)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestMirrorPolicies != nil {
		in, out := &in.RequestMirrorPolicies, &out.RequestMirrorPolicies
		*out = make([]*RouteAction_RequestMirrorPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RouteAction_RequestMirrorPolicy)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.TypedPerFilterConfig != nil {
		in, out := &in.TypedPerFilterConfig, &out.TypedPerFilterConfig
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
}

// ClusterSpecifierPlugin represents the Envoy ClusterSpecifierPlugin configuration.
type ClusterSpecifierPlugin struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
	Extension   *TypedExtensionConfig `json:"extension,omitempty"`
	IsOptional  bool                  `json:"is_optional,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterSpecifierPlugin) DeepCopyInto(out *ClusterSpecifierPlugin) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// ConfigSource represents the Envoy ConfigSource configuration.
type ConfigSource struct {
	InitialFetchTimeout *string    `json:"initial_fetch_timeout,omitempty"`
	ResourceApiVersion  ApiVersion `json:"resource_api_version,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.InitialFetchTimeout != nil {
		in, out := &in.InitialFetchTimeout, &out.InitialFetchTimeout
		*out = new(string)
		**out = **in
	}
}

// CorsPolicy represents the Envoy CorsPolicy configuration.
type CorsPolicy struct {
	AllowOriginStringMatch       []*StringMatcher          `json:"allow_origin_string_match,omitempty"`
	AllowMethods                 string                    `json:"allow_methods,omitempty"`
	AllowHeaders                 string                    `json:"allow_headers,omitempty"`
	ExposeHeaders                string                    `json:"expose_headers,omitempty"`
	MaxAge                       string                    `json:"max_age,omitempty"`
	AllowCredentials             *bool                     `json:"allow_credentials,omitempty"`
	FilterEnabled                *RuntimeFractionalPercent `json:"filter_enabled,omitempty"`
	ShadowEnabled                *RuntimeFractionalPercent `json:"shadow_enabled,omitempty"`
	AllowPrivateNetworkAccess    *bool                     `json:"allow_private_network_access,omitempty"`
	ForwardNotMatchingPreflights *bool                     `json:"forward_not_matching_preflights,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *CorsPolicy) DeepCopyInto(out *CorsPolicy) {
	*out = *in
	if in.AllowOriginStringMatch != nil {
		in, out := &in.AllowOriginStringMatch, &out.AllowOriginStringMatch
		*out = make([]*StringMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(StringMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.AllowCredentials != nil {
		in, out := &in.AllowCredentials, &out.AllowCredentials
		*out = new(bool)
		**out = **in
	}
	if in.FilterEnabled != nil {
		in, out := &in.FilterEnabled, &out.FilterEnabled
		*out = new(RuntimeFractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.ShadowEnabled != nil {
		in, out := &in.ShadowEnabled, &out.ShadowEnabled
		*out = new(RuntimeFractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowPrivateNetworkAccess != nil {
		in, out := &in.AllowPrivateNetworkAccess, &out.AllowPrivateNetworkAccess
		*out = new(bool)
		**out = **in
	}
	if in.ForwardNotMatchingPreflights != nil {
		in, out := &in.ForwardNotMatchingPreflights, &out.ForwardNotMatchingPreflights
		*out = new(bool)
		**out = **in
	}
}

// CustomTag represents the Envoy CustomTag configuration.
type CustomTag struct {
	Tag string `json:"tag,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *CustomTag) DeepCopyInto(out *CustomTag) {
	*out = *in
}

// DataSource represents the Envoy DataSource configuration.
type DataSource struct {
	Filename            string            `json:"filename,omitempty"`
	InlineBytes         []byte            `json:"inline_bytes,omitempty"`
	InlineString        string            `json:"inline_string,omitempty"`
	EnvironmentVariable string            `json:"environment_variable,omitempty"`
	WatchedDirectory    *WatchedDirectory `json:"watched_directory,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	if in.InlineBytes != nil {
		in, out := &in.InlineBytes, &out.InlineBytes
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.WatchedDirectory != nil {
		in, out := &in.WatchedDirectory, &out.WatchedDirectory
		*out = new(WatchedDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// Decorator represents the Envoy Decorator configuration.
type Decorator struct {
	Operation string `json:"operation,omitempty"`
	Propagate *bool  `json:"propagate,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Decorator) DeepCopyInto(out *Decorator) {
	*out = *in
	if in.Propagate != nil {
		in, out := &in.Propagate, &out.Propagate
		*out = new(bool)
		**out = **in
	}
}

// DirectResponseAction represents the Envoy DirectResponseAction configuration.
type DirectResponseAction struct {
	Status uint32      `json:"status,omitempty"`
	Body   *DataSource `json:"body,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DirectResponseAction) DeepCopyInto(out *DirectResponseAction) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(DataSource)
		(*in).DeepCopyInto(*out)
	}
}

// DoubleMatcher represents the Envoy DoubleMatcher configuration.
type DoubleMatcher struct {
	Range *DoubleRange `json:"range,omitempty"`
	Exact float64      `json:"exact,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DoubleMatcher) DeepCopyInto(out *DoubleMatcher) {
	*out = *in
	if in.Range != nil {
		in, out := &in.Range, &out.Range
		*out = new(DoubleRange)
		(*in).DeepCopyInto(*out)
	}
}

// DoubleRange represents the Envoy DoubleRange configuration.
type DoubleRange struct {
	Start float64 `json:"start,omitempty"`
	End   float64 `json:"end,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DoubleRange) DeepCopyInto(out *DoubleRange) {
	*out = *in
}

// FilterAction represents the Envoy FilterAction configuration.
type FilterAction struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Action *runtime.RawExtension `json:"action,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FilterAction) DeepCopyInto(out *FilterAction) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// FilterStateMatcher represents the Envoy FilterStateMatcher configuration.
type FilterStateMatcher struct {
	Key string `json:"key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FilterStateMatcher) DeepCopyInto(out *FilterStateMatcher) {
	*out = *in
}

// FractionalPercent represents the Envoy FractionalPercent configuration.
type FractionalPercent struct {
	Numerator   uint32                            `json:"numerator,omitempty"`
	Denominator FractionalPercent_DenominatorType `json:"denominator,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FractionalPercent) DeepCopyInto(out *FractionalPercent) {
	*out = *in
}

// HeaderMatcher represents the Envoy HeaderMatcher configuration.
type HeaderMatcher struct {
	Name                      string         `json:"name,omitempty"`
	ExactMatch                string         `json:"exact_match,omitempty"`
	SafeRegexMatch            *RegexMatcher  `json:"safe_regex_match,omitempty"`
	RangeMatch                *Int64Range    `json:"range_match,omitempty"`
	PresentMatch              bool           `json:"present_match,omitempty"`
	PrefixMatch               string         `json:"prefix_match,omitempty"`
	SuffixMatch               string         `json:"suffix_match,omitempty"`
	ContainsMatch             string         `json:"contains_match,omitempty"`
	StringMatch               *StringMatcher `json:"string_match,omitempty"`
	InvertMatch               bool           `json:"invert_match,omitempty"`
	TreatMissingHeaderAsEmpty bool           `json:"treat_missing_header_as_empty,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderMatcher) DeepCopyInto(out *HeaderMatcher) {
	*out = *in
	if in.SafeRegexMatch != nil {
		in, out := &in.SafeRegexMatch, &out.SafeRegexMatch
		*out = new(RegexMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.RangeMatch != nil {
		in, out := &in.RangeMatch, &out.RangeMatch
		*out = new(Int64Range)
		(*in).DeepCopyInto(*out)
	}
	if in.StringMatch != nil {
		in, out := &in.StringMatch, &out.StringMatch
		*out = new(StringMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// HeaderMutation represents the Envoy HeaderMutation configuration.
type HeaderMutation struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderMutation) DeepCopyInto(out *HeaderMutation) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// HeaderValue represents the Envoy HeaderValue configuration.
type HeaderValue struct {
	Key      string `json:"key,omitempty"`
	Value    string `json:"value,omitempty"`
	RawValue []byte `json:"raw_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderValue) DeepCopyInto(out *HeaderValue) {
	*out = *in
	if in.RawValue != nil {
		in, out := &in.RawValue, &out.RawValue
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// HeaderValueOption represents the Envoy HeaderValueOption configuration.
type HeaderValueOption struct {
	Header         *HeaderValue                         `json:"header,omitempty"`
	Append         *bool                                `json:"append,omitempty"`
	AppendAction   HeaderValueOption_HeaderAppendAction `json:"append_action,omitempty"`
	KeepEmptyValue bool                                 `json:"keep_empty_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderValueOption) DeepCopyInto(out *HeaderValueOption) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(HeaderValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = new(bool)
		**out = **in
	}
}

// HedgePolicy represents the Envoy HedgePolicy configuration.
type HedgePolicy struct {
	InitialRequests         *uint32            `json:"initial_requests,omitempty"`
	AdditionalRequestChance *FractionalPercent `json:"additional_request_chance,omitempty"`
	HedgeOnPerTryTimeout    bool               `json:"hedge_on_per_try_timeout,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HedgePolicy) DeepCopyInto(out *HedgePolicy) {
	*out = *in
	if in.InitialRequests != nil {
		in, out := &in.InitialRequests, &out.InitialRequests
		*out = new(uint32)
		**out = **in
	}
	if in.AdditionalRequestChance != nil {
		in, out := &in.AdditionalRequestChance, &out.AdditionalRequestChance
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
}

// Int64Range represents the Envoy Int64Range configuration.
type Int64Range struct {
	Start int64 `json:"start,omitempty"`
	End   int64 `json:"end,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Int64Range) DeepCopyInto(out *Int64Range) {
	*out = *in
}

// InternalRedirectPolicy represents the Envoy InternalRedirectPolicy configuration.
type InternalRedirectPolicy struct {
	MaxInternalRedirects     *uint32                 `json:"max_internal_redirects,omitempty"`
	RedirectResponseCodes    []uint32                `json:"redirect_response_codes,omitempty"`
	Predicates               []*TypedExtensionConfig `json:"predicates,omitempty"`
	AllowCrossSchemeRedirect bool                    `json:"allow_cross_scheme_redirect,omitempty"`
	ResponseHeadersToCopy    []string                `json:"response_headers_to_copy,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *InternalRedirectPolicy) DeepCopyInto(out *InternalRedirectPolicy) {
	*out = *in
	if in.MaxInternalRedirects != nil {
		in, out := &in.MaxInternalRedirects, &out.MaxInternalRedirects
		*out = new(uint32)
		**out = **in
	}
	if in.RedirectResponseCodes != nil {
		in, out := &in.RedirectResponseCodes, &out.RedirectResponseCodes
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseHeadersToCopy != nil {
		in, out := &in.ResponseHeadersToCopy, &out.ResponseHeadersToCopy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// JsonFormatOptions represents the Envoy JsonFormatOptions configuration.
type JsonFormatOptions struct {
	SortProperties bool `json:"sort_properties,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *JsonFormatOptions) DeepCopyInto(out *JsonFormatOptions) {
	*out = *in
}

// ListMatcher represents the Envoy ListMatcher configuration.
type ListMatcher struct {
	OneOf *ValueMatcher `json:"one_of,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ListMatcher) DeepCopyInto(out *ListMatcher) {
	*out = *in
	if in.OneOf != nil {
		in, out := &in.OneOf, &out.OneOf
		*out = new(ValueMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// Metadata represents the Envoy Metadata configuration.
type Metadata struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	FilterMetadata map[string]*runtime.RawExtension `json:"filter_metadata,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedFilterMetadata map[string]*runtime.RawExtension `json:"typed_filter_metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
	if in.FilterMetadata != nil {
		in, out := &in.FilterMetadata, &out.FilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TypedFilterMetadata != nil {
		in, out := &in.TypedFilterMetadata, &out.TypedFilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// MetadataKey represents the Envoy MetadataKey configuration.
type MetadataKey struct {
	Key string `json:"key,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Path []*runtime.RawExtension `json:"path,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *MetadataKey) DeepCopyInto(out *MetadataKey) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(runtime.RawExtension)
				*(*out)[i] = *(*in)[i]
			}
		}
	}
}

// MetadataMatcher represents the Envoy MetadataMatcher configuration.
type MetadataMatcher struct {
	Filter string                         `json:"filter,omitempty"`
	Path   []*MetadataMatcher_PathSegment `json:"path,omitempty"`
	Value  *ValueMatcher                  `json:"value,omitempty"`
	Invert bool                           `json:"invert,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *MetadataMatcher) DeepCopyInto(out *MetadataMatcher) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]*MetadataMatcher_PathSegment, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(MetadataMatcher_PathSegment)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(ValueMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// MetadataMatcher_PathSegment represents the Envoy MetadataMatcher_PathSegment configuration.
type MetadataMatcher_PathSegment struct {
	Key string `json:"key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *MetadataMatcher_PathSegment) DeepCopyInto(out *MetadataMatcher_PathSegment) {
	*out = *in
}

// OrMatcher represents the Envoy OrMatcher configuration.
type OrMatcher struct {
	ValueMatchers []*ValueMatcher `json:"value_matchers,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *OrMatcher) DeepCopyInto(out *OrMatcher) {
	*out = *in
	if in.ValueMatchers != nil {
		in, out := &in.ValueMatchers, &out.ValueMatchers
		*out = make([]*ValueMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(ValueMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// ProxyProtocolConfig represents the Envoy ProxyProtocolConfig configuration.
type ProxyProtocolConfig struct {
	Version         ProxyProtocolConfig_Version   `json:"version,omitempty"`
	PassThroughTlvs *ProxyProtocolPassThroughTLVs `json:"pass_through_tlvs,omitempty"`
	AddedTlvs       []*TlvEntry                   `json:"added_tlvs,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ProxyProtocolConfig) DeepCopyInto(out *ProxyProtocolConfig) {
	*out = *in
	if in.PassThroughTlvs != nil {
		in, out := &in.PassThroughTlvs, &out.PassThroughTlvs
		*out = new(ProxyProtocolPassThroughTLVs)
		(*in).DeepCopyInto(*out)
	}
	if in.AddedTlvs != nil {
		in, out := &in.AddedTlvs, &out.AddedTlvs
		*out = make([]*TlvEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TlvEntry)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// ProxyProtocolPassThroughTLVs represents the Envoy ProxyProtocolPassThroughTLVs configuration.
type ProxyProtocolPassThroughTLVs struct {
	MatchType ProxyProtocolPassThroughTLVs_PassTLVsMatchType `json:"match_type,omitempty"`
	TlvType   []uint32                                       `json:"tlv_type,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ProxyProtocolPassThroughTLVs) DeepCopyInto(out *ProxyProtocolPassThroughTLVs) {
	*out = *in
	if in.TlvType != nil {
		in, out := &in.TlvType, &out.TlvType
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// QueryParameterMatcher represents the Envoy QueryParameterMatcher configuration.
type QueryParameterMatcher struct {
	Name         string         `json:"name,omitempty"`
	StringMatch  *StringMatcher `json:"string_match,omitempty"`
	PresentMatch bool           `json:"present_match,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *QueryParameterMatcher) DeepCopyInto(out *QueryParameterMatcher) {
	*out = *in
	if in.StringMatch != nil {
		in, out := &in.StringMatch, &out.StringMatch
		*out = new(StringMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// RateLimit represents the Envoy RateLimit configuration.
type RateLimit struct {
	Stage             *uint32               `json:"stage,omitempty"`
	DisableKey        string                `json:"disable_key,omitempty"`
	Actions           []*RateLimit_Action   `json:"actions,omitempty"`
	Limit             *RateLimit_Override   `json:"limit,omitempty"`
	HitsAddend        *RateLimit_HitsAddend `json:"hits_addend,omitempty"`
	ApplyOnStreamDone bool                  `json:"apply_on_stream_done,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit) DeepCopyInto(out *RateLimit) {
	*out = *in
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(uint32)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]*RateLimit_Action, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RateLimit_Action)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(RateLimit_Override)
		(*in).DeepCopyInto(*out)
	}
	if in.HitsAddend != nil {
		in, out := &in.HitsAddend, &out.HitsAddend
		*out = new(RateLimit_HitsAddend)
		(*in).DeepCopyInto(*out)
	}
}

// RateLimit_Action represents the Envoy RateLimit_Action configuration.
type RateLimit_Action struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	SourceCluster *runtime.RawExtension `json:"source_cluster,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	DestinationCluster *runtime.RawExtension `json:"destination_cluster,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	RequestHeaders *runtime.RawExtension `json:"request_headers,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	QueryParameters *runtime.RawExtension `json:"query_parameters,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	RemoteAddress *runtime.RawExtension `json:"remote_address,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	GenericKey *runtime.RawExtension `json:"generic_key,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	HeaderValueMatch *runtime.RawExtension `json:"header_value_match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	DynamicMetadata *runtime.RawExtension `json:"dynamic_metadata,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Metadata  *runtime.RawExtension `json:"metadata,omitempty"`
	Extension *TypedExtensionConfig `json:"extension,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	MaskedRemoteAddress *runtime.RawExtension `json:"masked_remote_address,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	QueryParameterValueMatch *runtime.RawExtension `json:"query_parameter_value_match,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action) DeepCopyInto(out *RateLimit_Action) {
	*out = *in
	if in.SourceCluster != nil {
		in, out := &in.SourceCluster, &out.SourceCluster
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.DestinationCluster != nil {
		in, out := &in.DestinationCluster, &out.DestinationCluster
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.QueryParameters != nil {
		in, out := &in.QueryParameters, &out.QueryParameters
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.RemoteAddress != nil {
		in, out := &in.RemoteAddress, &out.RemoteAddress
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.GenericKey != nil {
		in, out := &in.GenericKey, &out.GenericKey
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.HeaderValueMatch != nil {
		in, out := &in.HeaderValueMatch, &out.HeaderValueMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.DynamicMetadata != nil {
		in, out := &in.DynamicMetadata, &out.DynamicMetadata
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Extension != nil {
		in, out := &in.Extension, &out.Extension
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaskedRemoteAddress != nil {
		in, out := &in.MaskedRemoteAddress, &out.MaskedRemoteAddress
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.QueryParameterValueMatch != nil {
		in, out := &in.QueryParameterValueMatch, &out.QueryParameterValueMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RateLimit_Action_DynamicMetaData represents the Envoy RateLimit_Action_DynamicMetaData configuration.
type RateLimit_Action_DynamicMetaData struct {
	DescriptorKey string       `json:"descriptor_key,omitempty"`
	MetadataKey   *MetadataKey `json:"metadata_key,omitempty"`
	DefaultValue  string       `json:"default_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_DynamicMetaData) DeepCopyInto(out *RateLimit_Action_DynamicMetaData) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(MetadataKey)
		(*in).DeepCopyInto(*out)
	}
}

// RateLimit_Action_GenericKey represents the Envoy RateLimit_Action_GenericKey configuration.
type RateLimit_Action_GenericKey struct {
	DescriptorValue string `json:"descriptor_value,omitempty"`
	DescriptorKey   string `json:"descriptor_key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_GenericKey) DeepCopyInto(out *RateLimit_Action_GenericKey) {
	*out = *in
}

// RateLimit_Action_HeaderValueMatch represents the Envoy RateLimit_Action_HeaderValueMatch configuration.
type RateLimit_Action_HeaderValueMatch struct {
	DescriptorKey   string           `json:"descriptor_key,omitempty"`
	DescriptorValue string           `json:"descriptor_value,omitempty"`
	ExpectMatch     *bool            `json:"expect_match,omitempty"`
	Headers         []*HeaderMatcher `json:"headers,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_HeaderValueMatch) DeepCopyInto(out *RateLimit_Action_HeaderValueMatch) {
	*out = *in
	if in.ExpectMatch != nil {
		in, out := &in.ExpectMatch, &out.ExpectMatch
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]*HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RateLimit_Action_MaskedRemoteAddress represents the Envoy RateLimit_Action_MaskedRemoteAddress configuration.
type RateLimit_Action_MaskedRemoteAddress struct {
	V4PrefixMaskLen *uint32 `json:"v4_prefix_mask_len,omitempty"`
	V6PrefixMaskLen *uint32 `json:"v6_prefix_mask_len,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_MaskedRemoteAddress) DeepCopyInto(out *RateLimit_Action_MaskedRemoteAddress) {
	*out = *in
	if in.V4PrefixMaskLen != nil {
		in, out := &in.V4PrefixMaskLen, &out.V4PrefixMaskLen
		*out = new(uint32)
		**out = **in
	}
	if in.V6PrefixMaskLen != nil {
		in, out := &in.V6PrefixMaskLen, &out.V6PrefixMaskLen
		*out = new(uint32)
		**out = **in
	}
}

// RateLimit_Action_MetaData represents the Envoy RateLimit_Action_MetaData configuration.
type RateLimit_Action_MetaData struct {
	DescriptorKey string                           `json:"descriptor_key,omitempty"`
	MetadataKey   *MetadataKey                     `json:"metadata_key,omitempty"`
	DefaultValue  string                           `json:"default_value,omitempty"`
	Source        RateLimit_Action_MetaData_Source `json:"source,omitempty"`
	SkipIfAbsent  bool                             `json:"skip_if_absent,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_MetaData) DeepCopyInto(out *RateLimit_Action_MetaData) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(MetadataKey)
		(*in).DeepCopyInto(*out)
	}
}

// RateLimit_Action_QueryParameterValueMatch represents the Envoy RateLimit_Action_QueryParameterValueMatch configuration.
type RateLimit_Action_QueryParameterValueMatch struct {
	DescriptorKey   string                   `json:"descriptor_key,omitempty"`
	DescriptorValue string                   `json:"descriptor_value,omitempty"`
	ExpectMatch     *bool                    `json:"expect_match,omitempty"`
	QueryParameters []*QueryParameterMatcher `json:"query_parameters,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_QueryParameterValueMatch) DeepCopyInto(out *RateLimit_Action_QueryParameterValueMatch) {
	*out = *in
	if in.ExpectMatch != nil {
		in, out := &in.ExpectMatch, &out.ExpectMatch
		*out = new(bool)
		**out = **in
	}
	if in.QueryParameters != nil {
		in, out := &in.QueryParameters, &out.QueryParameters
		*out = make([]*QueryParameterMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(QueryParameterMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RateLimit_Action_QueryParameters represents the Envoy RateLimit_Action_QueryParameters configuration.
type RateLimit_Action_QueryParameters struct {
	QueryParameterName string `json:"query_parameter_name,omitempty"`
	DescriptorKey      string `json:"descriptor_key,omitempty"`
	SkipIfAbsent       bool   `json:"skip_if_absent,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_QueryParameters) DeepCopyInto(out *RateLimit_Action_QueryParameters) {
	*out = *in
}

// RateLimit_Action_RequestHeaders represents the Envoy RateLimit_Action_RequestHeaders configuration.
type RateLimit_Action_RequestHeaders struct {
	HeaderName    string `json:"header_name,omitempty"`
	DescriptorKey string `json:"descriptor_key,omitempty"`
	SkipIfAbsent  bool   `json:"skip_if_absent,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Action_RequestHeaders) DeepCopyInto(out *RateLimit_Action_RequestHeaders) {
	*out = *in
}

// RateLimit_HitsAddend represents the Envoy RateLimit_HitsAddend configuration.
type RateLimit_HitsAddend struct {
	Number *uint64 `json:"number,omitempty"`
	Format string  `json:"format,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_HitsAddend) DeepCopyInto(out *RateLimit_HitsAddend) {
	*out = *in
	if in.Number != nil {
		in, out := &in.Number, &out.Number
		*out = new(uint64)
		**out = **in
	}
}

// RateLimit_Override represents the Envoy RateLimit_Override configuration.
type RateLimit_Override struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	DynamicMetadata *runtime.RawExtension `json:"dynamic_metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Override) DeepCopyInto(out *RateLimit_Override) {
	*out = *in
	if in.DynamicMetadata != nil {
		in, out := &in.DynamicMetadata, &out.DynamicMetadata
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RateLimit_Override_DynamicMetadata represents the Envoy RateLimit_Override_DynamicMetadata configuration.
type RateLimit_Override_DynamicMetadata struct {
	MetadataKey *MetadataKey `json:"metadata_key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimit_Override_DynamicMetadata) DeepCopyInto(out *RateLimit_Override_DynamicMetadata) {
	*out = *in
	if in.MetadataKey != nil {
		in, out := &in.MetadataKey, &out.MetadataKey
		*out = new(MetadataKey)
		(*in).DeepCopyInto(*out)
	}
}

// RedirectAction represents the Envoy RedirectAction configuration.
type RedirectAction struct {
	HttpsRedirect  bool                                `json:"https_redirect,omitempty"`
	SchemeRedirect string                              `json:"scheme_redirect,omitempty"`
	HostRedirect   string                              `json:"host_redirect,omitempty"`
	PortRedirect   uint32                              `json:"port_redirect,omitempty"`
	PathRedirect   string                              `json:"path_redirect,omitempty"`
	PrefixRewrite  string                              `json:"prefix_rewrite,omitempty"`
	RegexRewrite   *RegexMatchAndSubstitute            `json:"regex_rewrite,omitempty"`
	ResponseCode   RedirectAction_RedirectResponseCode `json:"response_code,omitempty"`
	StripQuery     bool                                `json:"strip_query,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RedirectAction) DeepCopyInto(out *RedirectAction) {
	*out = *in
	if in.RegexRewrite != nil {
		in, out := &in.RegexRewrite, &out.RegexRewrite
		*out = new(RegexMatchAndSubstitute)
		(*in).DeepCopyInto(*out)
	}
}

// RegexMatchAndSubstitute represents the Envoy RegexMatchAndSubstitute configuration.
type RegexMatchAndSubstitute struct {
	Pattern      *RegexMatcher `json:"pattern,omitempty"`
	Substitution string        `json:"substitution,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RegexMatchAndSubstitute) DeepCopyInto(out *RegexMatchAndSubstitute) {
	*out = *in
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(RegexMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// RegexMatcher represents the Envoy RegexMatcher configuration.
type RegexMatcher struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	GoogleRe2 *runtime.RawExtension `json:"google_re2,omitempty"`
	Regex     string                `json:"regex,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RegexMatcher) DeepCopyInto(out *RegexMatcher) {
	*out = *in
	if in.GoogleRe2 != nil {
		in, out := &in.GoogleRe2, &out.GoogleRe2
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RetryPolicy represents the Envoy RetryPolicy configuration.
type RetryPolicy struct {
	RetryOn                       string                            `json:"retry_on,omitempty"`
	NumRetries                    *uint32                           `json:"num_retries,omitempty"`
	PerTryTimeout                 *string                           `json:"per_try_timeout,omitempty"`
	PerTryIdleTimeout             *string                           `json:"per_try_idle_timeout,omitempty"`
	RetryPriority                 *RetryPolicy_RetryPriority        `json:"retry_priority,omitempty"`
	RetryHostPredicate            []*RetryPolicy_RetryHostPredicate `json:"retry_host_predicate,omitempty"`
	RetryOptionsPredicates        []*TypedExtensionConfig           `json:"retry_options_predicates,omitempty"`
	HostSelectionRetryMaxAttempts int64                             `json:"host_selection_retry_max_attempts,omitempty"`
	RetriableStatusCodes          []uint32                          `json:"retriable_status_codes,omitempty"`
	RetryBackOff                  *RetryPolicy_RetryBackOff         `json:"retry_back_off,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	RateLimitedRetryBackOff *runtime.RawExtension `json:"rate_limited_retry_back_off,omitempty"`
	RetriableHeaders        []*HeaderMatcher      `json:"retriable_headers,omitempty"`
	RetriableRequestHeaders []*HeaderMatcher      `json:"retriable_request_headers,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.NumRetries != nil {
		in, out := &in.NumRetries, &out.NumRetries
		*out = new(uint32)
		**out = **in
	}
	if in.PerTryTimeout != nil {
		in, out := &in.PerTryTimeout, &out.PerTryTimeout
		*out = new(string)
		**out = **in
	}
	if in.PerTryIdleTimeout != nil {
		in, out := &in.PerTryIdleTimeout, &out.PerTryIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.RetryPriority != nil {
		in, out := &in.RetryPriority, &out.RetryPriority
		*out = new(RetryPolicy_RetryPriority)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryHostPredicate != nil {
		in, out := &in.RetryHostPredicate, &out.RetryHostPredicate
		*out = make([]*RetryPolicy_RetryHostPredicate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RetryPolicy_RetryHostPredicate)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetryOptionsPredicates != nil {
		in, out := &in.RetryOptionsPredicates, &out.RetryOptionsPredicates
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetriableStatusCodes != nil {
		in, out := &in.RetriableStatusCodes, &out.RetriableStatusCodes
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	if in.RetryBackOff != nil {
		in, out := &in.RetryBackOff, &out.RetryBackOff
		*out = new(RetryPolicy_RetryBackOff)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimitedRetryBackOff != nil {
		in, out := &in.RateLimitedRetryBackOff, &out.RateLimitedRetryBackOff
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.RetriableHeaders != nil {
		in, out := &in.RetriableHeaders, &out.RetriableHeaders
		*out = make([]*HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetriableRequestHeaders != nil {
		in, out := &in.RetriableRequestHeaders, &out.RetriableRequestHeaders
		*out = make([]*HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RetryPolicy_RateLimitedRetryBackOff represents the Envoy RetryPolicy_RateLimitedRetryBackOff configuration.
type RetryPolicy_RateLimitedRetryBackOff struct {
	ResetHeaders []*RetryPolicy_ResetHeader `json:"reset_headers,omitempty"`
	MaxInterval  *string                    `json:"max_interval,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RateLimitedRetryBackOff) DeepCopyInto(out *RetryPolicy_RateLimitedRetryBackOff) {
	*out = *in
	if in.ResetHeaders != nil {
		in, out := &in.ResetHeaders, &out.ResetHeaders
		*out = make([]*RetryPolicy_ResetHeader, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RetryPolicy_ResetHeader)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.MaxInterval != nil {
		in, out := &in.MaxInterval, &out.MaxInterval
		*out = new(string)
		**out = **in
	}
}

// RetryPolicy_ResetHeader represents the Envoy RetryPolicy_ResetHeader configuration.
type RetryPolicy_ResetHeader struct {
	Name   string                        `json:"name,omitempty"`
	Format RetryPolicy_ResetHeaderFormat `json:"format,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_ResetHeader) DeepCopyInto(out *RetryPolicy_ResetHeader) {
	*out = *in
}

// RetryPolicy_RetryBackOff represents the Envoy RetryPolicy_RetryBackOff configuration.
type RetryPolicy_RetryBackOff struct {
	BaseInterval *string `json:"base_interval,omitempty"`
	MaxInterval  *string `json:"max_interval,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryBackOff) DeepCopyInto(out *RetryPolicy_RetryBackOff) {
	*out = *in
	if in.BaseInterval != nil {
		in, out := &in.BaseInterval, &out.BaseInterval
		*out = new(string)
		**out = **in
	}
	if in.MaxInterval != nil {
		in, out := &in.MaxInterval, &out.MaxInterval
		*out = new(string)
		**out = **in
	}
}

// RetryPolicy_RetryHostPredicate represents the Envoy RetryPolicy_RetryHostPredicate configuration.
type RetryPolicy_RetryHostPredicate struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryHostPredicate) DeepCopyInto(out *RetryPolicy_RetryHostPredicate) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RetryPolicy_RetryPriority represents the Envoy RetryPolicy_RetryPriority configuration.
type RetryPolicy_RetryPriority struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryPriority) DeepCopyInto(out *RetryPolicy_RetryPriority) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// Route represents the Envoy Route configuration.
type Route struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Match *runtime.RawExtension `json:"match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Route          *runtime.RawExtension `json:"route,omitempty"`
	Redirect       *RedirectAction       `json:"redirect,omitempty"`
	DirectResponse *DirectResponseAction `json:"direct_response,omitempty"`
	FilterAction   *FilterAction         `json:"filter_action,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	NonForwardingAction *runtime.RawExtension `json:"non_forwarding_action,omitempty"`
	Metadata            *Metadata             `json:"metadata,omitempty"`
	Decorator           *Decorator            `json:"decorator,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedPerFilterConfig       map[string]*runtime.RawExtension `json:"typed_per_filter_config,omitempty"`
	RequestHeadersToAdd        []*HeaderValueOption             `json:"request_headers_to_add,omitempty"`
	RequestHeadersToRemove     []string                         `json:"request_headers_to_remove,omitempty"`
	ResponseHeadersToAdd       []*HeaderValueOption             `json:"response_headers_to_add,omitempty"`
	ResponseHeadersToRemove    []string                         `json:"response_headers_to_remove,omitempty"`
	Tracing                    *Tracing                         `json:"tracing,omitempty"`
	PerRequestBufferLimitBytes *uint32                          `json:"per_request_buffer_limit_bytes,omitempty"`
	StatPrefix                 string                           `json:"stat_prefix,omitempty"`
	RequestBodyBufferLimit     *uint64                          `json:"request_body_buffer_limit,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Route) DeepCopyInto(out *Route) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Redirect != nil {
		in, out := &in.Redirect, &out.Redirect
		*out = new(RedirectAction)
		(*in).DeepCopyInto(*out)
	}
	if in.DirectResponse != nil {
		in, out := &in.DirectResponse, &out.DirectResponse
		*out = new(DirectResponseAction)
		(*in).DeepCopyInto(*out)
	}
	if in.FilterAction != nil {
		in, out := &in.FilterAction, &out.FilterAction
		*out = new(FilterAction)
		(*in).DeepCopyInto(*out)
	}
	if in.NonForwardingAction != nil {
		in, out := &in.NonForwardingAction, &out.NonForwardingAction
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Decorator != nil {
		in, out := &in.Decorator, &out.Decorator
		*out = new(Decorator)
		(*in).DeepCopyInto(*out)
	}
	if in.TypedPerFilterConfig != nil {
		in, out := &in.TypedPerFilterConfig, &out.TypedPerFilterConfig
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestHeadersToAdd != nil {
		in, out := &in.RequestHeadersToAdd, &out.RequestHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToRemove != nil {
		in, out := &in.RequestHeadersToRemove, &out.RequestHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseHeadersToAdd != nil {
		in, out := &in.ResponseHeadersToAdd, &out.ResponseHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseHeadersToRemove != nil {
		in, out := &in.ResponseHeadersToRemove, &out.ResponseHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(Tracing)
		(*in).DeepCopyInto(*out)
	}
	if in.PerRequestBufferLimitBytes != nil {
		in, out := &in.PerRequestBufferLimitBytes, &out.PerRequestBufferLimitBytes
		*out = new(uint32)
		**out = **in
	}
	if in.RequestBodyBufferLimit != nil {
		in, out := &in.RequestBodyBufferLimit, &out.RequestBodyBufferLimit
		*out = new(uint64)
		**out = **in
	}
}

// RouteAction represents the Envoy RouteAction configuration.
type RouteAction struct {
	Cluster                      string                                  `json:"cluster,omitempty"`
	ClusterHeader                string                                  `json:"cluster_header,omitempty"`
	WeightedClusters             *WeightedCluster                        `json:"weighted_clusters,omitempty"`
	ClusterSpecifierPlugin       string                                  `json:"cluster_specifier_plugin,omitempty"`
	InlineClusterSpecifierPlugin *ClusterSpecifierPlugin                 `json:"inline_cluster_specifier_plugin,omitempty"`
	ClusterNotFoundResponseCode  RouteAction_ClusterNotFoundResponseCode `json:"cluster_not_found_response_code,omitempty"`
	MetadataMatch                *Metadata                               `json:"metadata_match,omitempty"`
	PrefixRewrite                string                                  `json:"prefix_rewrite,omitempty"`
	RegexRewrite                 *RegexMatchAndSubstitute                `json:"regex_rewrite,omitempty"`
	PathRewritePolicy            *TypedExtensionConfig                   `json:"path_rewrite_policy,omitempty"`
	HostRewriteLiteral           string                                  `json:"host_rewrite_literal,omitempty"`
	AutoHostRewrite              *bool                                   `json:"auto_host_rewrite,omitempty"`
	HostRewriteHeader            string                                  `json:"host_rewrite_header,omitempty"`
	HostRewritePathRegex         *RegexMatchAndSubstitute                `json:"host_rewrite_path_regex,omitempty"`
	AppendXForwardedHost         bool                                    `json:"append_x_forwarded_host,omitempty"`
	Timeout                      *string                                 `json:"timeout,omitempty"`
	IdleTimeout                  *string                                 `json:"idle_timeout,omitempty"`
	FlushTimeout                 *string                                 `json:"flush_timeout,omitempty"`
	EarlyDataPolicy              *TypedExtensionConfig                   `json:"early_data_policy,omitempty"`
	RetryPolicy                  *RetryPolicy                            `json:"retry_policy,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	RetryPolicyTypedConfig *runtime.RawExtension              `json:"retry_policy_typed_config,omitempty"`
	RequestMirrorPolicies  []*RouteAction_RequestMirrorPolicy `json:"request_mirror_policies,omitempty"`
	Priority               RoutingPriority                    `json:"priority,omitempty"`
	RateLimits             []*RateLimit                       `json:"rate_limits,omitempty"`
	IncludeVhRateLimits    *bool                              `json:"include_vh_rate_limits,omitempty"`
	HashPolicy             []*RouteAction_HashPolicy          `json:"hash_policy,omitempty"`
	Cors                   *CorsPolicy                        `json:"cors,omitempty"`
	MaxGrpcTimeout         *string                            `json:"max_grpc_timeout,omitempty"`
	GrpcTimeoutOffset      *string                            `json:"grpc_timeout_offset,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	UpgradeConfigs         []*runtime.RawExtension            `json:"upgrade_configs,omitempty"`
	InternalRedirectPolicy *InternalRedirectPolicy            `json:"internal_redirect_policy,omitempty"`
	InternalRedirectAction RouteAction_InternalRedirectAction `json:"internal_redirect_action,omitempty"`
	MaxInternalRedirects   *uint32                            `json:"max_internal_redirects,omitempty"`
	HedgePolicy            *HedgePolicy                       `json:"hedge_policy,omitempty"`
	MaxStreamDuration      *RouteAction_MaxStreamDuration     `json:"max_stream_duration,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction) DeepCopyInto(out *RouteAction) {
	*out = *in
	if in.WeightedClusters != nil {
		in, out := &in.WeightedClusters, &out.WeightedClusters
		*out = new(WeightedCluster)
		(*in).DeepCopyInto(*out)
	}
	if in.InlineClusterSpecifierPlugin != nil {
		in, out := &in.InlineClusterSpecifierPlugin, &out.InlineClusterSpecifierPlugin
		*out = new(ClusterSpecifierPlugin)
		(*in).DeepCopyInto(*out)
	}
	if in.MetadataMatch != nil {
		in, out := &in.MetadataMatch, &out.MetadataMatch
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.RegexRewrite != nil {
		in, out := &in.RegexRewrite, &out.RegexRewrite
		*out = new(RegexMatchAndSubstitute)
		(*in).DeepCopyInto(*out)
	}
	if in.PathRewritePolicy != nil {
		in, out := &in.PathRewritePolicy, &out.PathRewritePolicy
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoHostRewrite != nil {
		in, out := &in.AutoHostRewrite, &out.AutoHostRewrite
		*out = new(bool)
		**out = **in
	}
	if in.HostRewritePathRegex != nil {
		in, out := &in.HostRewritePathRegex, &out.HostRewritePathRegex
		*out = new(RegexMatchAndSubstitute)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.FlushTimeout != nil {
		in, out := &in.FlushTimeout, &out.FlushTimeout
		*out = new(string)
		**out = **in
	}
	if in.EarlyDataPolicy != nil {
		in, out := &in.EarlyDataPolicy, &out.EarlyDataPolicy
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryPolicyTypedConfig != nil {
		in, out := &in.RetryPolicyTypedConfig, &out.RetryPolicyTypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.RequestMirrorPolicies != nil {
		in, out := &in.RequestMirrorPolicies, &out.RequestMirrorPolicies
		*out = make([]*RouteAction_RequestMirrorPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RouteAction_RequestMirrorPolicy)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = make([]*RateLimit, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RateLimit)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.IncludeVhRateLimits != nil {
		in, out := &in.IncludeVhRateLimits, &out.IncludeVhRateLimits
		*out = new(bool)
		**out = **in
	}
	if in.HashPolicy != nil {
		in, out := &in.HashPolicy, &out.HashPolicy
		*out = make([]*RouteAction_HashPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RouteAction_HashPolicy)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(CorsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxGrpcTimeout != nil {
		in, out := &in.MaxGrpcTimeout, &out.MaxGrpcTimeout
		*out = new(string)
		**out = **in
	}
	if in.GrpcTimeoutOffset != nil {
		in, out := &in.GrpcTimeoutOffset, &out.GrpcTimeoutOffset
		*out = new(string)
		**out = **in
	}
	if in.UpgradeConfigs != nil {
		in, out := &in.UpgradeConfigs, &out.UpgradeConfigs
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(runtime.RawExtension)
				*(*out)[i] = *(*in)[i]
			}
		}
	}
	if in.InternalRedirectPolicy != nil {
		in, out := &in.InternalRedirectPolicy, &out.InternalRedirectPolicy
		*out = new(InternalRedirectPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxInternalRedirects != nil {
		in, out := &in.MaxInternalRedirects, &out.MaxInternalRedirects
		*out = new(uint32)
		**out = **in
	}
	if in.HedgePolicy != nil {
		in, out := &in.HedgePolicy, &out.HedgePolicy
		*out = new(HedgePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxStreamDuration != nil {
		in, out := &in.MaxStreamDuration, &out.MaxStreamDuration
		*out = new(RouteAction_MaxStreamDuration)
		(*in).DeepCopyInto(*out)
	}
}

// RouteAction_HashPolicy represents the Envoy RouteAction_HashPolicy configuration.
type RouteAction_HashPolicy struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	Header *runtime.RawExtension `json:"header,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Cookie *runtime.RawExtension `json:"cookie,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ConnectionProperties *runtime.RawExtension `json:"connection_properties,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	QueryParameter *runtime.RawExtension `json:"query_parameter,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	FilterState *runtime.RawExtension `json:"filter_state,omitempty"`
	Terminal    bool                  `json:"terminal,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy) DeepCopyInto(out *RouteAction_HashPolicy) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Cookie != nil {
		in, out := &in.Cookie, &out.Cookie
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.ConnectionProperties != nil {
		in, out := &in.ConnectionProperties, &out.ConnectionProperties
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.QueryParameter != nil {
		in, out := &in.QueryParameter, &out.QueryParameter
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.FilterState != nil {
		in, out := &in.FilterState, &out.FilterState
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RouteAction_HashPolicy_ConnectionProperties represents the Envoy RouteAction_HashPolicy_ConnectionProperties configuration.
type RouteAction_HashPolicy_ConnectionProperties struct {
	SourceIp bool `json:"source_ip,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_ConnectionProperties) DeepCopyInto(out *RouteAction_HashPolicy_ConnectionProperties) {
	*out = *in
}

// RouteAction_HashPolicy_Cookie represents the Envoy RouteAction_HashPolicy_Cookie configuration.
type RouteAction_HashPolicy_Cookie struct {
	Name       string                                    `json:"name,omitempty"`
	Ttl        *string                                   `json:"ttl,omitempty"`
	Path       string                                    `json:"path,omitempty"`
	Attributes []*RouteAction_HashPolicy_CookieAttribute `json:"attributes,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_Cookie) DeepCopyInto(out *RouteAction_HashPolicy_Cookie) {
	*out = *in
	if in.Ttl != nil {
		in, out := &in.Ttl, &out.Ttl
		*out = new(string)
		**out = **in
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]*RouteAction_HashPolicy_CookieAttribute, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RouteAction_HashPolicy_CookieAttribute)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RouteAction_HashPolicy_CookieAttribute represents the Envoy RouteAction_HashPolicy_CookieAttribute configuration.
type RouteAction_HashPolicy_CookieAttribute struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_CookieAttribute) DeepCopyInto(out *RouteAction_HashPolicy_CookieAttribute) {
	*out = *in
}

// RouteAction_HashPolicy_FilterState represents the Envoy RouteAction_HashPolicy_FilterState configuration.
type RouteAction_HashPolicy_FilterState struct {
	Key string `json:"key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_FilterState) DeepCopyInto(out *RouteAction_HashPolicy_FilterState) {
	*out = *in
}

// RouteAction_HashPolicy_Header represents the Envoy RouteAction_HashPolicy_Header configuration.
type RouteAction_HashPolicy_Header struct {
	HeaderName   string                   `json:"header_name,omitempty"`
	RegexRewrite *RegexMatchAndSubstitute `json:"regex_rewrite,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_Header) DeepCopyInto(out *RouteAction_HashPolicy_Header) {
	*out = *in
	if in.RegexRewrite != nil {
		in, out := &in.RegexRewrite, &out.RegexRewrite
		*out = new(RegexMatchAndSubstitute)
		(*in).DeepCopyInto(*out)
	}
}

// RouteAction_HashPolicy_QueryParameter represents the Envoy RouteAction_HashPolicy_QueryParameter configuration.
type RouteAction_HashPolicy_QueryParameter struct {
	Name string `json:"name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_HashPolicy_QueryParameter) DeepCopyInto(out *RouteAction_HashPolicy_QueryParameter) {
	*out = *in
}

// RouteAction_MaxStreamDuration represents the Envoy RouteAction_MaxStreamDuration configuration.
type RouteAction_MaxStreamDuration struct {
	MaxStreamDuration       *string `json:"max_stream_duration,omitempty"`
	GrpcTimeoutHeaderMax    *string `json:"grpc_timeout_header_max,omitempty"`
	GrpcTimeoutHeaderOffset *string `json:"grpc_timeout_header_offset,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_MaxStreamDuration) DeepCopyInto(out *RouteAction_MaxStreamDuration) {
	*out = *in
	if in.MaxStreamDuration != nil {
		in, out := &in.MaxStreamDuration, &out.MaxStreamDuration
		*out = new(string)
		**out = **in
	}
	if in.GrpcTimeoutHeaderMax != nil {
		in, out := &in.GrpcTimeoutHeaderMax, &out.GrpcTimeoutHeaderMax
		*out = new(string)
		**out = **in
	}
	if in.GrpcTimeoutHeaderOffset != nil {
		in, out := &in.GrpcTimeoutHeaderOffset, &out.GrpcTimeoutHeaderOffset
		*out = new(string)
		**out = **in
	}
}

// RouteAction_RequestMirrorPolicy represents the Envoy RouteAction_RequestMirrorPolicy configuration.
type RouteAction_RequestMirrorPolicy struct {
	Cluster                       string                    `json:"cluster,omitempty"`
	ClusterHeader                 string                    `json:"cluster_header,omitempty"`
	RuntimeFraction               *RuntimeFractionalPercent `json:"runtime_fraction,omitempty"`
	TraceSampled                  *bool                     `json:"trace_sampled,omitempty"`
	DisableShadowHostSuffixAppend bool                      `json:"disable_shadow_host_suffix_append,omitempty"`
	RequestHeadersMutations       []*HeaderMutation         `json:"request_headers_mutations,omitempty"`
	HostRewriteLiteral            string                    `json:"host_rewrite_literal,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_RequestMirrorPolicy) DeepCopyInto(out *RouteAction_RequestMirrorPolicy) {
	*out = *in
	if in.RuntimeFraction != nil {
		in, out := &in.RuntimeFraction, &out.RuntimeFraction
		*out = new(RuntimeFractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.TraceSampled != nil {
		in, out := &in.TraceSampled, &out.TraceSampled
		*out = new(bool)
		**out = **in
	}
	if in.RequestHeadersMutations != nil {
		in, out := &in.RequestHeadersMutations, &out.RequestHeadersMutations
		*out = make([]*HeaderMutation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMutation)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RouteAction_UpgradeConfig represents the Envoy RouteAction_UpgradeConfig configuration.
type RouteAction_UpgradeConfig struct {
	UpgradeType   string                                   `json:"upgrade_type,omitempty"`
	Enabled       *bool                                    `json:"enabled,omitempty"`
	ConnectConfig *RouteAction_UpgradeConfig_ConnectConfig `json:"connect_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_UpgradeConfig) DeepCopyInto(out *RouteAction_UpgradeConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectConfig != nil {
		in, out := &in.ConnectConfig, &out.ConnectConfig
		*out = new(RouteAction_UpgradeConfig_ConnectConfig)
		(*in).DeepCopyInto(*out)
	}
}

// RouteAction_UpgradeConfig_ConnectConfig represents the Envoy RouteAction_UpgradeConfig_ConnectConfig configuration.
type RouteAction_UpgradeConfig_ConnectConfig struct {
	ProxyProtocolConfig *ProxyProtocolConfig `json:"proxy_protocol_config,omitempty"`
	AllowPost           bool                 `json:"allow_post,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteAction_UpgradeConfig_ConnectConfig) DeepCopyInto(out *RouteAction_UpgradeConfig_ConnectConfig) {
	*out = *in
	if in.ProxyProtocolConfig != nil {
		in, out := &in.ProxyProtocolConfig, &out.ProxyProtocolConfig
		*out = new(ProxyProtocolConfig)
		(*in).DeepCopyInto(*out)
	}
}

// RouteMatch represents the Envoy RouteMatch configuration.
type RouteMatch struct {
	Prefix    string        `json:"prefix,omitempty"`
	Path      string        `json:"path,omitempty"`
	SafeRegex *RegexMatcher `json:"safe_regex,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ConnectMatcher      *runtime.RawExtension     `json:"connect_matcher,omitempty"`
	PathSeparatedPrefix string                    `json:"path_separated_prefix,omitempty"`
	PathMatchPolicy     *TypedExtensionConfig     `json:"path_match_policy,omitempty"`
	CaseSensitive       *bool                     `json:"case_sensitive,omitempty"`
	RuntimeFraction     *RuntimeFractionalPercent `json:"runtime_fraction,omitempty"`
	Headers             []*HeaderMatcher          `json:"headers,omitempty"`
	QueryParameters     []*QueryParameterMatcher  `json:"query_parameters,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Grpc            *runtime.RawExtension              `json:"grpc,omitempty"`
	TlsContext      *RouteMatch_TlsContextMatchOptions `json:"tls_context,omitempty"`
	DynamicMetadata []*MetadataMatcher                 `json:"dynamic_metadata,omitempty"`
	FilterState     []*FilterStateMatcher              `json:"filter_state,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteMatch) DeepCopyInto(out *RouteMatch) {
	*out = *in
	if in.SafeRegex != nil {
		in, out := &in.SafeRegex, &out.SafeRegex
		*out = new(RegexMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectMatcher != nil {
		in, out := &in.ConnectMatcher, &out.ConnectMatcher
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.PathMatchPolicy != nil {
		in, out := &in.PathMatchPolicy, &out.PathMatchPolicy
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.RuntimeFraction != nil {
		in, out := &in.RuntimeFraction, &out.RuntimeFraction
		*out = new(RuntimeFractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]*HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.QueryParameters != nil {
		in, out := &in.QueryParameters, &out.QueryParameters
		*out = make([]*QueryParameterMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(QueryParameterMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Grpc != nil {
		in, out := &in.Grpc, &out.Grpc
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.TlsContext != nil {
		in, out := &in.TlsContext, &out.TlsContext
		*out = new(RouteMatch_TlsContextMatchOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DynamicMetadata != nil {
		in, out := &in.DynamicMetadata, &out.DynamicMetadata
		*out = make([]*MetadataMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(MetadataMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.FilterState != nil {
		in, out := &in.FilterState, &out.FilterState
		*out = make([]*FilterStateMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(FilterStateMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RouteMatch_TlsContextMatchOptions represents the Envoy RouteMatch_TlsContextMatchOptions configuration.
type RouteMatch_TlsContextMatchOptions struct {
	Presented *bool `json:"presented,omitempty"`
	Validated *bool `json:"validated,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RouteMatch_TlsContextMatchOptions) DeepCopyInto(out *RouteMatch_TlsContextMatchOptions) {
	*out = *in
	if in.Presented != nil {
		in, out := &in.Presented, &out.Presented
		*out = new(bool)
		**out = **in
	}
	if in.Validated != nil {
		in, out := &in.Validated, &out.Validated
		*out = new(bool)
		**out = **in
	}
}

// RuntimeFractionalPercent represents the Envoy RuntimeFractionalPercent configuration.
type RuntimeFractionalPercent struct {
	DefaultValue *FractionalPercent `json:"default_value,omitempty"`
	RuntimeKey   string             `json:"runtime_key,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RuntimeFractionalPercent) DeepCopyInto(out *RuntimeFractionalPercent) {
	*out = *in
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
}

// StringMatcher represents the Envoy StringMatcher configuration.
type StringMatcher struct {
	Exact      string                `json:"exact,omitempty"`
	Prefix     string                `json:"prefix,omitempty"`
	Suffix     string                `json:"suffix,omitempty"`
	SafeRegex  *RegexMatcher         `json:"safe_regex,omitempty"`
	Contains   string                `json:"contains,omitempty"`
	Custom     *TypedExtensionConfig `json:"custom,omitempty"`
	IgnoreCase bool                  `json:"ignore_case,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *StringMatcher) DeepCopyInto(out *StringMatcher) {
	*out = *in
	if in.SafeRegex != nil {
		in, out := &in.SafeRegex, &out.SafeRegex
		*out = new(RegexMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(TypedExtensionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// SubstitutionFormatString represents the Envoy SubstitutionFormatString configuration.
type SubstitutionFormatString struct {
	OmitEmptyValues   bool                    `json:"omit_empty_values,omitempty"`
	ContentType       string                  `json:"content_type,omitempty"`
	Formatters        []*TypedExtensionConfig `json:"formatters,omitempty"`
	JsonFormatOptions *JsonFormatOptions      `json:"json_format_options,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SubstitutionFormatString) DeepCopyInto(out *SubstitutionFormatString) {
	*out = *in
	if in.Formatters != nil {
		in, out := &in.Formatters, &out.Formatters
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.JsonFormatOptions != nil {
		in, out := &in.JsonFormatOptions, &out.JsonFormatOptions
		*out = new(JsonFormatOptions)
		(*in).DeepCopyInto(*out)
	}
}

// TlvEntry represents the Envoy TlvEntry configuration.
type TlvEntry struct {
	Type         uint32                    `json:"type,omitempty"`
	Value        []byte                    `json:"value,omitempty"`
	FormatString *SubstitutionFormatString `json:"format_string,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TlvEntry) DeepCopyInto(out *TlvEntry) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.FormatString != nil {
		in, out := &in.FormatString, &out.FormatString
		*out = new(SubstitutionFormatString)
		(*in).DeepCopyInto(*out)
	}
}

// Tracing represents the Envoy Tracing configuration.
type Tracing struct {
	ClientSampling  *FractionalPercent `json:"client_sampling,omitempty"`
	RandomSampling  *FractionalPercent `json:"random_sampling,omitempty"`
	OverallSampling *FractionalPercent `json:"overall_sampling,omitempty"`
	CustomTags      []*CustomTag       `json:"custom_tags,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Tracing) DeepCopyInto(out *Tracing) {
	*out = *in
	if in.ClientSampling != nil {
		in, out := &in.ClientSampling, &out.ClientSampling
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.RandomSampling != nil {
		in, out := &in.RandomSampling, &out.RandomSampling
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.OverallSampling != nil {
		in, out := &in.OverallSampling, &out.OverallSampling
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomTags != nil {
		in, out := &in.CustomTags, &out.CustomTags
		*out = make([]*CustomTag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(CustomTag)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// TypedExtensionConfig represents the Envoy TypedExtensionConfig configuration.
type TypedExtensionConfig struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TypedExtensionConfig) DeepCopyInto(out *TypedExtensionConfig) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// ValueMatcher represents the Envoy ValueMatcher configuration.
type ValueMatcher struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	NullMatch    *runtime.RawExtension `json:"null_match,omitempty"`
	DoubleMatch  *DoubleMatcher        `json:"double_match,omitempty"`
	StringMatch  *StringMatcher        `json:"string_match,omitempty"`
	BoolMatch    bool                  `json:"bool_match,omitempty"`
	PresentMatch bool                  `json:"present_match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ListMatch *runtime.RawExtension `json:"list_match,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	OrMatch *runtime.RawExtension `json:"or_match,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ValueMatcher) DeepCopyInto(out *ValueMatcher) {
	*out = *in
	if in.NullMatch != nil {
		in, out := &in.NullMatch, &out.NullMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.DoubleMatch != nil {
		in, out := &in.DoubleMatch, &out.DoubleMatch
		*out = new(DoubleMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.StringMatch != nil {
		in, out := &in.StringMatch, &out.StringMatch
		*out = new(StringMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.ListMatch != nil {
		in, out := &in.ListMatch, &out.ListMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.OrMatch != nil {
		in, out := &in.OrMatch, &out.OrMatch
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// Vhds represents the Envoy Vhds configuration.
type Vhds struct {
	ConfigSource *ConfigSource `json:"config_source,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Vhds) DeepCopyInto(out *Vhds) {
	*out = *in
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// VirtualCluster represents the Envoy VirtualCluster configuration.
type VirtualCluster struct {
	Headers []*HeaderMatcher `json:"headers,omitempty"`
	Name    string           `json:"name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *VirtualCluster) DeepCopyInto(out *VirtualCluster) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]*HeaderMatcher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderMatcher)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// VirtualHost represents the Envoy VirtualHost configuration.
type VirtualHost struct {
	Name                    string                         `json:"name,omitempty"`
	Domains                 []string                       `json:"domains,omitempty"`
	Routes                  []*Route                       `json:"routes,omitempty"`
	RequireTls              VirtualHost_TlsRequirementType `json:"require_tls,omitempty"`
	VirtualClusters         []*VirtualCluster              `json:"virtual_clusters,omitempty"`
	RateLimits              []*RateLimit                   `json:"rate_limits,omitempty"`
	RequestHeadersToAdd     []*HeaderValueOption           `json:"request_headers_to_add,omitempty"`
	RequestHeadersToRemove  []string                       `json:"request_headers_to_remove,omitempty"`
	ResponseHeadersToAdd    []*HeaderValueOption           `json:"response_headers_to_add,omitempty"`
	ResponseHeadersToRemove []string                       `json:"response_headers_to_remove,omitempty"`
	Cors                    *CorsPolicy                    `json:"cors,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedPerFilterConfig          map[string]*runtime.RawExtension `json:"typed_per_filter_config,omitempty"`
	IncludeRequestAttemptCount    bool                             `json:"include_request_attempt_count,omitempty"`
	IncludeAttemptCountInResponse bool                             `json:"include_attempt_count_in_response,omitempty"`
	RetryPolicy                   *RetryPolicy                     `json:"retry_policy,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	RetryPolicyTypedConfig      *runtime.RawExtension              `json:"retry_policy_typed_config,omitempty"`
	HedgePolicy                 *HedgePolicy                       `json:"hedge_policy,omitempty"`
	IncludeIsTimeoutRetryHeader bool                               `json:"include_is_timeout_retry_header,omitempty"`
	PerRequestBufferLimitBytes  *uint32                            `json:"per_request_buffer_limit_bytes,omitempty"`
	RequestBodyBufferLimit      *uint64                            `json:"request_body_buffer_limit,omitempty"`
	RequestMirrorPolicies       []*RouteAction_RequestMirrorPolicy `json:"request_mirror_policies,omitempty"`
	Metadata                    *Metadata                          `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *VirtualHost) DeepCopyInto(out *VirtualHost) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]*Route, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(Route)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.VirtualClusters != nil {
		in, out := &in.VirtualClusters, &out.VirtualClusters
		*out = make([]*VirtualCluster, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(VirtualCluster)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = make([]*RateLimit, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RateLimit)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToAdd != nil {
		in, out := &in.RequestHeadersToAdd, &out.RequestHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToRemove != nil {
		in, out := &in.RequestHeadersToRemove, &out.RequestHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseHeadersToAdd != nil {
		in, out := &in.ResponseHeadersToAdd, &out.ResponseHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseHeadersToRemove != nil {
		in, out := &in.ResponseHeadersToRemove, &out.ResponseHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Cors != nil {
		in, out := &in.Cors, &out.Cors
		*out = new(CorsPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.TypedPerFilterConfig != nil {
		in, out := &in.TypedPerFilterConfig, &out.TypedPerFilterConfig
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryPolicyTypedConfig != nil {
		in, out := &in.RetryPolicyTypedConfig, &out.RetryPolicyTypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.HedgePolicy != nil {
		in, out := &in.HedgePolicy, &out.HedgePolicy
		*out = new(HedgePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PerRequestBufferLimitBytes != nil {
		in, out := &in.PerRequestBufferLimitBytes, &out.PerRequestBufferLimitBytes
		*out = new(uint32)
		**out = **in
	}
	if in.RequestBodyBufferLimit != nil {
		in, out := &in.RequestBodyBufferLimit, &out.RequestBodyBufferLimit
		*out = new(uint64)
		**out = **in
	}
	if in.RequestMirrorPolicies != nil {
		in, out := &in.RequestMirrorPolicies, &out.RequestMirrorPolicies
		*out = make([]*RouteAction_RequestMirrorPolicy, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RouteAction_RequestMirrorPolicy)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
}

// WatchedDirectory represents the Envoy WatchedDirectory configuration.
type WatchedDirectory struct {
	Path string `json:"path,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *WatchedDirectory) DeepCopyInto(out *WatchedDirectory) {
	*out = *in
}

// WeightedCluster represents the Envoy WeightedCluster configuration.
type WeightedCluster struct {
	Clusters           []*WeightedCluster_ClusterWeight `json:"clusters,omitempty"`
	TotalWeight        *uint32                          `json:"total_weight,omitempty"`
	RuntimeKeyPrefix   string                           `json:"runtime_key_prefix,omitempty"`
	HeaderName         string                           `json:"header_name,omitempty"`
	UseHashPolicy      *bool                            `json:"use_hash_policy,omitempty"`
	HostRewriteLiteral string                           `json:"host_rewrite_literal,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *WeightedCluster) DeepCopyInto(out *WeightedCluster) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]*WeightedCluster_ClusterWeight, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(WeightedCluster_ClusterWeight)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.TotalWeight != nil {
		in, out := &in.TotalWeight, &out.TotalWeight
		*out = new(uint32)
		**out = **in
	}
	if in.UseHashPolicy != nil {
		in, out := &in.UseHashPolicy, &out.UseHashPolicy
		*out = new(bool)
		**out = **in
	}
}

// WeightedCluster_ClusterWeight represents the Envoy WeightedCluster_ClusterWeight configuration.
type WeightedCluster_ClusterWeight struct {
	Name                    string               `json:"name,omitempty"`
	ClusterHeader           string               `json:"cluster_header,omitempty"`
	Weight                  *uint32              `json:"weight,omitempty"`
	MetadataMatch           *Metadata            `json:"metadata_match,omitempty"`
	RequestHeadersToAdd     []*HeaderValueOption `json:"request_headers_to_add,omitempty"`
	RequestHeadersToRemove  []string             `json:"request_headers_to_remove,omitempty"`
	ResponseHeadersToAdd    []*HeaderValueOption `json:"response_headers_to_add,omitempty"`
	ResponseHeadersToRemove []string             `json:"response_headers_to_remove,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedPerFilterConfig map[string]*runtime.RawExtension `json:"typed_per_filter_config,omitempty"`
	HostRewriteLiteral   string                           `json:"host_rewrite_literal,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *WeightedCluster_ClusterWeight) DeepCopyInto(out *WeightedCluster_ClusterWeight) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(uint32)
		**out = **in
	}
	if in.MetadataMatch != nil {
		in, out := &in.MetadataMatch, &out.MetadataMatch
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeadersToAdd != nil {
		in, out := &in.RequestHeadersToAdd, &out.RequestHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToRemove != nil {
		in, out := &in.RequestHeadersToRemove, &out.RequestHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseHeadersToAdd != nil {
		in, out := &in.ResponseHeadersToAdd, &out.ResponseHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseHeadersToRemove != nil {
		in, out := &in.ResponseHeadersToRemove, &out.ResponseHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TypedPerFilterConfig != nil {
		in, out := &in.TypedPerFilterConfig, &out.TypedPerFilterConfig
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}
