# =============================================================================
# TCP Proxy Example - Layer 4 Proxying for Databases
# =============================================================================
# This example demonstrates TCP proxying for non-HTTP services like:
#   - PostgreSQL (port 5432)
#   - Redis (port 6379)
#   - MySQL (port 3306)
#   - RabbitMQ (port 5672)
#
# TCP proxy operates at Layer 4, forwarding raw TCP connections without
# any HTTP-level processing.
# =============================================================================

---
# PostgreSQL TCP Proxy Listener
apiVersion: envoyxds.io/v1alpha1
kind: Listener
metadata:
  name: postgres-proxy
  namespace: xds-system
spec:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 5432
  filter_chains:
    - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: postgres
            cluster: postgres-cluster
            idle_timeout: 3600s  # 1 hour idle timeout for long connections

---
# Redis TCP Proxy Listener
apiVersion: envoyxds.io/v1alpha1
kind: Listener
metadata:
  name: redis-proxy
  namespace: xds-system
spec:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6379
  filter_chains:
    - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: redis
            cluster: redis-cluster
            idle_timeout: 300s  # 5 minute idle timeout

---
# MySQL TCP Proxy Listener
apiVersion: envoyxds.io/v1alpha1
kind: Listener
metadata:
  name: mysql-proxy
  namespace: xds-system
spec:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 3306
  filter_chains:
    - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: mysql
            cluster: mysql-cluster

---
# PostgreSQL Cluster
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: xds-system
spec:
  connect_timeout: 5s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: postgres-cluster
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  # Replace with your PostgreSQL service
                  address: postgres.database.svc.cluster.local
                  port_value: 5432
  # TCP health check for PostgreSQL
  health_checks:
    - timeout: 2s
      interval: 10s
      unhealthy_threshold: 3
      healthy_threshold: 1
      tcp_health_check: {}

---
# Redis Cluster with multiple replicas
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: redis-cluster
  namespace: xds-system
spec:
  connect_timeout: 1s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: redis-cluster
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  # Replace with your Redis service
                  address: redis.cache.svc.cluster.local
                  port_value: 6379
  health_checks:
    - timeout: 1s
      interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 1
      tcp_health_check: {}

---
# MySQL Cluster
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: mysql-cluster
  namespace: xds-system
spec:
  connect_timeout: 5s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: mysql-cluster
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  # Replace with your MySQL service
                  address: mysql.database.svc.cluster.local
                  port_value: 3306
  health_checks:
    - timeout: 2s
      interval: 10s
      unhealthy_threshold: 3
      healthy_threshold: 1
      tcp_health_check: {}

