// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/xds/sds.go

// Package mock_xds is a generated GoMock package.
package mock_xds

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/tentens-tech/xds-controller/pkg/xds/types"
)

// MockCertGetter is a mock of CertGetter interface.
type MockCertGetter struct {
	ctrl     *gomock.Controller
	recorder *MockCertGetterMockRecorder
}

// MockCertGetterMockRecorder is the mock recorder for MockCertGetter.
type MockCertGetterMockRecorder struct {
	mock *MockCertGetter
}

// NewMockCertGetter creates a new mock instance.
func NewMockCertGetter(ctrl *gomock.Controller) *MockCertGetter {
	mock := &MockCertGetter{ctrl: ctrl}
	mock.recorder = &MockCertGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCertGetter) EXPECT() *MockCertGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCertGetter) Get(d *types.DomainConfig) (types.Cert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", d)
	ret0, _ := ret[0].(types.Cert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCertGetterMockRecorder) Get(d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCertGetter)(nil).Get), d)
}

// MockGlobalConfig is a mock of GlobalConfig interface.
type MockGlobalConfig struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalConfigMockRecorder
}

// MockGlobalConfigMockRecorder is the mock recorder for MockGlobalConfig.
type MockGlobalConfigMockRecorder struct {
	mock *MockGlobalConfig
}

// NewMockGlobalConfig creates a new mock instance.
func NewMockGlobalConfig(ctrl *gomock.Controller) *MockGlobalConfig {
	mock := &MockGlobalConfig{ctrl: ctrl}
	mock.recorder = &MockGlobalConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalConfig) EXPECT() *MockGlobalConfigMockRecorder {
	return m.recorder
}

// CheckVaultWriteAccess mocks base method.
func (m *MockGlobalConfig) CheckVaultWriteAccess(d *types.DomainConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckVaultWriteAccess", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckVaultWriteAccess indicates an expected call of CheckVaultWriteAccess.
func (mr *MockGlobalConfigMockRecorder) CheckVaultWriteAccess(d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckVaultWriteAccess", reflect.TypeOf((*MockGlobalConfig)(nil).CheckVaultWriteAccess), d)
}

// GetDomainConfigs mocks base method.
func (m *MockGlobalConfig) GetDomainConfigs() map[string][]*types.DomainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomainConfigs")
	ret0, _ := ret[0].(map[string][]*types.DomainConfig)
	return ret0
}

// GetDomainConfigs indicates an expected call of GetDomainConfigs.
func (mr *MockGlobalConfigMockRecorder) GetDomainConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomainConfigs", reflect.TypeOf((*MockGlobalConfig)(nil).GetDomainConfigs))
}

// GetDryRun mocks base method.
func (m *MockGlobalConfig) GetDryRun() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDryRun")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetDryRun indicates an expected call of GetDryRun.
func (mr *MockGlobalConfigMockRecorder) GetDryRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDryRun", reflect.TypeOf((*MockGlobalConfig)(nil).GetDryRun))
}

// GetRenewBeforeExpireInMinutes mocks base method.
func (m *MockGlobalConfig) GetRenewBeforeExpireInMinutes() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRenewBeforeExpireInMinutes")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRenewBeforeExpireInMinutes indicates an expected call of GetRenewBeforeExpireInMinutes.
func (mr *MockGlobalConfigMockRecorder) GetRenewBeforeExpireInMinutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRenewBeforeExpireInMinutes", reflect.TypeOf((*MockGlobalConfig)(nil).GetRenewBeforeExpireInMinutes))
}

// GetRndNumber mocks base method.
func (m *MockGlobalConfig) GetRndNumber() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRndNumber")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRndNumber indicates an expected call of GetRndNumber.
func (mr *MockGlobalConfigMockRecorder) GetRndNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRndNumber", reflect.TypeOf((*MockGlobalConfig)(nil).GetRndNumber))
}

// StorageConfigRead mocks base method.
func (m *MockGlobalConfig) StorageConfigRead(ctx context.Context, d *types.DomainConfig) (types.Cert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageConfigRead", ctx, d)
	ret0, _ := ret[0].(types.Cert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageConfigRead indicates an expected call of StorageConfigRead.
func (mr *MockGlobalConfigMockRecorder) StorageConfigRead(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageConfigRead", reflect.TypeOf((*MockGlobalConfig)(nil).StorageConfigRead), ctx, d)
}

// StorageConfigWrite mocks base method.
func (m *MockGlobalConfig) StorageConfigWrite(d *types.DomainConfig, c types.Cert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageConfigWrite", d, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageConfigWrite indicates an expected call of StorageConfigWrite.
func (mr *MockGlobalConfigMockRecorder) StorageConfigWrite(d, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageConfigWrite", reflect.TypeOf((*MockGlobalConfig)(nil).StorageConfigWrite), d, c)
}

// MockStorageConfigReaderWriter is a mock of StorageConfigReaderWriter interface.
type MockStorageConfigReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStorageConfigReaderWriterMockRecorder
}

// MockStorageConfigReaderWriterMockRecorder is the mock recorder for MockStorageConfigReaderWriter.
type MockStorageConfigReaderWriterMockRecorder struct {
	mock *MockStorageConfigReaderWriter
}

// NewMockStorageConfigReaderWriter creates a new mock instance.
func NewMockStorageConfigReaderWriter(ctrl *gomock.Controller) *MockStorageConfigReaderWriter {
	mock := &MockStorageConfigReaderWriter{ctrl: ctrl}
	mock.recorder = &MockStorageConfigReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageConfigReaderWriter) EXPECT() *MockStorageConfigReaderWriterMockRecorder {
	return m.recorder
}

// CheckVaultWriteAccess mocks base method.
func (m *MockStorageConfigReaderWriter) CheckVaultWriteAccess(d *types.DomainConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckVaultWriteAccess", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckVaultWriteAccess indicates an expected call of CheckVaultWriteAccess.
func (mr *MockStorageConfigReaderWriterMockRecorder) CheckVaultWriteAccess(d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckVaultWriteAccess", reflect.TypeOf((*MockStorageConfigReaderWriter)(nil).CheckVaultWriteAccess), d)
}

// StorageConfigRead mocks base method.
func (m *MockStorageConfigReaderWriter) StorageConfigRead(ctx context.Context, d *types.DomainConfig) (types.Cert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageConfigRead", ctx, d)
	ret0, _ := ret[0].(types.Cert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageConfigRead indicates an expected call of StorageConfigRead.
func (mr *MockStorageConfigReaderWriterMockRecorder) StorageConfigRead(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageConfigRead", reflect.TypeOf((*MockStorageConfigReaderWriter)(nil).StorageConfigRead), ctx, d)
}

// StorageConfigWrite mocks base method.
func (m *MockStorageConfigReaderWriter) StorageConfigWrite(d *types.DomainConfig, c types.Cert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageConfigWrite", d, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageConfigWrite indicates an expected call of StorageConfigWrite.
func (mr *MockStorageConfigReaderWriterMockRecorder) StorageConfigWrite(d, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageConfigWrite", reflect.TypeOf((*MockStorageConfigReaderWriter)(nil).StorageConfigWrite), d, c)
}
