// Code generated by tools/typegen/eds. DO NOT EDIT.
// Source: github.com/envoyproxy/go-control-plane/envoy/config/endpoint/v3
// Envoy version: v1.36.0
// To regenerate: make generate-eds

package eds

import (
	"strings"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

var _ = strings.ToUpper // suppress unused import

// ApiConfigSource_ApiType is an enum type.
type ApiConfigSource_ApiType string

const (
	ApiConfigSource_ApiType_DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE ApiConfigSource_ApiType = "DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE"
	ApiConfigSource_ApiType_REST                                  ApiConfigSource_ApiType = "REST"
	ApiConfigSource_ApiType_GRPC                                  ApiConfigSource_ApiType = "GRPC"
	ApiConfigSource_ApiType_DELTA_GRPC                            ApiConfigSource_ApiType = "DELTA_GRPC"
	ApiConfigSource_ApiType_AGGREGATED_GRPC                       ApiConfigSource_ApiType = "AGGREGATED_GRPC"
	ApiConfigSource_ApiType_AGGREGATED_DELTA_GRPC                 ApiConfigSource_ApiType = "AGGREGATED_DELTA_GRPC"
)

var (
	ApiConfigSource_ApiType_name = map[int32]string{
		0: "DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE",
		1: "REST",
		2: "GRPC",
		3: "DELTA_GRPC",
		5: "AGGREGATED_GRPC",
		6: "AGGREGATED_DELTA_GRPC",
	}
	ApiConfigSource_ApiType_value = map[string]int32{
		"DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE": 0,
		"REST":                                  1,
		"GRPC":                                  2,
		"DELTA_GRPC":                            3,
		"AGGREGATED_GRPC":                       5,
		"AGGREGATED_DELTA_GRPC":                 6,
	}
)

func (x ApiConfigSource_ApiType) ToInt() int32 {
	return ApiConfigSource_ApiType_value[strings.ToUpper(string(x))]
}

// ApiVersion is an enum type.
type ApiVersion string

const (
	ApiVersion_AUTO ApiVersion = "AUTO"
	ApiVersion_V2   ApiVersion = "V2"
	ApiVersion_V3   ApiVersion = "V3"
)

var (
	ApiVersion_name = map[int32]string{
		0: "AUTO",
		1: "V2",
		2: "V3",
	}
	ApiVersion_value = map[string]int32{
		"AUTO": 0,
		"V2":   1,
		"V3":   2,
	}
)

func (x ApiVersion) ToInt() int32 {
	return ApiVersion_value[strings.ToUpper(string(x))]
}

// CodecClientType is an enum type.
type CodecClientType string

var (
	CodecClientType_name  = map[int32]string{}
	CodecClientType_value = map[string]int32{}
)

func (x CodecClientType) ToInt() int32 {
	return CodecClientType_value[strings.ToUpper(string(x))]
}

// FractionalPercent_DenominatorType is an enum type.
type FractionalPercent_DenominatorType string

var (
	FractionalPercent_DenominatorType_name  = map[int32]string{}
	FractionalPercent_DenominatorType_value = map[string]int32{}
)

func (x FractionalPercent_DenominatorType) ToInt() int32 {
	return FractionalPercent_DenominatorType_value[strings.ToUpper(string(x))]
}

// HeaderValueOption_HeaderAppendAction is an enum type.
type HeaderValueOption_HeaderAppendAction string

const (
	HeaderValueOption_HeaderAppendAction_APPEND_IF_EXISTS_OR_ADD    HeaderValueOption_HeaderAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_ADD_IF_ABSENT              HeaderValueOption_HeaderAppendAction = "ADD_IF_ABSENT"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS_OR_ADD HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	HeaderValueOption_HeaderAppendAction_OVERWRITE_IF_EXISTS        HeaderValueOption_HeaderAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	HeaderValueOption_HeaderAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	HeaderValueOption_HeaderAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x HeaderValueOption_HeaderAppendAction) ToInt() int32 {
	return HeaderValueOption_HeaderAppendAction_value[strings.ToUpper(string(x))]
}

// HealthStatus is an enum type.
type HealthStatus string

const (
	HealthStatus_UNKNOWN   HealthStatus = "UNKNOWN"
	HealthStatus_HEALTHY   HealthStatus = "HEALTHY"
	HealthStatus_UNHEALTHY HealthStatus = "UNHEALTHY"
	HealthStatus_DRAINING  HealthStatus = "DRAINING"
	HealthStatus_TIMEOUT   HealthStatus = "TIMEOUT"
	HealthStatus_DEGRADED  HealthStatus = "DEGRADED"
)

var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "DRAINING",
		4: "TIMEOUT",
		5: "DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"DRAINING":  3,
		"TIMEOUT":   4,
		"DEGRADED":  5,
	}
)

func (x HealthStatus) ToInt() int32 {
	return HealthStatus_value[strings.ToUpper(string(x))]
}

// HttpProtocolOptions_HeadersWithUnderscoresAction is an enum type.
type HttpProtocolOptions_HeadersWithUnderscoresAction string

const (
	HttpProtocolOptions_HeadersWithUnderscoresAction_ALLOW          HttpProtocolOptions_HeadersWithUnderscoresAction = "ALLOW"
	HttpProtocolOptions_HeadersWithUnderscoresAction_REJECT_REQUEST HttpProtocolOptions_HeadersWithUnderscoresAction = "REJECT_REQUEST"
	HttpProtocolOptions_HeadersWithUnderscoresAction_DROP_HEADER    HttpProtocolOptions_HeadersWithUnderscoresAction = "DROP_HEADER"
)

var (
	HttpProtocolOptions_HeadersWithUnderscoresAction_name = map[int32]string{
		0: "ALLOW",
		1: "REJECT_REQUEST",
		2: "DROP_HEADER",
	}
	HttpProtocolOptions_HeadersWithUnderscoresAction_value = map[string]int32{
		"ALLOW":          0,
		"REJECT_REQUEST": 1,
		"DROP_HEADER":    2,
	}
)

func (x HttpProtocolOptions_HeadersWithUnderscoresAction) ToInt() int32 {
	return HttpProtocolOptions_HeadersWithUnderscoresAction_value[strings.ToUpper(string(x))]
}

// KeyValueAppend_KeyValueAppendAction is an enum type.
type KeyValueAppend_KeyValueAppendAction string

const (
	KeyValueAppend_KeyValueAppendAction_APPEND_IF_EXISTS_OR_ADD    KeyValueAppend_KeyValueAppendAction = "APPEND_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_ADD_IF_ABSENT              KeyValueAppend_KeyValueAppendAction = "ADD_IF_ABSENT"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS_OR_ADD KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS_OR_ADD"
	KeyValueAppend_KeyValueAppendAction_OVERWRITE_IF_EXISTS        KeyValueAppend_KeyValueAppendAction = "OVERWRITE_IF_EXISTS"
)

var (
	KeyValueAppend_KeyValueAppendAction_name = map[int32]string{
		0: "APPEND_IF_EXISTS_OR_ADD",
		1: "ADD_IF_ABSENT",
		2: "OVERWRITE_IF_EXISTS_OR_ADD",
		3: "OVERWRITE_IF_EXISTS",
	}
	KeyValueAppend_KeyValueAppendAction_value = map[string]int32{
		"APPEND_IF_EXISTS_OR_ADD":    0,
		"ADD_IF_ABSENT":              1,
		"OVERWRITE_IF_EXISTS_OR_ADD": 2,
		"OVERWRITE_IF_EXISTS":        3,
	}
)

func (x KeyValueAppend_KeyValueAppendAction) ToInt() int32 {
	return KeyValueAppend_KeyValueAppendAction_value[strings.ToUpper(string(x))]
}

// ProxyProtocolConfig_Version is an enum type.
type ProxyProtocolConfig_Version string

var (
	ProxyProtocolConfig_Version_name  = map[int32]string{}
	ProxyProtocolConfig_Version_value = map[string]int32{}
)

func (x ProxyProtocolConfig_Version) ToInt() int32 {
	return ProxyProtocolConfig_Version_value[strings.ToUpper(string(x))]
}

// ProxyProtocolPassThroughTLVs_PassTLVsMatchType is an enum type.
type ProxyProtocolPassThroughTLVs_PassTLVsMatchType string

var (
	ProxyProtocolPassThroughTLVs_PassTLVsMatchType_name  = map[int32]string{}
	ProxyProtocolPassThroughTLVs_PassTLVsMatchType_value = map[string]int32{}
)

func (x ProxyProtocolPassThroughTLVs_PassTLVsMatchType) ToInt() int32 {
	return ProxyProtocolPassThroughTLVs_PassTLVsMatchType_value[strings.ToUpper(string(x))]
}

// RequestMethod is an enum type.
type RequestMethod string

const (
	RequestMethod_METHOD_UNSPECIFIED RequestMethod = "METHOD_UNSPECIFIED"
	RequestMethod_GET                RequestMethod = "GET"
	RequestMethod_HEAD               RequestMethod = "HEAD"
	RequestMethod_POST               RequestMethod = "POST"
	RequestMethod_PUT                RequestMethod = "PUT"
	RequestMethod_DELETE             RequestMethod = "DELETE"
	RequestMethod_CONNECT            RequestMethod = "CONNECT"
	RequestMethod_OPTIONS            RequestMethod = "OPTIONS"
	RequestMethod_TRACE              RequestMethod = "TRACE"
	RequestMethod_PATCH              RequestMethod = "PATCH"
)

var (
	RequestMethod_name = map[int32]string{
		0: "METHOD_UNSPECIFIED",
		1: "GET",
		2: "HEAD",
		3: "POST",
		4: "PUT",
		5: "DELETE",
		6: "CONNECT",
		7: "OPTIONS",
		8: "TRACE",
		9: "PATCH",
	}
	RequestMethod_value = map[string]int32{
		"METHOD_UNSPECIFIED": 0,
		"GET":                1,
		"HEAD":               2,
		"POST":               3,
		"PUT":                4,
		"DELETE":             5,
		"CONNECT":            6,
		"OPTIONS":            7,
		"TRACE":              8,
		"PATCH":              9,
	}
)

func (x RequestMethod) ToInt() int32 {
	return RequestMethod_value[strings.ToUpper(string(x))]
}

// RoutingPriority is an enum type.
type RoutingPriority string

const (
	RoutingPriority_DEFAULT RoutingPriority = "DEFAULT"
	RoutingPriority_HIGH    RoutingPriority = "HIGH"
)

var (
	RoutingPriority_name = map[int32]string{
		0: "DEFAULT",
		1: "HIGH",
	}
	RoutingPriority_value = map[string]int32{
		"DEFAULT": 0,
		"HIGH":    1,
	}
)

func (x RoutingPriority) ToInt() int32 {
	return RoutingPriority_value[strings.ToUpper(string(x))]
}

// SocketAddress_Protocol is an enum type.
type SocketAddress_Protocol string

const (
	SocketAddress_Protocol_TCP SocketAddress_Protocol = "TCP"
	SocketAddress_Protocol_UDP SocketAddress_Protocol = "UDP"
)

var (
	SocketAddress_Protocol_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	SocketAddress_Protocol_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x SocketAddress_Protocol) ToInt() int32 {
	return SocketAddress_Protocol_value[strings.ToUpper(string(x))]
}

// SocketOption_SocketState is an enum type.
type SocketOption_SocketState string

const (
	SocketOption_SocketState_STATE_PREBIND   SocketOption_SocketState = "STATE_PREBIND"
	SocketOption_SocketState_STATE_BOUND     SocketOption_SocketState = "STATE_BOUND"
	SocketOption_SocketState_STATE_LISTENING SocketOption_SocketState = "STATE_LISTENING"
)

var (
	SocketOption_SocketState_name = map[int32]string{
		0: "STATE_PREBIND",
		1: "STATE_BOUND",
		2: "STATE_LISTENING",
	}
	SocketOption_SocketState_value = map[string]int32{
		"STATE_PREBIND":   0,
		"STATE_BOUND":     1,
		"STATE_LISTENING": 2,
	}
)

func (x SocketOption_SocketState) ToInt() int32 {
	return SocketOption_SocketState_value[strings.ToUpper(string(x))]
}

// TrafficDirection is an enum type.
type TrafficDirection string

const (
	TrafficDirection_UNSPECIFIED TrafficDirection = "UNSPECIFIED"
	TrafficDirection_INBOUND     TrafficDirection = "INBOUND"
	TrafficDirection_OUTBOUND    TrafficDirection = "OUTBOUND"
)

var (
	TrafficDirection_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INBOUND",
		2: "OUTBOUND",
	}
	TrafficDirection_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INBOUND":     1,
		"OUTBOUND":    2,
	}
)

func (x TrafficDirection) ToInt() int32 {
	return TrafficDirection_value[strings.ToUpper(string(x))]
}

// EDS represents the Envoy EDS configuration.
type EDS struct {
	ClusterName    string                        `json:"cluster_name,omitempty"`
	Endpoints      []*LocalityLbEndpoints        `json:"endpoints,omitempty"`
	NamedEndpoints map[string]*Endpoint          `json:"named_endpoints,omitempty"`
	Policy         *ClusterLoadAssignment_Policy `json:"policy,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *EDS) DeepCopyInto(out *EDS) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*LocalityLbEndpoints, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(LocalityLbEndpoints)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.NamedEndpoints != nil {
		in, out := &in.NamedEndpoints, &out.NamedEndpoints
		*out = make(map[string]*Endpoint, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(ClusterLoadAssignment_Policy)
		(*in).DeepCopyInto(*out)
	}
}

// Address represents the Envoy Address configuration.
type Address struct {
	SocketAddress        *SocketAddress        `json:"socket_address,omitempty"`
	Pipe                 *Pipe                 `json:"pipe,omitempty"`
	EnvoyInternalAddress *EnvoyInternalAddress `json:"envoy_internal_address,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
	if in.SocketAddress != nil {
		in, out := &in.SocketAddress, &out.SocketAddress
		*out = new(SocketAddress)
		(*in).DeepCopyInto(*out)
	}
	if in.Pipe != nil {
		in, out := &in.Pipe, &out.Pipe
		*out = new(Pipe)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyInternalAddress != nil {
		in, out := &in.EnvoyInternalAddress, &out.EnvoyInternalAddress
		*out = new(EnvoyInternalAddress)
		(*in).DeepCopyInto(*out)
	}
}

// ApiConfigSource represents the Envoy ApiConfigSource configuration.
type ApiConfigSource struct {
	ApiType                   ApiConfigSource_ApiType `json:"api_type,omitempty"`
	TransportApiVersion       ApiVersion              `json:"transport_api_version,omitempty"`
	ClusterNames              []string                `json:"cluster_names,omitempty"`
	GrpcServices              []*GrpcService          `json:"grpc_services,omitempty"`
	RefreshDelay              *string                 `json:"refresh_delay,omitempty"`
	RequestTimeout            *string                 `json:"request_timeout,omitempty"`
	RateLimitSettings         *RateLimitSettings      `json:"rate_limit_settings,omitempty"`
	SetNodeOnFirstMessageOnly bool                    `json:"set_node_on_first_message_only,omitempty"`
	ConfigValidators          []*TypedExtensionConfig `json:"config_validators,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ApiConfigSource) DeepCopyInto(out *ApiConfigSource) {
	*out = *in
	if in.ClusterNames != nil {
		in, out := &in.ClusterNames, &out.ClusterNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GrpcServices != nil {
		in, out := &in.GrpcServices, &out.GrpcServices
		*out = make([]*GrpcService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(GrpcService)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RefreshDelay != nil {
		in, out := &in.RefreshDelay, &out.RefreshDelay
		*out = new(string)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(string)
		**out = **in
	}
	if in.RateLimitSettings != nil {
		in, out := &in.RateLimitSettings, &out.RateLimitSettings
		*out = new(RateLimitSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigValidators != nil {
		in, out := &in.ConfigValidators, &out.ConfigValidators
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// BackoffStrategy represents the Envoy BackoffStrategy configuration.
type BackoffStrategy struct {
	BaseInterval *string `json:"base_interval,omitempty"`
	MaxInterval  *string `json:"max_interval,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *BackoffStrategy) DeepCopyInto(out *BackoffStrategy) {
	*out = *in
	if in.BaseInterval != nil {
		in, out := &in.BaseInterval, &out.BaseInterval
		*out = new(string)
		**out = **in
	}
	if in.MaxInterval != nil {
		in, out := &in.MaxInterval, &out.MaxInterval
		*out = new(string)
		**out = **in
	}
}

// BuildVersion represents the Envoy BuildVersion configuration.
type BuildVersion struct {
	Version *SemanticVersion `json:"version,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Metadata *runtime.RawExtension `json:"metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *BuildVersion) DeepCopyInto(out *BuildVersion) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(SemanticVersion)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// ClusterLoadAssignment_Policy represents the Envoy ClusterLoadAssignment_Policy configuration.
type ClusterLoadAssignment_Policy struct {
	DropOverloads          []*ClusterLoadAssignment_Policy_DropOverload `json:"drop_overloads,omitempty"`
	OverprovisioningFactor *uint32                                      `json:"overprovisioning_factor,omitempty"`
	EndpointStaleAfter     *string                                      `json:"endpoint_stale_after,omitempty"`
	WeightedPriorityHealth bool                                         `json:"weighted_priority_health,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterLoadAssignment_Policy) DeepCopyInto(out *ClusterLoadAssignment_Policy) {
	*out = *in
	if in.DropOverloads != nil {
		in, out := &in.DropOverloads, &out.DropOverloads
		*out = make([]*ClusterLoadAssignment_Policy_DropOverload, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(ClusterLoadAssignment_Policy_DropOverload)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(uint32)
		**out = **in
	}
	if in.EndpointStaleAfter != nil {
		in, out := &in.EndpointStaleAfter, &out.EndpointStaleAfter
		*out = new(string)
		**out = **in
	}
}

// ClusterLoadAssignment_Policy_DropOverload represents the Envoy ClusterLoadAssignment_Policy_DropOverload configuration.
type ClusterLoadAssignment_Policy_DropOverload struct {
	Category       string             `json:"category,omitempty"`
	DropPercentage *FractionalPercent `json:"drop_percentage,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ClusterLoadAssignment_Policy_DropOverload) DeepCopyInto(out *ClusterLoadAssignment_Policy_DropOverload) {
	*out = *in
	if in.DropPercentage != nil {
		in, out := &in.DropPercentage, &out.DropPercentage
		*out = new(FractionalPercent)
		(*in).DeepCopyInto(*out)
	}
}

// ConfigSource represents the Envoy ConfigSource configuration.
type ConfigSource struct {
	Path             string            `json:"path,omitempty"`
	PathConfigSource *PathConfigSource `json:"path_config_source,omitempty"`
	ApiConfigSource  *ApiConfigSource  `json:"api_config_source,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Ads                 *runtime.RawExtension `json:"ads,omitempty"`
	Self                *SelfConfigSource     `json:"self,omitempty"`
	InitialFetchTimeout *string               `json:"initial_fetch_timeout,omitempty"`
	ResourceApiVersion  ApiVersion            `json:"resource_api_version,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.PathConfigSource != nil {
		in, out := &in.PathConfigSource, &out.PathConfigSource
		*out = new(PathConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ApiConfigSource != nil {
		in, out := &in.ApiConfigSource, &out.ApiConfigSource
		*out = new(ApiConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Ads != nil {
		in, out := &in.Ads, &out.Ads
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Self != nil {
		in, out := &in.Self, &out.Self
		*out = new(SelfConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialFetchTimeout != nil {
		in, out := &in.InitialFetchTimeout, &out.InitialFetchTimeout
		*out = new(string)
		**out = **in
	}
}

// DataSource represents the Envoy DataSource configuration.
type DataSource struct {
	Filename            string            `json:"filename,omitempty"`
	InlineBytes         []byte            `json:"inline_bytes,omitempty"`
	InlineString        string            `json:"inline_string,omitempty"`
	EnvironmentVariable string            `json:"environment_variable,omitempty"`
	WatchedDirectory    *WatchedDirectory `json:"watched_directory,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	if in.InlineBytes != nil {
		in, out := &in.InlineBytes, &out.InlineBytes
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.WatchedDirectory != nil {
		in, out := &in.WatchedDirectory, &out.WatchedDirectory
		*out = new(WatchedDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// Endpoint represents the Envoy Endpoint configuration.
type Endpoint struct {
	Address             *Address                      `json:"address,omitempty"`
	HealthCheckConfig   *Endpoint_HealthCheckConfig   `json:"health_check_config,omitempty"`
	Hostname            string                        `json:"hostname,omitempty"`
	AdditionalAddresses []*Endpoint_AdditionalAddress `json:"additional_addresses,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthCheckConfig != nil {
		in, out := &in.HealthCheckConfig, &out.HealthCheckConfig
		*out = new(Endpoint_HealthCheckConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalAddresses != nil {
		in, out := &in.AdditionalAddresses, &out.AdditionalAddresses
		*out = make([]*Endpoint_AdditionalAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(Endpoint_AdditionalAddress)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// Endpoint_AdditionalAddress represents the Envoy Endpoint_AdditionalAddress configuration.
type Endpoint_AdditionalAddress struct {
	Address *Address `json:"address,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Endpoint_AdditionalAddress) DeepCopyInto(out *Endpoint_AdditionalAddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		(*in).DeepCopyInto(*out)
	}
}

// Endpoint_HealthCheckConfig represents the Envoy Endpoint_HealthCheckConfig configuration.
type Endpoint_HealthCheckConfig struct {
	PortValue                uint32   `json:"port_value,omitempty"`
	Hostname                 string   `json:"hostname,omitempty"`
	Address                  *Address `json:"address,omitempty"`
	DisableActiveHealthCheck bool     `json:"disable_active_health_check,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Endpoint_HealthCheckConfig) DeepCopyInto(out *Endpoint_HealthCheckConfig) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(Address)
		(*in).DeepCopyInto(*out)
	}
}

// EnvoyInternalAddress represents the Envoy EnvoyInternalAddress configuration.
type EnvoyInternalAddress struct {
	ServerListenerName string `json:"server_listener_name,omitempty"`
	EndpointId         string `json:"endpoint_id,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *EnvoyInternalAddress) DeepCopyInto(out *EnvoyInternalAddress) {
	*out = *in
}

// FractionalPercent represents the Envoy FractionalPercent configuration.
type FractionalPercent struct {
	Numerator   uint32                            `json:"numerator,omitempty"`
	Denominator FractionalPercent_DenominatorType `json:"denominator,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *FractionalPercent) DeepCopyInto(out *FractionalPercent) {
	*out = *in
}

// GrpcService represents the Envoy GrpcService configuration.
type GrpcService struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	EnvoyGrpc *runtime.RawExtension `json:"envoy_grpc,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	GoogleGrpc *runtime.RawExtension `json:"google_grpc,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	SslCredentials *runtime.RawExtension `json:"ssl_credentials,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	LocalCredentials *runtime.RawExtension `json:"local_credentials,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	FromPlugin *runtime.RawExtension `json:"from_plugin,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	StsService      *runtime.RawExtension `json:"sts_service,omitempty"`
	StringValue     string                `json:"string_value,omitempty"`
	IntValue        int64                 `json:"int_value,omitempty"`
	Timeout         *string               `json:"timeout,omitempty"`
	InitialMetadata []*HeaderValue        `json:"initial_metadata,omitempty"`
	RetryPolicy     *RetryPolicy          `json:"retry_policy,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService) DeepCopyInto(out *GrpcService) {
	*out = *in
	if in.EnvoyGrpc != nil {
		in, out := &in.EnvoyGrpc, &out.EnvoyGrpc
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.GoogleGrpc != nil {
		in, out := &in.GoogleGrpc, &out.GoogleGrpc
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.SslCredentials != nil {
		in, out := &in.SslCredentials, &out.SslCredentials
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.LocalCredentials != nil {
		in, out := &in.LocalCredentials, &out.LocalCredentials
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.FromPlugin != nil {
		in, out := &in.FromPlugin, &out.FromPlugin
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.StsService != nil {
		in, out := &in.StsService, &out.StsService
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.InitialMetadata != nil {
		in, out := &in.InitialMetadata, &out.InitialMetadata
		*out = make([]*HeaderValue, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValue)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// GrpcService_EnvoyGrpc represents the Envoy GrpcService_EnvoyGrpc configuration.
type GrpcService_EnvoyGrpc struct {
	ClusterName             string       `json:"cluster_name,omitempty"`
	Authority               string       `json:"authority,omitempty"`
	RetryPolicy             *RetryPolicy `json:"retry_policy,omitempty"`
	MaxReceiveMessageLength *uint32      `json:"max_receive_message_length,omitempty"`
	SkipEnvoyHeaders        bool         `json:"skip_envoy_headers,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_EnvoyGrpc) DeepCopyInto(out *GrpcService_EnvoyGrpc) {
	*out = *in
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxReceiveMessageLength != nil {
		in, out := &in.MaxReceiveMessageLength, &out.MaxReceiveMessageLength
		*out = new(uint32)
		**out = **in
	}
}

// GrpcService_GoogleGrpc represents the Envoy GrpcService_GoogleGrpc configuration.
type GrpcService_GoogleGrpc struct {
	TargetUri          string                                     `json:"target_uri,omitempty"`
	ChannelCredentials *GrpcService_GoogleGrpc_ChannelCredentials `json:"channel_credentials,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ChannelCredentialsPlugin []*runtime.RawExtension                   `json:"channel_credentials_plugin,omitempty"`
	CallCredentials          []*GrpcService_GoogleGrpc_CallCredentials `json:"call_credentials,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	CallCredentialsPlugin  []*runtime.RawExtension `json:"call_credentials_plugin,omitempty"`
	StatPrefix             string                  `json:"stat_prefix,omitempty"`
	CredentialsFactoryName string                  `json:"credentials_factory_name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Config                    *runtime.RawExtension `json:"config,omitempty"`
	PerStreamBufferLimitBytes *uint32               `json:"per_stream_buffer_limit_bytes,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ChannelArgs *runtime.RawExtension `json:"channel_args,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_GoogleGrpc) DeepCopyInto(out *GrpcService_GoogleGrpc) {
	*out = *in
	if in.ChannelCredentials != nil {
		in, out := &in.ChannelCredentials, &out.ChannelCredentials
		*out = new(GrpcService_GoogleGrpc_ChannelCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.ChannelCredentialsPlugin != nil {
		in, out := &in.ChannelCredentialsPlugin, &out.ChannelCredentialsPlugin
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(runtime.RawExtension)
				*(*out)[i] = *(*in)[i]
			}
		}
	}
	if in.CallCredentials != nil {
		in, out := &in.CallCredentials, &out.CallCredentials
		*out = make([]*GrpcService_GoogleGrpc_CallCredentials, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(GrpcService_GoogleGrpc_CallCredentials)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.CallCredentialsPlugin != nil {
		in, out := &in.CallCredentialsPlugin, &out.CallCredentialsPlugin
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(runtime.RawExtension)
				*(*out)[i] = *(*in)[i]
			}
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.PerStreamBufferLimitBytes != nil {
		in, out := &in.PerStreamBufferLimitBytes, &out.PerStreamBufferLimitBytes
		*out = new(uint32)
		**out = **in
	}
	if in.ChannelArgs != nil {
		in, out := &in.ChannelArgs, &out.ChannelArgs
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// GrpcService_GoogleGrpc_CallCredentials represents the Envoy GrpcService_GoogleGrpc_CallCredentials configuration.
type GrpcService_GoogleGrpc_CallCredentials struct {
	GoogleComputeEngine *bool `json:"google_compute_engine,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	GoogleIam *runtime.RawExtension `json:"google_iam,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_GoogleGrpc_CallCredentials) DeepCopyInto(out *GrpcService_GoogleGrpc_CallCredentials) {
	*out = *in
	if in.GoogleComputeEngine != nil {
		in, out := &in.GoogleComputeEngine, &out.GoogleComputeEngine
		*out = new(bool)
		**out = **in
	}
	if in.GoogleIam != nil {
		in, out := &in.GoogleIam, &out.GoogleIam
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// GrpcService_GoogleGrpc_ChannelArgs represents the Envoy GrpcService_GoogleGrpc_ChannelArgs configuration.
type GrpcService_GoogleGrpc_ChannelArgs struct {
	Args map[string]*GrpcService_GoogleGrpc_ChannelArgs_Value `json:"args,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_GoogleGrpc_ChannelArgs) DeepCopyInto(out *GrpcService_GoogleGrpc_ChannelArgs) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]*GrpcService_GoogleGrpc_ChannelArgs_Value, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// GrpcService_GoogleGrpc_ChannelArgs_Value represents the Envoy GrpcService_GoogleGrpc_ChannelArgs_Value configuration.
type GrpcService_GoogleGrpc_ChannelArgs_Value struct {
	GoogleDefault *bool `json:"google_default,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	ServiceAccountJwtAccess *runtime.RawExtension `json:"service_account_jwt_access,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_GoogleGrpc_ChannelArgs_Value) DeepCopyInto(out *GrpcService_GoogleGrpc_ChannelArgs_Value) {
	*out = *in
	if in.GoogleDefault != nil {
		in, out := &in.GoogleDefault, &out.GoogleDefault
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountJwtAccess != nil {
		in, out := &in.ServiceAccountJwtAccess, &out.ServiceAccountJwtAccess
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// GrpcService_GoogleGrpc_ChannelCredentials represents the Envoy GrpcService_GoogleGrpc_ChannelCredentials configuration.
type GrpcService_GoogleGrpc_ChannelCredentials struct {
	AccessToken string `json:"access_token,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *GrpcService_GoogleGrpc_ChannelCredentials) DeepCopyInto(out *GrpcService_GoogleGrpc_ChannelCredentials) {
	*out = *in
}

// HeaderValue represents the Envoy HeaderValue configuration.
type HeaderValue struct {
	Key      string `json:"key,omitempty"`
	Value    string `json:"value,omitempty"`
	RawValue []byte `json:"raw_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderValue) DeepCopyInto(out *HeaderValue) {
	*out = *in
	if in.RawValue != nil {
		in, out := &in.RawValue, &out.RawValue
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// HeaderValueOption represents the Envoy HeaderValueOption configuration.
type HeaderValueOption struct {
	Header         *HeaderValue                         `json:"header,omitempty"`
	Append         *bool                                `json:"append,omitempty"`
	AppendAction   HeaderValueOption_HeaderAppendAction `json:"append_action,omitempty"`
	KeepEmptyValue bool                                 `json:"keep_empty_value,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HeaderValueOption) DeepCopyInto(out *HeaderValueOption) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(HeaderValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = new(bool)
		**out = **in
	}
}

// HealthCheck_CustomHealthCheck represents the Envoy HealthCheck_CustomHealthCheck configuration.
type HealthCheck_CustomHealthCheck struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HealthCheck_CustomHealthCheck) DeepCopyInto(out *HealthCheck_CustomHealthCheck) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// HealthCheck_GrpcHealthCheck represents the Envoy HealthCheck_GrpcHealthCheck configuration.
type HealthCheck_GrpcHealthCheck struct {
	ServiceName     string               `json:"service_name,omitempty"`
	Authority       string               `json:"authority,omitempty"`
	InitialMetadata []*HeaderValueOption `json:"initial_metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HealthCheck_GrpcHealthCheck) DeepCopyInto(out *HealthCheck_GrpcHealthCheck) {
	*out = *in
	if in.InitialMetadata != nil {
		in, out := &in.InitialMetadata, &out.InitialMetadata
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// HealthCheck_HttpHealthCheck represents the Envoy HealthCheck_HttpHealthCheck configuration.
type HealthCheck_HttpHealthCheck struct {
	Host                   string                 `json:"host,omitempty"`
	Path                   string                 `json:"path,omitempty"`
	Send                   *HealthCheck_Payload   `json:"send,omitempty"`
	Receive                []*HealthCheck_Payload `json:"receive,omitempty"`
	ResponseBufferSize     *uint64                `json:"response_buffer_size,omitempty"`
	RequestHeadersToAdd    []*HeaderValueOption   `json:"request_headers_to_add,omitempty"`
	RequestHeadersToRemove []string               `json:"request_headers_to_remove,omitempty"`
	ExpectedStatuses       []*Int64Range          `json:"expected_statuses,omitempty"`
	RetriableStatuses      []*Int64Range          `json:"retriable_statuses,omitempty"`
	CodecClientType        CodecClientType        `json:"codec_client_type,omitempty"`
	ServiceNameMatcher     *StringMatcher         `json:"service_name_matcher,omitempty"`
	Method                 RequestMethod          `json:"method,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HealthCheck_HttpHealthCheck) DeepCopyInto(out *HealthCheck_HttpHealthCheck) {
	*out = *in
	if in.Send != nil {
		in, out := &in.Send, &out.Send
		*out = new(HealthCheck_Payload)
		(*in).DeepCopyInto(*out)
	}
	if in.Receive != nil {
		in, out := &in.Receive, &out.Receive
		*out = make([]*HealthCheck_Payload, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HealthCheck_Payload)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ResponseBufferSize != nil {
		in, out := &in.ResponseBufferSize, &out.ResponseBufferSize
		*out = new(uint64)
		**out = **in
	}
	if in.RequestHeadersToAdd != nil {
		in, out := &in.RequestHeadersToAdd, &out.RequestHeadersToAdd
		*out = make([]*HeaderValueOption, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HeaderValueOption)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RequestHeadersToRemove != nil {
		in, out := &in.RequestHeadersToRemove, &out.RequestHeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpectedStatuses != nil {
		in, out := &in.ExpectedStatuses, &out.ExpectedStatuses
		*out = make([]*Int64Range, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(Int64Range)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.RetriableStatuses != nil {
		in, out := &in.RetriableStatuses, &out.RetriableStatuses
		*out = make([]*Int64Range, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(Int64Range)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ServiceNameMatcher != nil {
		in, out := &in.ServiceNameMatcher, &out.ServiceNameMatcher
		*out = new(StringMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// HealthCheck_Payload represents the Envoy HealthCheck_Payload configuration.
type HealthCheck_Payload struct {
	Text   string `json:"text,omitempty"`
	Binary []byte `json:"binary,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HealthCheck_Payload) DeepCopyInto(out *HealthCheck_Payload) {
	*out = *in
	if in.Binary != nil {
		in, out := &in.Binary, &out.Binary
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// HealthCheck_TcpHealthCheck represents the Envoy HealthCheck_TcpHealthCheck configuration.
type HealthCheck_TcpHealthCheck struct {
	Send                *HealthCheck_Payload   `json:"send,omitempty"`
	Receive             []*HealthCheck_Payload `json:"receive,omitempty"`
	ProxyProtocolConfig *ProxyProtocolConfig   `json:"proxy_protocol_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HealthCheck_TcpHealthCheck) DeepCopyInto(out *HealthCheck_TcpHealthCheck) {
	*out = *in
	if in.Send != nil {
		in, out := &in.Send, &out.Send
		*out = new(HealthCheck_Payload)
		(*in).DeepCopyInto(*out)
	}
	if in.Receive != nil {
		in, out := &in.Receive, &out.Receive
		*out = make([]*HealthCheck_Payload, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(HealthCheck_Payload)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.ProxyProtocolConfig != nil {
		in, out := &in.ProxyProtocolConfig, &out.ProxyProtocolConfig
		*out = new(ProxyProtocolConfig)
		(*in).DeepCopyInto(*out)
	}
}

// HttpUri represents the Envoy HttpUri configuration.
type HttpUri struct {
	Uri     string  `json:"uri,omitempty"`
	Timeout *string `json:"timeout,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *HttpUri) DeepCopyInto(out *HttpUri) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
}

// Int64Range represents the Envoy Int64Range configuration.
type Int64Range struct {
	Start int64 `json:"start,omitempty"`
	End   int64 `json:"end,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Int64Range) DeepCopyInto(out *Int64Range) {
	*out = *in
}

// JsonFormatOptions represents the Envoy JsonFormatOptions configuration.
type JsonFormatOptions struct {
	SortProperties bool `json:"sort_properties,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *JsonFormatOptions) DeepCopyInto(out *JsonFormatOptions) {
	*out = *in
}

// LbEndpoint represents the Envoy LbEndpoint configuration.
type LbEndpoint struct {
	Endpoint            *Endpoint    `json:"endpoint,omitempty"`
	EndpointName        string       `json:"endpoint_name,omitempty"`
	HealthStatus        HealthStatus `json:"health_status,omitempty"`
	Metadata            *Metadata    `json:"metadata,omitempty"`
	LoadBalancingWeight *uint32      `json:"load_balancing_weight,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LbEndpoint) DeepCopyInto(out *LbEndpoint) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(Endpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancingWeight != nil {
		in, out := &in.LoadBalancingWeight, &out.LoadBalancingWeight
		*out = new(uint32)
		**out = **in
	}
}

// LedsClusterLocalityConfig represents the Envoy LedsClusterLocalityConfig configuration.
type LedsClusterLocalityConfig struct {
	LedsConfig         *ConfigSource `json:"leds_config,omitempty"`
	LedsCollectionName string        `json:"leds_collection_name,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LedsClusterLocalityConfig) DeepCopyInto(out *LedsClusterLocalityConfig) {
	*out = *in
	if in.LedsConfig != nil {
		in, out := &in.LedsConfig, &out.LedsConfig
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
}

// Locality represents the Envoy Locality configuration.
type Locality struct {
	Region  string `json:"region,omitempty"`
	Zone    string `json:"zone,omitempty"`
	SubZone string `json:"sub_zone,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Locality) DeepCopyInto(out *Locality) {
	*out = *in
}

// LocalityLbEndpoints represents the Envoy LocalityLbEndpoints configuration.
type LocalityLbEndpoints struct {
	Locality    *Locality     `json:"locality,omitempty"`
	Metadata    *Metadata     `json:"metadata,omitempty"`
	LbEndpoints []*LbEndpoint `json:"lb_endpoints,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	LoadBalancerEndpoints     *runtime.RawExtension      `json:"load_balancer_endpoints,omitempty"`
	LedsClusterLocalityConfig *LedsClusterLocalityConfig `json:"leds_cluster_locality_config,omitempty"`
	LoadBalancingWeight       *uint32                    `json:"load_balancing_weight,omitempty"`
	Priority                  uint32                     `json:"priority,omitempty"`
	Proximity                 *uint32                    `json:"proximity,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LocalityLbEndpoints) DeepCopyInto(out *LocalityLbEndpoints) {
	*out = *in
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = new(Locality)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(Metadata)
		(*in).DeepCopyInto(*out)
	}
	if in.LbEndpoints != nil {
		in, out := &in.LbEndpoints, &out.LbEndpoints
		*out = make([]*LbEndpoint, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(LbEndpoint)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.LoadBalancerEndpoints != nil {
		in, out := &in.LoadBalancerEndpoints, &out.LoadBalancerEndpoints
		*out = new(runtime.RawExtension)
		**out = **in
	}
	if in.LedsClusterLocalityConfig != nil {
		in, out := &in.LedsClusterLocalityConfig, &out.LedsClusterLocalityConfig
		*out = new(LedsClusterLocalityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancingWeight != nil {
		in, out := &in.LoadBalancingWeight, &out.LoadBalancingWeight
		*out = new(uint32)
		**out = **in
	}
	if in.Proximity != nil {
		in, out := &in.Proximity, &out.Proximity
		*out = new(uint32)
		**out = **in
	}
}

// LocalityLbEndpoints_LbEndpointList represents the Envoy LocalityLbEndpoints_LbEndpointList configuration.
type LocalityLbEndpoints_LbEndpointList struct {
	LbEndpoints []*LbEndpoint `json:"lb_endpoints,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *LocalityLbEndpoints_LbEndpointList) DeepCopyInto(out *LocalityLbEndpoints_LbEndpointList) {
	*out = *in
	if in.LbEndpoints != nil {
		in, out := &in.LbEndpoints, &out.LbEndpoints
		*out = make([]*LbEndpoint, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(LbEndpoint)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// Metadata represents the Envoy Metadata configuration.
type Metadata struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	FilterMetadata map[string]*runtime.RawExtension `json:"filter_metadata,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedFilterMetadata map[string]*runtime.RawExtension `json:"typed_filter_metadata,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
	if in.FilterMetadata != nil {
		in, out := &in.FilterMetadata, &out.FilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TypedFilterMetadata != nil {
		in, out := &in.TypedFilterMetadata, &out.TypedFilterMetadata
		*out = make(map[string]*runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// PathConfigSource represents the Envoy PathConfigSource configuration.
type PathConfigSource struct {
	Path             string            `json:"path,omitempty"`
	WatchedDirectory *WatchedDirectory `json:"watched_directory,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *PathConfigSource) DeepCopyInto(out *PathConfigSource) {
	*out = *in
	if in.WatchedDirectory != nil {
		in, out := &in.WatchedDirectory, &out.WatchedDirectory
		*out = new(WatchedDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// Pipe represents the Envoy Pipe configuration.
type Pipe struct {
	Path string `json:"path,omitempty"`
	Mode uint32 `json:"mode,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *Pipe) DeepCopyInto(out *Pipe) {
	*out = *in
}

// ProxyProtocolConfig represents the Envoy ProxyProtocolConfig configuration.
type ProxyProtocolConfig struct {
	Version         ProxyProtocolConfig_Version   `json:"version,omitempty"`
	PassThroughTlvs *ProxyProtocolPassThroughTLVs `json:"pass_through_tlvs,omitempty"`
	AddedTlvs       []*TlvEntry                   `json:"added_tlvs,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ProxyProtocolConfig) DeepCopyInto(out *ProxyProtocolConfig) {
	*out = *in
	if in.PassThroughTlvs != nil {
		in, out := &in.PassThroughTlvs, &out.PassThroughTlvs
		*out = new(ProxyProtocolPassThroughTLVs)
		(*in).DeepCopyInto(*out)
	}
	if in.AddedTlvs != nil {
		in, out := &in.AddedTlvs, &out.AddedTlvs
		*out = make([]*TlvEntry, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TlvEntry)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// ProxyProtocolPassThroughTLVs represents the Envoy ProxyProtocolPassThroughTLVs configuration.
type ProxyProtocolPassThroughTLVs struct {
	MatchType ProxyProtocolPassThroughTLVs_PassTLVsMatchType `json:"match_type,omitempty"`
	TlvType   []uint32                                       `json:"tlv_type,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *ProxyProtocolPassThroughTLVs) DeepCopyInto(out *ProxyProtocolPassThroughTLVs) {
	*out = *in
	if in.TlvType != nil {
		in, out := &in.TlvType, &out.TlvType
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// RateLimitSettings represents the Envoy RateLimitSettings configuration.
type RateLimitSettings struct {
	MaxTokens *uint32  `json:"max_tokens,omitempty"`
	FillRate  *float64 `json:"fill_rate,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RateLimitSettings) DeepCopyInto(out *RateLimitSettings) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(uint32)
		**out = **in
	}
	if in.FillRate != nil {
		in, out := &in.FillRate, &out.FillRate
		*out = new(float64)
		**out = **in
	}
}

// RemoteDataSource represents the Envoy RemoteDataSource configuration.
type RemoteDataSource struct {
	HttpUri     *HttpUri     `json:"http_uri,omitempty"`
	Sha256      string       `json:"sha256,omitempty"`
	RetryPolicy *RetryPolicy `json:"retry_policy,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RemoteDataSource) DeepCopyInto(out *RemoteDataSource) {
	*out = *in
	if in.HttpUri != nil {
		in, out := &in.HttpUri, &out.HttpUri
		*out = new(HttpUri)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// RetryPolicy represents the Envoy RetryPolicy configuration.
type RetryPolicy struct {
	RetryBackOff                  *BackoffStrategy                  `json:"retry_back_off,omitempty"`
	NumRetries                    *uint32                           `json:"num_retries,omitempty"`
	RetryOn                       string                            `json:"retry_on,omitempty"`
	RetryPriority                 *RetryPolicy_RetryPriority        `json:"retry_priority,omitempty"`
	RetryHostPredicate            []*RetryPolicy_RetryHostPredicate `json:"retry_host_predicate,omitempty"`
	HostSelectionRetryMaxAttempts int64                             `json:"host_selection_retry_max_attempts,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.RetryBackOff != nil {
		in, out := &in.RetryBackOff, &out.RetryBackOff
		*out = new(BackoffStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.NumRetries != nil {
		in, out := &in.NumRetries, &out.NumRetries
		*out = new(uint32)
		**out = **in
	}
	if in.RetryPriority != nil {
		in, out := &in.RetryPriority, &out.RetryPriority
		*out = new(RetryPolicy_RetryPriority)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryHostPredicate != nil {
		in, out := &in.RetryHostPredicate, &out.RetryHostPredicate
		*out = make([]*RetryPolicy_RetryHostPredicate, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(RetryPolicy_RetryHostPredicate)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
}

// RetryPolicy_RetryHostPredicate represents the Envoy RetryPolicy_RetryHostPredicate configuration.
type RetryPolicy_RetryHostPredicate struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryHostPredicate) DeepCopyInto(out *RetryPolicy_RetryHostPredicate) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// RetryPolicy_RetryPriority represents the Envoy RetryPolicy_RetryPriority configuration.
type RetryPolicy_RetryPriority struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *RetryPolicy_RetryPriority) DeepCopyInto(out *RetryPolicy_RetryPriority) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// SelfConfigSource represents the Envoy SelfConfigSource configuration.
type SelfConfigSource struct {
	TransportApiVersion ApiVersion `json:"transport_api_version,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SelfConfigSource) DeepCopyInto(out *SelfConfigSource) {
	*out = *in
}

// SemanticVersion represents the Envoy SemanticVersion configuration.
type SemanticVersion struct {
	MajorNumber uint32 `json:"major_number,omitempty"`
	MinorNumber uint32 `json:"minor_number,omitempty"`
	Patch       uint32 `json:"patch,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SemanticVersion) DeepCopyInto(out *SemanticVersion) {
	*out = *in
}

// SocketAddress represents the Envoy SocketAddress configuration.
type SocketAddress struct {
	Protocol                 SocketAddress_Protocol `json:"protocol,omitempty"`
	Address                  string                 `json:"address,omitempty"`
	PortValue                uint32                 `json:"port_value,omitempty"`
	NamedPort                string                 `json:"named_port,omitempty"`
	ResolverName             string                 `json:"resolver_name,omitempty"`
	Ipv4Compat               bool                   `json:"ipv4_compat,omitempty"`
	NetworkNamespaceFilepath string                 `json:"network_namespace_filepath,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SocketAddress) DeepCopyInto(out *SocketAddress) {
	*out = *in
}

// StringMatcher represents the Envoy StringMatcher configuration.
type StringMatcher struct {
	IgnoreCase bool `json:"ignore_case,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *StringMatcher) DeepCopyInto(out *StringMatcher) {
	*out = *in
}

// SubstitutionFormatString represents the Envoy SubstitutionFormatString configuration.
type SubstitutionFormatString struct {
	OmitEmptyValues   bool                    `json:"omit_empty_values,omitempty"`
	ContentType       string                  `json:"content_type,omitempty"`
	Formatters        []*TypedExtensionConfig `json:"formatters,omitempty"`
	JsonFormatOptions *JsonFormatOptions      `json:"json_format_options,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *SubstitutionFormatString) DeepCopyInto(out *SubstitutionFormatString) {
	*out = *in
	if in.Formatters != nil {
		in, out := &in.Formatters, &out.Formatters
		*out = make([]*TypedExtensionConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				(*out)[i] = new(TypedExtensionConfig)
				(*in)[i].DeepCopyInto((*out)[i])
			}
		}
	}
	if in.JsonFormatOptions != nil {
		in, out := &in.JsonFormatOptions, &out.JsonFormatOptions
		*out = new(JsonFormatOptions)
		(*in).DeepCopyInto(*out)
	}
}

// TlvEntry represents the Envoy TlvEntry configuration.
type TlvEntry struct {
	Type         uint32                    `json:"type,omitempty"`
	Value        []byte                    `json:"value,omitempty"`
	FormatString *SubstitutionFormatString `json:"format_string,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TlvEntry) DeepCopyInto(out *TlvEntry) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.FormatString != nil {
		in, out := &in.FormatString, &out.FormatString
		*out = new(SubstitutionFormatString)
		(*in).DeepCopyInto(*out)
	}
}

// TypedExtensionConfig represents the Envoy TypedExtensionConfig configuration.
type TypedExtensionConfig struct {
	Name string `json:"name,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	TypedConfig *runtime.RawExtension `json:"typed_config,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *TypedExtensionConfig) DeepCopyInto(out *TypedExtensionConfig) {
	*out = *in
	if in.TypedConfig != nil {
		in, out := &in.TypedConfig, &out.TypedConfig
		*out = new(runtime.RawExtension)
		**out = **in
	}
}

// WatchedDirectory represents the Envoy WatchedDirectory configuration.
type WatchedDirectory struct {
	Path string `json:"path,omitempty"`
}

// DeepCopyInto copies the receiver into out.
func (in *WatchedDirectory) DeepCopyInto(out *WatchedDirectory) {
	*out = *in
}
