# =============================================================================
# Multi-Zone Backend Services for Load Balancing Testing
# =============================================================================
# Creates backend services in different "zones" (simulated with labels)
# for testing load balancing and failover functionality.
# =============================================================================

---
# Zone A - Backend 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a-1
  namespace: xds-system
  labels:
    app: backend
    zone: a
    instance: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-a-1
  template:
    metadata:
      labels:
        app: backend-a-1
        zone: a
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-a-1
  namespace: xds-system
spec:
  selector:
    app: backend-a-1
  ports:
    - port: 80
      targetPort: 80

---
# Zone A - Backend 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a-2
  namespace: xds-system
  labels:
    app: backend
    zone: a
    instance: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-a-2
  template:
    metadata:
      labels:
        app: backend-a-2
        zone: a
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-a-2
  namespace: xds-system
spec:
  selector:
    app: backend-a-2
  ports:
    - port: 80
      targetPort: 80

---
# Zone B - Backend 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b-1
  namespace: xds-system
  labels:
    app: backend
    zone: b
    instance: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-b-1
  template:
    metadata:
      labels:
        app: backend-b-1
        zone: b
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-b-1
  namespace: xds-system
spec:
  selector:
    app: backend-b-1
  ports:
    - port: 80
      targetPort: 80

---
# Zone B - Backend 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b-2
  namespace: xds-system
  labels:
    app: backend
    zone: b
    instance: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-b-2
  template:
    metadata:
      labels:
        app: backend-b-2
        zone: b
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-b-2
  namespace: xds-system
spec:
  selector:
    app: backend-b-2
  ports:
    - port: 80
      targetPort: 80

---
# Zone C - Backend 1 (Failover)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-c-1
  namespace: xds-system
  labels:
    app: backend
    zone: c
    instance: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-c-1
  template:
    metadata:
      labels:
        app: backend-c-1
        zone: c
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-c-1
  namespace: xds-system
spec:
  selector:
    app: backend-c-1
  ports:
    - port: 80
      targetPort: 80

