# =============================================================================
# Load Balancer Example - Multi-Zone Load Balancing with Failover
# =============================================================================
# This example demonstrates advanced load balancing features:
#   - Multi-zone/locality-aware load balancing
#   - Priority-based failover
#   - Health checks with circuit breakers
#   - Endpoint references for dynamic endpoint management
#
# Components:
#   - Endpoint resources for different zones
#   - Cluster with endpoint_refs and health checks
#   - Listener and Route for HTTP traffic
# =============================================================================

---
# Zone A Endpoints (Primary - Priority 0)
apiVersion: envoyxds.io/v1alpha1
kind: Endpoint
metadata:
  name: backend-zone-a
  namespace: xds-system
spec:
  endpoints:
    - locality:
        region: us-east-1
        zone: us-east-1a
      lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-a-1.xds-system.svc.cluster.local
                port_value: 80
          load_balancing_weight: 100
          health_status: HEALTHY
        - endpoint:
            address:
              socket_address:
                address: backend-a-2.xds-system.svc.cluster.local
                port_value: 80
          load_balancing_weight: 100
          health_status: HEALTHY
      load_balancing_weight: 100
      priority: 0  # Primary zone

---
# Zone B Endpoints (Primary - Priority 0)
apiVersion: envoyxds.io/v1alpha1
kind: Endpoint
metadata:
  name: backend-zone-b
  namespace: xds-system
spec:
  endpoints:
    - locality:
        region: us-east-1
        zone: us-east-1b
      lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-b-1.xds-system.svc.cluster.local
                port_value: 80
          load_balancing_weight: 100
          health_status: HEALTHY
        - endpoint:
            address:
              socket_address:
                address: backend-b-2.xds-system.svc.cluster.local
                port_value: 80
          load_balancing_weight: 100
          health_status: HEALTHY
      load_balancing_weight: 100
      priority: 0  # Primary zone

---
# Zone C Endpoints (Failover - Priority 1)
apiVersion: envoyxds.io/v1alpha1
kind: Endpoint
metadata:
  name: backend-zone-c
  namespace: xds-system
spec:
  endpoints:
    - locality:
        region: us-west-2
        zone: us-west-2a
      lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-c-1.xds-system.svc.cluster.local
                port_value: 80
          load_balancing_weight: 100
          health_status: HEALTHY
      load_balancing_weight: 100
      priority: 1  # Failover zone - only used when primary is unhealthy

---
# Cluster with endpoint_refs for dynamic endpoint management
# Merges endpoints from all referenced Endpoint resources
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: load-balanced-backend
  namespace: xds-system
spec:
  # Reference Endpoint resources - endpoints are merged from all refs
  endpoint_refs:
    - backend-zone-a
    - backend-zone-b
    - backend-zone-c
  connect_timeout: 0.5s
  type: STATIC
  lb_policy: ROUND_ROBIN
  # Enable locality-aware load balancing
  common_lb_config:
    healthy_panic_threshold:
      value: 50  # Route to all endpoints if <50% healthy
    locality_weighted_lb_config: {}
  # Health checks for automatic failover
  health_checks:
    - timeout: 2s
      interval: 5s
      unhealthy_threshold: 3
      healthy_threshold: 1
      http_health_check:
        path: /health
  # Circuit breaker protection
  circuit_breakers:
    thresholds:
      - priority: DEFAULT
        max_connections: 1000
        max_pending_requests: 1000
        max_requests: 2000
        max_retries: 3
      - priority: HIGH
        max_connections: 2000
        max_pending_requests: 2000
        max_requests: 4000
        max_retries: 5
  # Outlier detection for automatic endpoint ejection
  outlier_detection:
    consecutive_5xx: 5
    base_ejection_time: 30s
    max_ejection_percent: 50
    interval: 10s

---
# HTTP Listener
apiVersion: envoyxds.io/v1alpha1
kind: Listener
metadata:
  name: http
  namespace: xds-system
spec:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8080

---
# Route with retry policy for resilience
apiVersion: envoyxds.io/v1alpha1
kind: Route
metadata:
  name: load-balanced-route
  namespace: xds-system
spec:
  listener_refs:
    - http
  stat_prefix: load_balanced
  use_remote_address: true
  generate_request_id: true
  codec_type: AUTO
  route_config:
    name: lb_route
    virtual_hosts:
      - name: backend
        domains:
          - "*"
        routes:
          - match:
              prefix: /
            route:
              cluster: load-balanced-backend
              timeout: 30s
              retry_policy:
                retry_on: connect-failure,refused-stream,unavailable,cancelled,retriable-4xx,retriable-status-codes
                num_retries: 3
                per_try_timeout: 10s
                retry_host_predicate:
                  - name: envoy.retry_host_predicates.previous_hosts
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
                host_selection_retry_max_attempts: 3
                retriable_status_codes:
                  - 503
  http_filters:
    - name: envoy.filters.http.router
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

