# =============================================================================
# Multi-Environment Example - Production/Staging Targeting
# =============================================================================
# This example demonstrates how to target specific Envoy instances using
# cluster and node annotations. This allows different configurations for:
#   - Production vs Staging environments
#   - Different Envoy clusters/fleets
#   - Canary deployments
#
# Key Concepts:
#   - `clusters` annotation: Targets Envoy instances with matching node.cluster
#   - `nodes` annotation: Targets specific Envoy node IDs
#   - No annotations = "global/global" (default)
# =============================================================================

# =============================================================================
# PRODUCTION ENVIRONMENT
# Target: Envoy with node.cluster=production
# =============================================================================

---
# Production HTTP Listener
apiVersion: envoyxds.io/v1alpha1
kind: Listener
metadata:
  name: http
  namespace: xds-system
  annotations:
    clusters: "production,staging"
spec:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8080
---
# Production Backend Cluster (high availability settings)
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: backend-production
  namespace: xds-system
  annotations:
    clusters: "production"
spec:
  connect_timeout: 0.25s
  type: STRICT_DNS
  lb_policy: LEAST_REQUEST  # Better for production
  load_assignment:
    cluster_name: backend-production
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: backend-prod.production.svc.cluster.local
                  port_value: 80
  # Aggressive health checks for production
  health_checks:
    - timeout: 1s
      interval: 3s
      unhealthy_threshold: 2
      healthy_threshold: 1
      http_health_check:
        path: /health
  # Circuit breakers for production
  circuit_breakers:
    thresholds:
      - max_connections: 10000
        max_pending_requests: 10000
        max_requests: 20000
        max_retries: 5
  # Outlier detection for automatic failover
  outlier_detection:
    consecutive_5xx: 3
    base_ejection_time: 30s
    max_ejection_percent: 30
    interval: 5s

---
# Production Route
apiVersion: envoyxds.io/v1alpha1
kind: Route
metadata:
  name: route-production
  namespace: xds-system
  annotations:
    clusters: "production"
spec:
  listener_refs:
    - http
  stat_prefix: production
  use_remote_address: true
  generate_request_id: true
  codec_type: AUTO
  route_config:
    name: production_route
    virtual_hosts:
      - name: production
        domains:
          - "*"
        response_headers_to_add:
          - header:
              key: x-environment
              value: "production"
        routes:
          - match:
              prefix: /
            route:
              cluster: backend-production
              timeout: 10s
              retry_policy:
                retry_on: connect-failure,refused-stream,unavailable,retriable-status-codes
                num_retries: 3
                retriable_status_codes:
                  - 503
  http_filters:
    - name: envoy.filters.http.router
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

# =============================================================================
# STAGING ENVIRONMENT
# Target: Envoy with node.cluster=staging
# =============================================================================

---
# Staging Backend Cluster (relaxed settings for testing)
apiVersion: envoyxds.io/v1alpha1
kind: Cluster
metadata:
  name: backend-staging
  namespace: xds-system
  annotations:
    clusters: "staging"
spec:
  connect_timeout: 5s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: backend-staging
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: backend-staging.staging.svc.cluster.local
                  port_value: 80
  # Less aggressive health checks for staging
  health_checks:
    - timeout: 5s
      interval: 10s
      unhealthy_threshold: 5
      healthy_threshold: 1
      http_health_check:
        path: /health

---
# Staging Route
apiVersion: envoyxds.io/v1alpha1
kind: Route
metadata:
  name: route-staging
  namespace: xds-system
  annotations:
    clusters: "staging"
spec:
  listener_refs:
    - http
  stat_prefix: staging
  use_remote_address: true
  generate_request_id: true
  codec_type: AUTO
  route_config:
    name: staging_route
    virtual_hosts:
      - name: staging
        domains:
          - "*"
        response_headers_to_add:
          - header:
              key: x-environment
              value: "staging"
        routes:
          - match:
              prefix: /
            route:
              cluster: backend-staging
              timeout: 30s  # Longer timeout for debugging
  http_filters:
    - name: envoy.filters.http.router
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

