# =============================================================================
# Sample Backend - nginx for testing
# =============================================================================
# This creates a simple nginx deployment to test the proxy configuration
# =============================================================================

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: xds-system
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: xds-system
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

